- package.json
- src/core/Icon/Icon.tsx
- src/core/Icon/__snapshots__/Icon.test.tsx.snap
- yarn.lock
- Move Emotion dependencies from devDependencies
- Fix: remove theme-object from ending up to svg-tag
> Release alpha 0.0.3

- src/components/Menu/Menu.tsx
- src/core/Panel/PanelExpansion.tsx
- Omit type from exported MenuLinkProps
>  Omit type from exported MenuLinkProps

- FAQ.md
- src/core/theme/fontFaces.css
- styleguide.config.js
https://github.com/google/fonts/issues/358#issuecomment-492324042
> Use Google Webfont's new feature to set display:swap with query param

- src/core/theme/colors.ts
Update to correct values from Designs
> Update correct depthSecondary values

- src/core/Button/Button.baseStyles.tsx
- src/core/Button/Button.md
- src/core/Button/__snapshots__/Button.test.tsx.snap
Same format used elsewhere like Block examples
> [Patch]Order button examples to separate groups

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Question.md
- .github/ISSUE_TEMPLATE/Support.md
Create issue templates, based on few different found from Github repos.
> Create issue templates

- src/core/Text/Text.md
- src/core/Text/Text.test.tsx
- src/core/Text/__snapshots__/Text.test.tsx.snap
Issue #188 
Working as expected but features were not included in tests and examples.
Closed issue #188 
Need to have tests and examples for components' API features
`yarn validate`
> Add Text smallScreen to tests

- src/core/theme/utils/typography.ts
Replace `any` with correct interface
Closes #193
Typescript
`yarn build` and `yarn validate`
> Replace any with correct interface

- src/core/Button/Button.baseStyles.tsx
- src/core/Button/Button.tsx
- src/core/Button/__snapshots__/Button.test.tsx.snap
Removed the conditional style application from button baseStyles. Added a  corresponding className to be added conditionally instead.
Closes #176 
Changes work fine in styleguide locally. Not tested elsewhere yet.
> [Refactor] Set button fullWidth using className

- src/components/Panel/PanelExpansion.tsx
- src/core/Colors/Colors.tsx
- src/core/Link/Link.baseStyles.ts
- src/core/Panel/PanelExpansion.baseStyles.tsx
- src/core/theme/colors.ts
- src/core/theme/utils/typography.ts
- src/reset/HtmlA/HtmlA.tsx
- src/utils/css/index.ts
Issue #152 
Closes #152 
Being consistent and use the same convention like in other places in the code.
`yarn validate`
> [Feature] index.ts for utils/css

- src/components/Form/ToggleButton.tsx
- src/components/Form/ToggleInput.tsx
- src/core/Form/Toggle/Toggle.baseStyles.tsx
- src/core/Form/Toggle/Toggle.tsx
- src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
When hovering mouse over disabled **Toggle**, mouse cursor will now change to give better feedback to the user.
Related #228
To give better feedback for the user when the component is in disabled state.
- `yarn test`
- manually testing with browser
> [Feature] Mouse cursor change for disabled Toggle

- src/components/Form/SearchInput.tsx
- src/components/Form/TextInput.tsx
- src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
- src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
When hovering mouse over disabled SearchInput & TextInput, mouse cursor will now change to give better feedback to the user.
Related #228 
To give better feedback for the user when the component is in disabled state.
- `yarn test`
- manually testing with browser
> [Feature] Mouse cursor change for disabled SearchInput & TextInput

- .github/CODEOWNERS
Update codeowners according to the project team
> Add more codeowners

- .styleguidist/spacing.md
- package.json
- src/core/Button/Button.baseStyles.tsx
- src/core/Colors/__snapshots__/Colors.test.tsx.snap
- src/core/Dropdown/Dropdown.baseStyles.tsx
- src/core/Expander/Expander.baseStyles.tsx
- src/core/Form/Toggle/Toggle.baseStyles.tsx
- src/core/Icon/Icon.tsx
- src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
- src/core/Link/Link.baseStyles.ts
- src/core/theme/colors.ts
- yarn.lock
Updated the library to use the latest, 0.7.1 release of the suomifi-design-tokens. Update came with some name changes to color tokens, which is a breaking change. Implemented the new token names to the component library.
Designs changed and we want to make all the breaking changes we can before the 1.0 release.
Running locally and yarn test.
> [Breakinghange] Update library to use design tokens version 0.7.1

- .styleguidist/components.md
- .styleguidist/introduction.md
- README.md
- Updated the README to reflect current situation
- Removed the mentions of bare accessible components usage as it is not currently working
Wanted to have up to date documentation.
> [Feature] Update documentation

- package.json
Increase version to 0.11.0
New version includes:
- Updated spacing tokens (#302)
- Fixes to documentation (#303)
> [Release] 0.11.0

- DEVELOPMENT.md
Adds a clarification to run `yarn` after pulling changes from the repo to install all the dependencies needed.
Closes #196 
To help contributors to get started with the repo.
> [Feature] Added note to run 'yarn' after pulling changes from the repo

- package.json
- All dependencies updated to the latest available version
- Tests and snapshots adjusted accordingly
- Implementation and typings adjusted accordingly
- No changes to functionality or public APIs were introduced
Fixes some vulnerable dependencies by update.
Some dependencies were starting fall out-of-date and needed to be updated as some even became vulnerable. Made sense to update everything at once as no major changes were required.
Tested with styleguidist, Create React App TypeScript project, SSR template and Suomifi Design System site.
> [Release] 0.12.0

- package.json
Increase version to 0.13.0.
Using skipLibCheck: false for TS compiler options caused errors with build. These issues have now been resolved and fixes are included in the release (#318).
To allow strict type checking in projects using the ui-components library, also typings for dependencies have to be valid and available.
> [Release] 0.13.0

- package.json
Raise version number to 0.14.0 in anticipation of release.
> [Release] 0.14.0

- FAQ.md
- README.md
Updates for github documentation to cover SSR and strict content security policy cases as well as some dependency version requirements.
Having up-to-date information about implementing the library helps our users to implement it and reduces the need for support actions from our side.
Content changes, so no testing done.
> [Feature] Add new instructions to Readme and FAQ

- package.json
Increase version to 0.15.0. The following changes were introduced after 0.14.0:
- Style alignments with style guide for Breadcrumb, Expander, Button, Dropdown, TextInput and Toggle. (#327, #328, #329, #331, #332, #335, #336)
- Documentation improvements and updates (#333, #334)
> [Release] 0.15.0

- .github/pull_request_template.md
This PR adds release notes to pull request template.
It is cumbersome to go through all PR's included in a release while gathering release notes. If all PR's would include one line or maximum of one paragraph description of the most important contents as release notes, this work would be much easier. It is also better and faster to write the notes when things are fresh in memory.
Release notes heading with instructions added to pull request template.
> [Feature] Improve pull request template.

- package.json
- yarn.lock
Fixes the error when tried to use LanguageMenu or Dropdown component.
Fixes the critical errors when trying to use the LanguageMenu or Dropdown component.
- Locally in new CRA project
- Fixes errors when trying to use LanguageMenu or Dropdown component (#340)
> [Fix] Update reach dependencies

- package.json
Increases version number to 0.15.1 Following fix was introduced after 0.15.0
- Fixes errors when trying to use LanguageMenu or Dropdown component (#340)
> [Release] 0.15.1

- package.json
- Fix typo in design tokens. Spacing insetXss is now insetXxs. (#350)
- Rounded top and bottom corners for Expander groups and separator between as detailed in the design. ([#338](https://github.com/vrk-kpa/suomifi-ui-components/pull/338))
- Language menu styles adjusted to match latest designs (#351)
- Add support for multiline link focus style by using box shadow. Remove link underline while focused. (#342)
- Fixed a bug in checkbox internal state handling. (#346)
- Fixed an accessibility bug regarding checkbox in controlled state (#347)
- Checkbox `hintText` color changed (#352)
- `open`, `defaultOpen` and `onClick` should now work as intended and documented with Expander (#330)
- Fixed an accessibility bug regarding Toggle switch in controlled state (#347)
- Removed mentions of bare …
> [Release] 0.16.0

- package.json
- Fix spacing of language menu items (#354)
> [Release] 0.16.1

- package.json
- yarn.lock
Update suomifi-icons and suomifi-design-tokens dependencies to latest available releases. These releases use semantic versioning and can be added with scope.
Updating to post 1.0 versions allows semantic versioning and use of scopes. This makes updating the dependencies easier and faster.
Tested using Styleguidist build locally.
- Update suomifi-icons and suomifi-design-tokens dependencies to latest
> [Feature] Update suomifi-icons and design-tokens

- package.json
This PR increases version number to 0.17.0.  Includes breaking changes!
Changes since 0.16.1:
- Button text-shadow and icon color changes (#357)
- Placeholder text for TextInput (#358)
- Breaking change: Icon is now using currentColor by default (#359)
- Name prop is now called visual placeholder and is ignored by screen readers. Label has been added as mandatory prop. (#360)
- Fix for checkbox status text spacing (#361)
- Fix for Toggle focus style logic (#362)
- Breaking changes: Support for multiple dropdown form use cases. Multiple breaking changes, see #363
- Reach UI dependencies updated to latest to fix dependency scope issue (#364)
- Update suomifi-icons and suomifi-design-tokens dependencies to latest and add scope (#365)
> [Release] 0.17.0

- src/core/Dropdown/Dropdown.md
- src/core/Form/Toggle/Toggle.md
- src/core/Text/Text.md
Small fixes to different components examples:
- Dropdown
- Text
- Toggle
No changes to actual implementation of the components, just the examples shown in the styleguidist.
Examples were not using the "rules" they should have.
The code in Markdown file for the styleguidist is little problematic as IDE:s doesn't seem to be able to find the issues so easily as with "normal" code. These problems were found when tested to use the example codes in a separate CRA TS project.
If someone tests now to copy these examples straight from the styleguidist, they have bigger change of success.
- Styleguidist run locally
- CRA TS project
- Fixed few component examples [Dropdown, Toggle, Text] (#367)
> [Fix] Changes to examples

- package.json
- Disable generated button with disabled-attribute (#371, thanks to @jteuho )
> [Release] 1.0.1

- package.json
Increase version from 1.0.1 to 1.1.0.
- `hintText` and `type` props added for TextInput (#378)
- Radiobutton component (#377)
- Textarea component (#376)
- `name` and `value` props added for Checkbox (#375).
- `tokens` prop discarded for unstyled Button variant. (#383)
- Checkbox's hintText style fixed. (#379)
- Suomifi-icons upgraded to 1.0.1 (#382)
- Update react-styleguidist and webpack  dependecies to fix potential vulnerabilities (#381)
> [Release] 1.1.0

- package.json
- yarn.lock
Upgrade vulnerable dependencies and add resolution for tsdx/ts-jest.
Multiple vulnerabilities in dependencies.
Tested using styleguidist build, create react app TS project, Suomi.fi design system site and SSR test app.
- Upgrade for vulnerable dependencies, no breaking changes.
> [BugFix] Upgrade vulnerable dependencies

- .styleguidist/styleguidist.sections.js
- src/core/VisuallyHidden/VisuallyHidden.md
- src/core/VisuallyHidden/VisuallyHidden.tsx
- src/index.tsx
This PR exports VisuallyHidden from the library and offers basic examples of its use.
This component was requested by the developers using the library, and since we already had an internal implementation of it, it is easy to comply.
Tested manually in styleguidist.
-Add VisuallyHidden component
> [Feature] Export VisuallyHidden from the library

- package.json
- src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
- src/core/Button/__snapshots__/Button.test.tsx.snap
- src/core/Chip/__snapshots__/Chip.test.tsx.snap
- src/core/Colors/__snapshots__/Colors.test.tsx.snap
- src/core/Dropdown/Dropdown.baseStyles.tsx
- src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/core/Expander/__snapshots__/Expander.test.tsx.snap
- src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
- src/core/Form/Checkbox/Checkbox.baseStyles.tsx
- src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- src/core/Form/RadioButton/RadioButton.baseStyles.tsx
- src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
- src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
- src/core/Form/SearchInput/SearchInput.baseStyles.tsx
- src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
- src/core/Form/TextInput/TextInput.baseStyles.tsx
- src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
- src/core/Form/Textarea/Textarea.baseStyles.tsx
- src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
- src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
- src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
- src/core/Link/__snapshots__/Link.test.tsx.snap
- src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
- src/core/theme/__snapshots__/tokens.test.tsx.snap
- yarn.lock
There were some recent updates and changes to the suomifi-icons and suomifi-design-tokens. This PR implements those changes to the ui-components.
* Two new icons added
* Changes to some color tokens, such as successBase
* Two new color tokens, depthDark2 and 3, added
depthDark2 was implemented in the placeholder texts of input elements and depthDark3 replaced the border color in form elements.
The library needs to stay up to date with the changes in the style guide.
Tested by automated tests and by running locally. Should still be tested in different projects and environments, since some dependencies were changed in the underlying libraries.
Breaking change: changes to color token values
Other changes: new tokens and icons due to updated suomifi-icons and suomifi-design-tokens
> [Feature] Update suomifi-icons and suomifi-design-tokens dependencies

- src/core/Breadcrumb/Breadcrumb.tsx
- src/core/Button/Button.tsx
- src/core/Button/__snapshots__/Button.test.tsx.snap
- src/core/Expander/ExpanderContent/ExpanderContent.tsx
- src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
- src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
- src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.tsx
- src/core/Form/Checkbox/Checkbox.tsx
- src/core/Form/Textarea/Textarea.tsx
- src/utils/aria.test.ts
- src/utils/aria.ts
This PR introduces fixes for aria attribute handling for multiple components. Empty aria attributes are now omitted completely and updating aria attributes are always present in DOM. This PR also includes a minor update to aria utils.
Some components were not updated due to bigger upcoming migration. These issues were documented to related tickets.
Empty or appearing aria attributes may not work as intended and needed to be fixed.
Tested with Styleguidist and Create React App using Mac OS and Safari, Chrome and Firefox.
- Fixes and improvements for aria attribute handling.
> [Fix] Aria attribute issues

- package.json
* Breaking changes ⚒️ : support for Aria-disabled, unstyled variant removed along with mouseNoFocus, ariaAssertiveDisabled and ariaAssertiveUnDisabled attributes (#420)
* Breaking changes: className removed from DropdownPopoverProps, TypeScript minimum supported version updated to 3.8. (#421)
* All dependencies but webpack updated to latest. (#421)
* Improve test run speed (#422)
* Fixes and improvements for aria attribute handling. (#423)
* Remove Internet Explorer native pseudo elements from text input (#424)
> Increase version number to 3.0.0-beta.1

- src/core/Button/__snapshots__/Button.test.tsx.snap
- src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
- src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
- src/core/theme/colors.ts
Previously added link button had gradient backgrounds where the gradient ran the wrong way. This PR fixes this issue.
Tested by running locally in styleguidist in Chrome
* Fix link button background gradient direction
> [Bugfix] Link button gradient direction

- src/core/Modal/Modal/Modal.baseStyles.tsx
- src/core/Modal/Modal/Modal.tsx
- src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
- src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
- src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
- src/reset/HtmlDiv/HtmlDiv.tsx
- src/reset/index.ts
This PR removes the fix for Modal NVDA cursor escaping issue as it proved to be not working as expected. In addition, small improvements for styles and component structure.
NVDA fix prevented normal focusing on items inside the modal with mouse.
The fix for NVDA cursor escaping the modal with events bubbling through the modal background was made as a last minute improvement and was not properly tested. Preventing mouse interactions with modal background overlay resulted in undesired side effect and blocked most mouse interactions inside the modal also.
Removing the fix will re-introduce the cursor escaping issue where a user is clicking non interactive elements on the modal dialog with mouse and NVDA on. This allows the cursor to escape to the underlying DOM elements and there seems to be …
> [Fix] Modal mouse event issue

- src/core/Expander/Expander/Expander.tsx
- src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
- src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
- src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
- src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx
- src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
- src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.baseStyles.tsx
- src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
This PR increases ExpanderGroup performance especially for use cases with large amounts of expanders in one expander group.
In addition, this PR fixes small font style issues.
ExpanderGroup was setting state for each Expander close or open event and sharing that state via context. This was causing redundant renders and change detection for all nested Expanders and also unnecessary expander open state comparisons. This caused ExpanderGroups with hundreds or more Expanders to become unusable.
In addition, there was a bug with font-family style which resulted into invalid css being built. 
Tested on MacOS with Safari, Edge, Chrome and Firefox with VoiceOver. Test environment was React Styleguidist build, Create React App TypeScript build and SSR test build. Performance was tested with 500 …
> [Fix] ExpanderGroup performance improvements

- package.json
This PR raises the package version to 3.0.1 in anticipation of a patch release.
> [Release] Raise version to 3.0.1

- package.json
This PR raises the version number of the library to 5.0.0 in anticipation of the release.
> [Release] v5.0.0

- package.json
This PR raises the version number for release 6.1.0-beta.2
Only automated tests.
> [Release] v.6.1.0-beta.2

- src/core/theme/SuomifiTheme/SuomifiTheme.ts
- src/core/theme/SuomifiTheme/gradients.ts
- src/core/theme/SuomifiTheme/shadows.ts
- src/core/theme/index.ts
- src/core/theme/utils/spacing.ts
- src/index.tsx
Fix the export of the design token and related types from the library.
Following typings should now work from now on:
- TypographyDesignTokens
- ColorDesignTokens
- SpacingDesignTokens
- RawDesignTokens
- ValueUnit
- RawColorDesignTokens
- ColorToken
- RawSpacingDesignTokens
- RawTypographyDesignTokens
- TypographyToken
Some of these were not reported but those were found also missing when doing the fix.
We got report that at least in version 6.0.0 typings of the suomifi-ui-components are somewhat broken. Issue seemed to be in the develop branch and therefore in the latest beta.
> ERROR in node_modules/suomifi-ui-components/dist/suomifi-ui-components.esm.d.ts(617,1380):
TS2304: Cannot find name 'TypographyToken'.
Report says that same problem with all the followings
- ValueUnit
- …
> [Fix] Design token types exports

- README.md
Adds a table of supported OS, browser and screen reader combinations to repo's README.
Easier to see supported combinations of the library with the help of the table.
- Add table of supported OS, browser and screen reader combinations to README
> [Feature] Add table of supported OS, browser and screen reader combinations

- package.json
Increases the version to `6.1.0-beta.3`
Changes:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.0-beta.2...develop
- Fix design token types exports, #534 
- Change node-sass to sass (Dart Sass), #533 
- Add table of supported OS, browser and screen reader combinations to README, #527
> [Release]6.1.0-beta.3

- src/utils/css/utils.ts
Change should not affect to anything.  Removed unused CSS code. Unused code was float fix
Developer team wanted remove unused old code.
On mac. With Chrome.
> [fix] Remove from utils. Removed unused CSS code

- package.json
This PR increases version number to 6.1.0.
All commits against the previous, 6.0.0, release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.0.0...5ca25b6a0b9d30ecbc49a7611d8a859a04ab1ab8
- Add SingleSelect component. (#503, #536)
- Add Alert and InlineAlert component. (#528, #531)
- Add Notification component. (#530)
- Add scrolling support
- Add max-height of 265px to options list
- Improve accessibility of MultiSelect.
- Fix documentation related to use of statics and components level.
- Add visible icon names to list view in documentation.
- Add whiteBaseToDepthLight1 gradient.
- Fix design token types exports
- Add table of supported OS, browser and screen reader combinations to README.
- Update vulnerable dependencies
- Revert node-sass and react-styleguidist move to …
> [Release] v6.1.0

- package.json
This PR increases version number to 6.1.1-beta.0.
All commits against the previous, 6.1.0, release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.0...6b9db0ef52ae38c4ebe7807959736a5634718f5a
**SingleSelect**:
- Fix crash when inputting special characters into input field
- Fix crash when starting to filter and item labels contain special characters
**MultiSelect**
- Fix crash when inputting special characters into input field
> [Release] Increase version number to 6.1.1-beta.0

- package.json
This PR increases version number to 6.1.1
All commits against the previous, 6.1.0, release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.0...2df4537b0765b7612eb528ed78150018bac96038
- Fix crash when inputting special characters into input field
- Fix crash when starting to filter and item labels contain special characters
- Fix crash when inputting special characters into input field
> [Release] 6.1.1

- .styleguidist/styleguidist.sections.js
- src/core/Notification/Notification.baseStyles.ts
- src/core/Notification/Notification.md
- src/core/Notification/Notification.tsx
- src/core/Notification/__snapshots__/Notification.test.tsx.snap
- src/index.tsx
Developer team found out that look and feel was't like it should be with short content. Close button was not aligned to right corner, with short content. PR makes look and feel as in designs. Also 2px removed from top margin of button.  Also Notification will be exported in project and will be visible in styleguidist.
Fixes the issue that look and feel does not look correct.
Look and feel was not according to layouts with short content.
On Mac and Chrome and Safari.
> [Fix] Notification layout

- package.json
This PR increases version number to 6.2.0-beta.0.
All commits against the previous, 6.1.1, release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.1...06113f096ce2a85161e0010af55dbe00a4a676aa
- Introduce LabelText component
- Introduce HintText component
- Introduce StatusText component
- Introduce Notification component
- Fix missing status text margin
- Replace TSDX with Rollup
- Introduce module based library instead of bundle
> [Release] Increase version number to 6.2.0-beta.0

- package.json
This PR increases version number to 6.2.0-beta.1.
All commits against the previous, 6.1.1, stable release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.1...c4b7e508def5fe88b203f8d097519eda773af705
All commits against the previous, 6.2.0-beta.0, beta release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.2.0-beta.0...c4b7e508def5fe88b203f8d097519eda773af705
- Introduce Toast component
> [Release] Increase version number to 6.2.0-beta.1

- .github/CODEOWNERS
Remove old team members which are no longer working on project.
Previous team members were automatically added as reviewers for PRs because of this for the file were they were, well, code owners.
> [Fix] Update codeowners

- package.json
This PR increases version number to 6.2.0-beta.2
All commits against the previous, 6.2.0-beta.1, **beta** release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.2.0-beta.1...1befd7c2cc155c0725e6426f401526c6b0ca61ad
All commits against the previous, 6.1.1, **stable** release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.1...1befd7c2cc155c0725e6426f401526c6b0ca61ad
- Fix MultiSelect's controlled state. Filter should now work after selection.
- Fix Modal text styles.
- Introducing new two new color tokens from Suomifi-design-tokens. "successDark1" and "warningLight1"
> [Release] Increase version number to 6.2.0-beta.2

- package.json
This PR increases version number to 6.2.0
All commits against the previous, 6.1.1, **stable** release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.1.1...87c6e8272a19356f8bdb05f8b03f2b7ebf0b120c
- Introduce Toast component
- Introduce LabelText component
- Introduce HintText component
- Introduce StatusText component
- Introduce Notification component
- Introducing new two new color tokens from Suomifi-design-tokens. "successDark1" and "warningLight1"
- Fix missing status text margin
- Fix MultiSelect's controlled state. Filter should now work after selection.
- Fix Modal text styles.
- Replace TSDX with Rollup
- Introduce module based library instead of bundle
> [Release] Increase version number to 6.2.0

- package.json
This PR increases version number to 6.2.1
All commits against the previous, 6.2.0, **stable** release:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.2.0...74697faf738f4a629fbeb16693a1f7f2c3ef46e1
- Remove duplicate div
- Fix item selection in non-controlled state
> [Release] Increase version number to 6.2.1

- .styleguidist/logger.md
- .styleguidist/styleguidist.sections.js
- src/core/Chip/Chip/Chip.tsx
- src/core/Dropdown/Dropdown/Dropdown.tsx
- src/core/Form/Checkbox/Checkbox.tsx
- src/core/Form/RadioButton/RadioButton.tsx
- src/core/Heading/Heading.tsx
- src/core/Icon/Icon.tsx
- src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
- src/core/Link/ExternalLink/ExternalLink.tsx
- src/core/Modal/Modal/Modal.tsx
- src/index.tsx
- src/utils/css/colors.ts
- src/utils/log/index.ts
- src/utils/log/logger.ts
Update logger. Logger to be exported util and not logging anything by default
With Webpack 5, users were having problems as the logger used inside the library uses environment variables.
This PR will remove the use of those env vars and instead will now use logger as an util.
By default, nothing is logged as we cannot know what environment and capabilities the user has.
To see the previous style of logging user can use it like this:
```tsx
import {  setLogger } from "suomifi-ui-components";
setLogger(console);
```
Or something like the following:
```tsx
import {  setLogger, Logger } from "suomifi-ui-components";
const logging: Logger = {
log: (val: string) => {
console.log(`[LOG] ${val}`);
},
warn: (val: string) => {
console.warn(`[WAR] ${val}`);
},
error: (val: string) => { …
```
> [Fix/Feature] Change using of env variables to logger util

- package.json
Increases the version to `7.0.0-beta.0`
Changes:
https://github.com/vrk-kpa/suomifi-ui-components/compare/v6.2.1...8a9ac55b684265eddd7ddd807253d611194f5a7d
- Introduce LogoIcon component
- Change internal structure and styling
- Add smallScreen prop
- Remove icon from neutral variant
- Improve API documentation concerning onItemSelectionsChange event.
- Fix bug where list didn't open from clicking field after user removed selection once.
- Fix example where `as` prop was used instead the `asProp`
- Fix logic  of `labelNewWindow` prop when used with `toNewWindow` prop.
**Breaking changes:**
Following components had their baseStyle changed a little by moving the styles to top level (root). Actual styling should not have been changed on purpose. These might cause changes in services using …
> [Release] 7.0.0-beta.0

- README.md
Small typo in README in the section where we guide how to use variants. Not affecting the use case, but good to fix anyway.
`seconday` --> `secondary`
Looking little more professional when having less typos.
Looking the README here on GitHub
- Fix README. Small typo in variant example.
> [Fix] Small typo in README about variant example.

- package.json
This PR raises the version number to 7.0.0-beta.1 in anticipation of the release.
* Fix class name disparity when using SSR
* Fix typo in documentation
* Update dependencies
* Improve behaviour with asynchronous content
* **Breaking change:** Add support for multiline content and remove ellipsis
> [Release] 7.0.0-beta.1

- .styleguidist/styleguidist.sections.js
- src/core/Form/Checkbox/Checkbox.baseStyles.tsx
- src/core/Form/Checkbox/Checkbox.md
- src/core/Form/Checkbox/CheckboxGroup.baseStyles.tsx
- src/core/Form/Checkbox/CheckboxGroup.test.tsx
- src/core/Form/Checkbox/CheckboxGroup.tsx
- src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
- src/core/Form/index.ts
- src/index.tsx
- Add CheckboxGroup component
- Update Checkbox label font size to be smaller
Add CheckboxGroup component for visually helping grouping checkboxes together. Checkbox font size was decreased so they work visually better when grouped; CheckboxGroup and Checkbox has all the font sizes as 16px.
Locally in styleguidist and CRA-TS test project.
- Add Checkboxgroup component.
- Update Checkbox label's font size to be smaller
> [Feature] CheckboxGroup component

- package.json
This PR increases the version number to 7.0.0-beta.2 in anticipation of the coming release.
* Fix button styling and clean up internal structure (#587)
* Add `whiteBase` as default background color (#595)
* Update props to extend span props (#589)
* Add Checkboxgroup component. (#593)
* Update Checkbox label's font size to be smaller  (#593)
* Add `whiteBase` as default background color (#595)
* Add background color for the input element (#595)
* Resolve babel-plugin-styled-components version to 2.0.7 (#598)
> [Release] Increase version number to 7.0.0-beta.2

- package.json
This PR changes the version number to 7.0.0 in anticipation of the official release.
- Add Checkboxgroup component. 
- Introduce LogoIcon component
- **Breaking change:** Add support for multiline content and remove ellipsis
- Update StaticChip props to extend span props
- Fix button styling and clean up internal structure
- Add `whiteBase` as default background color
- Change internal structure and styling
- Add `smallScreen` prop
- Remove icon from neutral variant
- Improve API documentation concerning `onItemSelectionsChange` event.
- Improve behaviour with asynchronous content
- Fix bug where list didn't open from clicking field after user removed selection once.
- Improve behaviour with asynchronous content
- Fix example where `as` prop was used instead the `asProp`
- Fix logic  of …
> [Release] Change version number to 7.0.0

- .github/CODEOWNERS
Add new team members as code owners. **Waiting first for new team members to be in correct group before merging.**
> [Feature] Add new team members as code owners

- package.json
This PR raises the version number to 8.0.0-beta.0 in anticipation of release
https://github.com/vrk-kpa/suomifi-ui-components/compare/v7.0.0...ed27d6e6882ffc1f098d3e651ab3c3a029dbc8ec
* Add optional prop `disabled`
* Use internal `<InputToggleButton>` component to display the caret icon.
- This adds a new behavior to MultiSelect: the popover can now be closed (in addition to opening) by pressing the caret icon
* Change cursor from default to pointer in popover item list
* Change cursor from default to pointer in popover item list
* Change cursor from default to pointer in popover item list
* Fix issue regarding controlled state nullification
* Add optional prop `onClearSelection()`
* Add optional prop `disabled`
* Fix CSS selector which targeted all `.fi-icon` elements inside the …
> [Release] 8.0.0-beta.0

- package.json
Updated to minimum version that is required to build the project and run the styleguidist.
Should have no effect on services using the library.
`engines` field have not been updated since start.
When using older than v14 of the **node** , building the project was no longer possible as the dependencies required newer version of the node to be installed.
Building the project locally.
_I think there is no need to mention in release notes as this should be internal change._
> [Fix] Update engines field in package.json

- src/core/Form/RadioButton/RadioButton.baseStyles.tsx
- src/core/Form/RadioButton/RadioButton.md
- src/core/Form/RadioButton/RadioButton.test.tsx
- src/core/Form/RadioButton/RadioButton.tsx
- src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx
- src/core/Form/RadioButton/RadioButtonGroup.test.tsx
- src/core/Form/RadioButton/RadioButtonGroup.tsx
- src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
- src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
- Adjust spacings for RadioButtonGroup
- Decrease font size of RadioButton
- Renamed RadioButtonGroup's `hintText` to be `groupHinText` to not confuse with the RadioButton's one and to be in same way as in CheckboxGroup.
- Use the Label and HintText components in RadioButtonGroup  instead of custom implementations
- Use the HintText components in RadioButton instead of custom implementations
- Add `optionalText` prop for RadioButtonGroup 
While doing CheckboxGroup, some differences came up that this PR will fix to be more consistent with each other. 
_And something new also came up while doing this PR that will need to be fixed to CheckboxGroup. Will do that in separate PR._
Locally in styleguidist so far.
- Decrease font size
- **Breaking change:** Rename `hintText` prop to …
> [Fix] RadioButton & RadioButtonGroup adjustments

- package.json
This PR raises the version number to 8.0.0-beta.1
**Changes after previous stable**
https://github.com/vrk-kpa/suomifi-ui-components/compare/v7.0.0...546f2a0d4dd3f7a08904b54388ee74dec784567d
**Changes after previous beta**
https://github.com/vrk-kpa/suomifi-ui-components/compare/v8.0.0-beta.0...546f2a0d4dd3f7a08904b54388ee74dec784567d
- Decrease font size of label from 18px to 16px.
- **Breaking change:** Rename `hintText` prop to `groupHintText`.
- Update spacings to match with the design.
- New `optionalText` prop added.
- **Breaking change:** `labelNewWindow` no longer required or allowed when `toNewWindow` is set to false
- Improve API documentation readability in Styleguidist
- Remove subsections from Styleguidist components menu and put all components under one heading
- Order …
> [Release] 8.0.0-beta.1

- package.json
This PR changes the version number to 8.0.0.
* Add optional prop `disabled`
* Use internal `<InputToggleButton>` component to display the caret icon.
- This adds a new behavior to MultiSelect: the popover can now be closed (in addition to opening) by pressing the caret icon
* Change cursor from default to pointer in popover item list
* Change cursor from default to pointer in popover item list
* Change cursor from default to pointer in popover item list
* Fix issue regarding controlled state nullification
* Add optional prop `onClearSelection()`
* Add optional prop `disabled`
* Fix CSS selector which targeted all `.fi-icon` elements inside the component and determined their color
* Remove white background color
* **Breaking change**: Fix CSS specificity issue which caused unpredictable …
> [Release] Increase version number to 8.0.0

- package.json
This PR raises the version number to 9.0.0-beta.0
- Introduce LoadingSpinner component
- Add tooltipComponent, contentClassName, wrapperProps and style props
- **Breaking Changes:** 
- LabelProps now extend HtmlSpanProps instead of HtmlDivProps
- Props are passed to inner content wrapper instead of the top most element, except for className and wrapperProps.
- Remove labelSpanProps
- ClassName is passed to top most element instead of inner content wrapper
* **Breaking change:** Rehaul accessibility features
* Remove `ariaLiveMode` prop
* Add `role="region"` for the main container
* Add `regionAriaLabel` prop
- Add `groupStatus` and `groupStatusText` props.
- Introduce LoadingSpinner component
* **Breaking change**: Rename main class `.fi-label-text` to `.fi-label`
*  **Breaking change**: …
> [Release] 9.0.0-beta.0

- package.json
Increase version number to 9.0.0-beta.1
* Add possibility to allow user to add their own custom item as the selected item
- This mode requires a new prop `allowItemAddition` to be `true`. A string prop `itemAdditionHelpText` is then also required
* Fix a bug with keyboard navigation
* Fix arrow borders visual glitch
Full changelog after previous beta: https://github.com/vrk-kpa/suomifi-ui-components/compare/v9.0.0-beta.0...9e19c111ddb5676ed23548374a682e1ed5423fd1
> [Release] 9.0.0-beta.1

- package.json
- yarn.lock
Updates `suomifi-icons`dependency. This adds new icon, `application-profile`, to selection.
- Add `application-profile` icon
> Update suomifi-icons dependency

- src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap
- src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
- src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
- src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
- src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap
- src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
- src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
- src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
- src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
- src/utils/common/common.ts
Fixes a circular dependency warning
Closes #
The warning is probably not very serious as everything has been working fine. But this fix makes the build output shorter by one line and it's nice to have less warnings. 
Running build, tests, styleguidist.
> [Fix] Circular dependency

- package.json
- src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap
- src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
- yarn.lock
Update suomifi-design-tokens to the lastest version 4.0.0 (contains one color change)
Keeping the tokens dependency up to date.
With styleguidist Firefox and Chrome
*  Update suomifi-design-tokens version to 4.0.0
> [Feature] Update suomifi-design-tokens version to 4.0.0

- src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md
- src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
- yarn.lock
Adds alternative function props for `ariaOptionsAvailableText` and `ariaOptionChipRemovedText`. Typescript typing requires one of the prop versions to be used.  
Closes  https://jira.dvv.fi/browse/SFIDS-517
Improves support different languages with their different order of words.
Syleguidist, CRA  Firefox, Chrome
- Add function props for template literals
> [Feature] Multiselect template literals

- package.json
This PR raises the version number to 9.0.0-beta.3 in anticipation of the coming release.
* **Breaking change:** InlineAlert now uses `fi-inline-alert` instead of `fi-alert--inline` (#644)
* **Breaking change:** Change label content type from `string` to `ReactNode` (#652)
* Fix InlineAlert styles bleeding out to children. (#644)
* **Breaking change:** Change label content type from `string` to `ReactNode` (#652)
* Add support for functions as means to provide text content for screen readers in MultiSelect (#649)
* **Breaking change:** Change label content type from `string` to `ReactNode` (#652)
* Add separate props for margin & padding to each side. The props accept suomifi-design-token spacing values (#650)
* Add 'displayName' property to all components (#643)
* Update `suomifi-icons`, …
> [Release] 9.0.0-beta.3

- package.json
This PR raises the version number to 9.0.0 in anticipation of a new stable release.
- Introduce Tooltip component
- Label component
- Add `tooltipComponent`, `contentClassName`, `wrapperProps` and `contentStyle` props
- **Breaking changes**: 
- LabelProps now extend HtmlSpanProps instead of HtmlDivProps
- Props are passed to inner content wrapper instead of the top most element, except for className and wrapperProps.
- Remove labelSpanProps
- ClassName is passed to top most element instead of inner content wrapper
* **Breaking change:** Rehaul accessibility features
* Remove `ariaLiveMode` prop
* Add `role="region"` for the main container
* Add `regionAriaLabel` prop
- Add `groupStatus` and `groupStatusText` props.
- Introduce LoadingSpinner component
* **Breaking changes**:
- Rename main …
> [Release] 9.0.0

- src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/core/Form/Label/Label.tsx
- src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
- src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR addresses a bug where the hidden variant of Label was not semantically a label.
The bug was reported by a service using the library. It's a usability and accessibility problem.
Tested in styleguidist on Chrome + Windows. 
* Fix hidden variant semantics
> [Bugfix] Hidden Label semantics

- package.json
This PR raises the version number to 9.1.0-beta.1 in anticipation of a new beta release.
- Fix hidden variant semantics
- Introduce WizardNavigation component
- Introduce ServiceNavigation component
- Add support for ref
Full changelog https://github.com/vrk-kpa/suomifi-ui-components/compare/v9.1.0-beta.0...release/9.1.0-beta.1
> [Release] 9.1.0-beta.1

- src/core/Form/Select/SingleSelect/SingleSelect.test.tsx
- src/core/Form/Select/SingleSelect/SingleSelect.tsx
This PR adds property `ariaOptionsAvailableTextFunction` to SingleSelect component.
Property `ariaOptionsAvailableTextFunction` is an alternative to the property `ariaOptionsAvailableText`. A function enables better customization of the text, and has already been implemented to the MultiSelect component.
CRA, Styleguidist, and component tests.
- Add property `ariaOptionsAvailableTextFunction` to SingleSelect component.
> [Feature] Property ariaOptionsAvailableTextFunction to SingleSelect component

- package.json
This PR raises the version number to 9.1.0-beta.3 for a new beta release.
- Add top and bottom padding to level 3 list 
- Adjust focus style for better visibility
- Fix color in focus style
- Fix focus issue with NVDA screenreader
- Introduce `<Pagination>` component
- Connect the component's label to its input via the for attribute to allow focus on label click
Full changelog [v9.1.0-beta.2...release/9.1.0-beta.3](https://github.com/vrk-kpa/suomifi-ui-components/compare/v9.1.0-beta.2...release/9.1.0-beta.3)
> [Release] 9.1.0-beta.3

- package.json
This PR changes the version number to 9.1.0 in anticipation of the official release.
- Introduce `<Pagination>` component
- Introduce `<SideNavigation>` component
- Introduce `<ServiceNavigation>` component
- Introduce `<WizardNavigation>` component
- Add `showToggleAllButton` prop with a default value of true
- Fix focus issue with NVDA screenreader
- Connect the component's label to input
- Add `ariaOptionsAvailableTextFunction` prop
- Connect the component's label to input
- Add `underline` prop with a default value of 'hover'
- Add support for ref
- Add `underline` prop with a default value of 'hover'
* Fix hidden variant semantics
* Fix passed props on hidden variant 
* Add optional `forceTooltipRerender` boolean prop. 
* The prop toggles on behaviour which forces a Tooltip component …
> change version number to 9.1.0

- .styleguidist/styleguidist.sections.js
- package.json
- src/core/Form/DateInput/DateInput.baseStyles.tsx
- src/core/Form/DateInput/DateInput.md
- src/core/Form/DateInput/DateInput.test.tsx
- src/core/Form/DateInput/DateInput.tsx
- src/core/Form/DateInput/DatePicker/DatePicker.baseStyles.tsx
- src/core/Form/DateInput/DatePicker/DatePicker.tsx
- src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.baseStyles.tsx
- src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.tsx
- src/core/Form/DateInput/DatePicker/MonthDay/MonthDay.baseStyles.tsx
- src/core/Form/DateInput/DatePicker/MonthDay/MonthDay.tsx
- src/core/Form/DateInput/DatePicker/MonthTable/MonthTable.baseStyles.tsx
- src/core/Form/DateInput/DatePicker/MonthTable/MonthTable.tsx
- src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
- src/core/Form/DateInput/datePickerTexts.ts
- src/core/Form/DateInput/dateUtils.ts
- src/core/Form/DateInput/index.ts
- src/core/Form/index.ts
- src/index.tsx
- yarn.lock
Adds new component DateInput that has optional DatePicker.
DateInput component with DatePicker option is needed in applications that use components library
Windows, NVDA: Firefox, Chrome, Edge
iOS, VoiceOver: Safari, Chrome
Android, TalkBack: Chrome (BrowserStack)
macOS, VoiceOver: Safari (BrowserStack), Safari
Applications: Styleguidist, CRA, Next.js
Known issue in some instances with iOS, VoiceOver: Dropdown has additional focus to list, as Dropdown component will be updated later on, this is deemed not a blocker.
- Introduce `DateInput` component
> [Feature] DateInput component

- package.json
This PR raises the version number to 10.0.0-beta.0 for a new beta release.
- **Breaking change:** Rename a couple of token categories
- focus ---> focuses
- radius ---> radiuses
- **Breaking change:** update `blackBase` color from hsl(0, 0%, 16%) to hsl(0, 0%, 13%)
- Refactor underlying implementation to use suomifi-design-tokens package for all tokens
- **Breaking change:** Content will now take up all available space
- **Breaking change:** Change close button size and appearance
- **Breaking change:** Remove redundant `null` from possible parameters in `onItemSelect()` prop
- Add support for loading state
- Add support for loading state
- Introduce `DateInput` component
Full changelog: https://github.com/vrk-kpa/suomifi-ui-components/compare/v9.1.0...release/10.0.0-beta.0
> [Release] 10.0.0-beta.0

- package.json
This PR increases version to 10.0.0-beta.1 in anticipation of a new beta release
* Add screen reader support for loading state
* Fix possible issue with NVDA and `ariaOptionsAvailableText`
* Add mobile device support via `smallScreen` prop
* **Breaking change**: Change `wrapperProps` prop typing to include data-attributes (e.g. data-testid)
* Add 1px visual border
- **Breaking change**: Completely rewrite the component without using ReachUI dependency
- Remove props `dropdownButtonProps` and `dropdownPopoverProps` (these were provided by Reach)
- Change ref type from `HtmlDivElement` to `HtmlButtonElement`
- Add boolean prop `portal` which defaults to true. Controls whether the popover is rendered in a React portal
- Add props `status`, `statustext` and `hintText`. These are familiar from …
> [Release] 10.0.0-beta.1

- package.json
This PR raises the version number to 10.0.0 in anticipation of a new stable release.
- **Breaking change**: Completely rewrite the component without using ReachUI dependency
- Remove props `dropdownButtonProps` and `dropdownPopoverProps` (these were provided by Reach)
- Change ref type from `HtmlDivElement` to `HtmlButtonElement`
- Add boolean prop `portal` which defaults to true. Controls whether the popover is rendered in a React portal
- Add props `status`, `statustext` and `hintText`. These are familiar from the library's other form components
- Add `onBlur()` prop
- Add boolean prop `fullWidth` which makes the component fill its parent horizontally
- Add prop `wrapperProps` which accepts HTML div attributes including data-attributes
- All other props (for example `data-testid`) are …
> [Release] 10.0.0

- package.json
PR raises version to 10.0.1 in anticipation of a new patch release
* Fix an issue with multiple "active" looking items appearing in the popover list. Keyboard and mouse navigation now use the same underlying logic and state
> [Release] 10.0.1

- package.json
PR raises version to 10.0.2 in anticipation of a new patch release
- Fix an issue where setState was sometimes called when the component was unmounted (https://github.com/vrk-kpa/suomifi-ui-components/issues/720)
> [Release] 10.0.2

- src/core/Pagination/PageInput/PageInput.tsx
PR improves Pagination PageInput component validation so that it flags input like "2sds" as error.
https://jira.dvv.fi/browse/SFIDS-812
Bug was reported by user. It can lead to a state where a page refresh is needed.
Styleguidist
Image of the bug
* Fix bug in page input verification. Input containing non-numeric characters, but starting with number caused NaN error.
> [Fix] Pagination page number input verification

- package.json
- src/core/Button/Button.md
PR fixes minor documentation typo and increases version number to 11.0.0 for new stable release.
This major release changes how icons are used in the suomifi-ui-components library. Icon-component is removed and icons are imported as individual components. This adds support for tree-shaking to minimize bundle sizes.
- **Breaking change:** All icon props now take a ReactElement as value instead of a string.
- Library's documentation (Styleguidist) updated to support versioning
- previous major release documentation available from Versions page (10.0.4)
- **Breaking change:** Icon component is **removed** and no longer available through suomifi-ui-components. Icons are imported individually either from `suomifi-icons` or through `suomifi-ui-components`
- Update suomifi-icons to 7.0.0
> [Release] 11.0.0

- src/core/ActionMenu/ActionMenu.baseStyles.tsx
- src/core/ActionMenu/ActionMenu.md
- src/core/ActionMenu/ActionMenu.test.tsx
- src/core/ActionMenu/ActionMenu.tsx
- src/core/ActionMenu/ActionMenuDivider/ActionMenuDivider.baseStyles.tsx
- src/core/ActionMenu/ActionMenuDivider/ActionMenuDivider.tsx
- src/core/ActionMenu/ActionMenuItem/ActionMenuItem.baseStyles.tsx
- src/core/ActionMenu/ActionMenuItem/ActionMenuItem.tsx
- src/core/ActionMenu/ActionMenuPopover/ActionMenuPopover.baseStyles.tsx
- src/core/ActionMenu/ActionMenuPopover/ActionMenuPopover.tsx
- src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap
- src/core/Button/Button.tsx
PR adds a new ActionMenu component
Closes https://jira.dvv.fi/browse/SFIDS-692
ActionMenu component is needed in applications that use components library
Styleguidist
Windows, NVDA, Edge, Chrome, Firefox
Mac, VoiceOver, Safari, Chrome, Firefox
iPhone, iPad (VoiceOver), Android (TalkBack)
* Add `ActionMenu` component
> [Feature] ActionMenu

- package.json
PR raises version to 12.0.0-beta.1 in anticipation of a new beta release
* Update Styleguidist menu structure and add general library usage documentation to Styleguidist
- Add character counter option and examples
- Add optional property `listProps` for passing data-attributes to unordered list element
- Add optional property `listItemProps` for passing data-attributes to list items
> [Release] 12.0.0-beta.1

- src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap
- src/core/Button/Button.baseStyles.tsx
- src/core/Button/__snapshots__/Button.test.tsx.snap
- src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
- src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap
- src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
- src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
The button icon didn't align correctly vertically. This PR fixes the issue.
This was reported by a developer and would cause a bunch of annoying extra work if it remains unfixed.
Tested by running locally in styleguidist on chrome.
Before:
After: 
- Fix icon vertical alignment
> [Fix] Button icon vertical align

- package.json
- src/core/Link/LinkListItem/LinkListItem.tsx
This PR cherry-picks a hotfix from master to develop. Original hotfix PR: #784
> [Hotfix from master] LinkListItem icon rendering

- package.json
This PR increases package version to 13.0.0-beta.0 in anticipation of a new beta release
* Introduce the TimeInput component
* Add `onDatePickerButtonBlur()` prop
- Fix input to show updated value when item array is changed externally
- **Breaking change:** changed implementation of margins and spacing from CSS-based styles to style-attribute
- **Breaking change:** changed implementation of margin  from CSS-based styles to style-attribute
- **Breaking change:** `marginBottomSpacing` prop is replaced by `mb`
- New props `margin`, `mx`, `my`, `mt`, `mr`, `mb`, `ml`
- **Breaking change:** Combine `ariaOpenText` and `ariaCloseText` props to `toggleButtonAriaLabel`
- `openAllText` and `closeAllText` are optional when `showToggleAllButton` is set to false
- Improve HTML structure
- **Breaking …
> [Release] 13.0.0-beta.0

- package.json
This PR raises the vesion number to 13.0.0-beta.1 in anticipation of the release.
- **Breaking change:** Update `suomifi-design-tokens` to 6.0.0 
- Contains some [color changes](https://github.com/vrk-kpa/suomifi-design-tokens/releases/tag/v6.0.0)
- Style prop is forwarded to the outermost wrapper in all components
- Documentation improvements
- **Breaking change:** Decrease padding of smallScreen variant 
- **Breaking change**: Change `buttonText` prop type from string to ReactNode 
- **Breaking change:** Remove** `wrapperProps` and forward `style` prop to the outer wrapper
- Props now extend `ButtonProps`
- **Breaking change:** update styles to match new designs 
- **Breaking change:** update styles to match new designs 
- **Breaking change:** `closeButtonProps` are now of type …
> [Release] v13.0.0-beta.1

- src/core/LoadingSpinner/LoadingSpinner.tsx
This PR cherry-picks a hotfix from master to develop. Original hotfix PR: #805
> [Hotfix from master] LoadingSpinner ref

- package.json
PR increases version to 14.0.0-beta.2 in anticipation of a new beta release
- **Breaking change:** change disabled variant hint text color to match the label color 
- Add `datePickerProps` prop
- Set icon to render only when component has children
- Fix an issue where visible selected value did not get updated when changing application language (DropdownItem visible text changes but value remains the same) 
- Prevent `onToggleButtonClick` and `onCloseButtonClick` props from leaking to DOM
- Fix `forwardedRef` behavior
- Remove redundant `never` typing from `LoadingProps`
- Remove redundant `never` typing from `LoadingProps`
- Remove redundant `never` typing from `AllowItemAdditionProps`
- Remove redundant `never` typing from `LoadingProps`
- Remove redundant `never` typing from …
> Increase version to 14.0.0-beta.2

- src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
- src/core/Popover/Popover.tsx
Popover positioning was not updated properly on the `MultiSelect` compoennt when it was used in a container with dynamic dimensions. For example when using the `MultiSelect` component in a modal, as the user selects items from the multiselect the modal would resize and the popover would get "detached" from the multiselect input.
This was fixed by introducing a React context for the `Popover` component which contains an `updatePopover`-function. The `updatePopover` function should be called in the context whenever the `Popover` should call the `react-popper` provided `update` function, which would handle calculating the position again. 
Closes #848 
This was done because using the `MultiSelect` component in a container which's dimensions may change dynamically was not possible due to the …
> [Fix] Fix popover positioning when selected items change in a multiselect component

- package.json
PR updates version to 15.0.0-beta.1 in anticipation of a new beta release
- Fix `onChange` behavior in controlled state
- Fix file item text styles
- Update `@types/react` to 18.3.3
> [Release] 15.0.0-beta.1

- package.json
PR increases version to 15.0.0-beta.2 in anticipation of a new beta release
- Fix multifile list styles
> [Release] 15.0.0-beta.2

- package.json
PR increases version to 15.0.0-beta.3 in anticipation of a new beta release
- **Breaking change**: Fix group legend margin CSS in `labelMode="hidden"`
- Fix various accessibility related issues
- Update documentation regarding aria-attributes and the usage of tabIndex
- Adjust documentation
> [Release] 15.0.0-beta.3

- package.json
PR updates version to 15.0.0 in anticipation of a new stable release
- **Breaking change:** Margin props are now implemented using `!important` CSS styles instead of style attributes
- **Breaking change:** Fix group legend margin CSS logic (#872)
- Add `groupStatus` and `groupStatusText` props (#878)
- **Breaking change:** Fix group legend margin CSS logic
- **Breaking change**: Remove redundant `fullWidth` prop
- Introduce `<FileInput>` component
- Introduce `<Details>` component
- Introduce `<SpacingProvider>` HOC for providing context or even site-specific spacing rules
- Allow custom date picker positioning via new `datePickerPosition` prop (#856)
- Fix accessibility issues related to Windows high contrast mode (#855)
- Fix accessibility issues related to Windows high contrast mode
- …
> [Release] 15.0.0

- package.json
- src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
- src/core/Form/Dropdown/Dropdown/Dropdown.test.tsx
- src/core/Form/Dropdown/Dropdown/Dropdown.tsx
- src/core/Form/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx
- src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
- src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
- src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
- src/core/Form/Select/SingleSelect/SingleSelect.md
- src/core/Form/Select/SingleSelect/SingleSelect.tsx
- src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
- src/reset/HtmlUl/HtmlUl.tsx
This PR implements the changes made in #883 into develop.
#883
> [Hotfix from master] 15.0.1

- .styleguidist/styleguidist.sections.js
- package-lock.json
- package.json
- src/core/Table/Table.baseStyles.tsx
- src/core/Table/Table.md
- src/core/Table/Table.test.tsx
- src/core/Table/Table.tsx
- src/core/Table/__snapshots__/Table.test.tsx.snap
- src/core/theme/utils/spacing.ts
- src/index.tsx
- src/reset/HtmlTable/HtmlTable.tsx
- src/reset/HtmlTable/HtmlTableBody.tsx
- src/reset/HtmlTable/HtmlTableCaption.tsx
- src/reset/HtmlTable/HtmlTableCell.tsx
- src/reset/HtmlTable/HtmlTableHeader.tsx
- src/reset/HtmlTable/HtmlTableHeaderCell.tsx
- src/reset/HtmlTable/HtmlTableRow.tsx
- src/reset/index.ts
PR introduces the `<Table>` component. It has been developed according to Figma designs and various conversations the team has had. The component in itself is fairly simple without any complicated logic. It only takes in data regarding columns and rows and presents it. Notable extra features include table sorting and row selection with checkboxes.
Any filtering, pagination or other such features must be implemented around the Table component.
- Introduce `<Table>` component
> [Feature] Table

- package.json
This PR raises the version number to 16.0.0-beta.1 in anticipation of the beta release.
- Add `enableSingleRowSelection` prop
- Fix cell height and alignment issues
- Improve commonJS compatibility
- Change accent icon color to be set using CSS
> [Release] 16.0.0-beta.1

- package-lock.json
- package.json
- src/core/Expander/ExpanderTitle/ExpanderTitle.tsx
- src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.tsx
- src/core/Form/DateInput/DatePicker/DatePicker.tsx
- src/core/Link/LinkListItem/LinkListItem.tsx
- src/core/Tooltip/Tooltip.tsx
- src/utils/common/common.ts
The library had some issues where, due to wrong syntax in some imports inside the library, the resulting types had some issues with erroneous references. This PR fixes those issues and also updates babel runtime and plugins to fix some security issues.
All the fixed things were reported by services using the library and needed to be fixed.
Tested by running locally on styleguidist, by using and building a test vite-react project. Also tested by the developer who encountered the type issues. These changes seemed to fix them.
- Fix errors in built types
- Update babel runtime and build plugins
> [Fix] Broken type exports

- package.json
This PR raises the version number to 16.0.1 in anticipation of the coming release
- Fix errors in built types
- Update babel runtime and build plugins
- Make the component's wrapping div focusable when it has horizontal scroll to allow keyboard scrolling on Safari
> [Release] v16.0.1

- .styleguidist/accessibility.md
- Updated Known issues
- Updated statements regarding WCAG 2.2 compatibility
- Added a few WCAG 2.2 related checks to the checklist.
> Update Accessibility docs
