vrk-kpa/suomifi-ui-components

src/components/Menu/Menu.tsx, src/core/Menu/Menu.tsx
- Refactor so that Menu component has the original className prop and MenuButton has other props but it's className is menuButtonClassName
=> Fix Menu component's button styles not working

.styleguidist/styleguidist.styles.js, src/components/utils/aria.ts, src/core/Breadcrumb/Breadcrumb.tsx, src/core/Button/Button.tsx, src/core/Dropdown/Dropdown.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/Toggle/Toggle.tsx, src/core/Heading/Heading.tsx, src/core/Link/Link.md, src/core/Link/Link.tsx, src/core/Link/LinkExternal.tsx, src/core/Menu/Menu.tsx, src/core/Panel/PanelExpansion.tsx, src/core/Panel/PanelExpansionGroup.tsx
To make more clear when using components when is semantic structure within app to be noted.
=> Add '<constains semantic elements>'-tags to component styleguide pages

src/core/Heading/Heading.md, src/core/Heading/Heading.test.tsx, src/core/Heading/Heading.tsx, src/core/Heading/__snapshots__/Heading.test.tsx.snap, src/core/Icon/Icon.tsx, src/core/Link/Link.tsx, src/core/Link/LinkExternal.tsx, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/theme/utils/defaultTheme.ts, src/reset/HtmlA/HtmlA.tsx, src/reset/HtmlButton/HtmlButton.tsx, src/reset/HtmlDiv/HtmlDiv.tsx, src/reset/HtmlH/HtmlH.tsx, src/reset/HtmlInput/HtmlInput.tsx, src/reset/HtmlLabel/HtmlLabel.tsx, src/reset/HtmlLi/HtmlLi.tsx, src/reset/HtmlNav/HtmlNav.tsx, src/reset/HtmlOl/HtmlOl.tsx, src/reset/HtmlP/HtmlP.tsx, src/reset/HtmlSpan/HtmlSpan.tsx, src/utils/typescript.ts
Styled-components has as-prop that replaces styled-template literal tags' element/component. Our components use internal components with styled that are not the ones to be replaced. Using defaultTheme-util (will be later refactor at another fix) as-prop is now internally changed to asProp and implementations with that when needed. Link-component supports both public API as and internal API asProp.
closes #157
=> Create internal asProp for defaultTheme-util

src/components/Link/Link.tsx
Added info for Link's Description that it is not focusable without the href.
Closes #151
=> Link's description updated; unfocusable without href

src/core/Breadcrumb/BreadcrumbLink.tsx, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
Changed the aria-current value of the last item in the breadcrumb from "page" to "location" according to the specs from http://design-patterns.tink.uk/aria-current/
Also updated the test snapshot to match the new value.
Closes #175
=> [Bugfix]Change breadcrumb link "Aria-current" value from "page" to "location"

src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown.tsx
Dropdown component had gray background when it should be white.
**Versions:** 0.2.4, 0.2.5. 0.2.6
**Operating system:** macOS Catalina 10.15
**Browsers:** Firefox, Safari
**Versions:** 0.2.4, 0.2.5. 0.2.6
**Operating system:** macOS Catalina 10.15
**Browsers:** Chrome, Opera
Closes #178 
To look consistent with all applicable browsers and with intended colors.
Manually tested after the change with 
**Operating system:** macOS Catalina 10.15
**Browsers:** Chrome, Firefox, Safari, Opera
And seemed to work with all these browsers now.
And ran the validations
`yarn validate`
=> [Bugfix] Added the missing background-color for the Dropdown's baseStyle

src/components/Panel/PanelExpansion.tsx, src/core/Panel/Panel.md
Removes the JSDoc of the open-prop from PanelExpansion. Therefore also got rid of the example of using the prop.
Closes #203 
> PanelExpansion should not have described open-prop because it is handled by onClick
- manually checked in the browser
=> [Bugfix] PanelExpansion: Removed the JSDoc of the open-prop & example

src/core/Button/Button.baseStyles.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/theme/colors.ts
- New background gradient created for Button.tertiary, previously it used just one color
- Hover background color changed for Button.tertiary
- Updated the snapshot-test accordingly
Button.tertiary colors were not matching the design's colors.
- Manually viewing with the browser
=> [Patch] Button.tertiary colors to match design

src/core/Panel/PanelExpansionGroup.baseStyles.tsx, src/core/theme/__snapshots__/tokens.test.tsx.snap
This PR improves the styles for PanelExpansionGroup open/close all button for IE and Edge. Button is now correctly aligned to the right and not hiding under the expansion panels.
Closes #191 
The fix has been tested using Chrome locally and with IE11 and Edge using BrowserStack. The fix has also been tested using the styleguidist build and by creating a package using verdaccio and importing it to a local create react app typescript project.
=> Expansion panel alignment in IE and Edge

src/components/Panel/PanelExpansion.tsx, src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap
PanelExpansion now uses hidden attribute in addition to aria-hidden. The hidden attribute is conditionally removed when the panel is expanded while aria-hidden is always present and only it's value is derived from expanded state. Hidden content is force rendered by changing the element key when panel is either collapsed or expanded. The hidden prop is handled internally and cannot be provided as prop externally, so there should be no need for any existence checks etc.
Closes #199 
PanelExpansion was using only aria-hidden for expansion content, but to be accessible and semantically correct, hidden attribute should be used instead. Aria-hidden was left in place as a fallback for browsers that do not implement accessibility features for hidden attribute correctly.
Changes were tested …
=> Panel expansion disabled attribute

src/components/Form/SearchInput.tsx, src/components/Form/TextInput.tsx, src/core/Form/SearchInput/SearchInput.md, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.tsx
Adjusted TextInput and SearchInput components to the following standard:
1. Placeholder is not allowed in TextInput, and the user gets an error in console if one is used.
2. Placeholder is allowed in SearchInput, but only it is forced to match labelText. User gets warning in console if different placeholder is used.
3. Label can be made hidden or visible in both TextInput and SearchInput
Had to make some bigger adjustments since SearchInput uses TextInput. Need to make some changes to the way these work. Did it as follows:
1. Made a new class of BaseTextInput which essentially is the old TextInput without the required error when using placeholder.
2. Exported another class by the name of TextInput, which extends BaseTextInput and adds the error message and a slightly different logic …
=> [Bugfix] Only allow placeholder for search input

src/components/Form/Toggle.tsx, src/components/Form/ToggleButton.tsx, src/components/Form/ToggleInput.tsx, src/components/index.ts, src/core/Form/Toggle/Toggle.md, src/core/Form/Toggle/Toggle.test.tsx, src/core/Form/Toggle/Toggle.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Toggle will now have button-component by default and with the `withInput` attribute you can get the input-component version.
`toggleInputProps` and `toggleInputComponent` attributes will only work for the input-version.
Different versions are in separate files: `ToggleInput` and `ToggleButton`
```
suomifi-ui-components/src/components/Form
├── Toggle.tsx
├── ToggleButton.tsx
└── ToggleInput.tsx
```
This PR closes #136 and is related to the #154 changes (toggle functionality fixes incoming in later PR).
- manually in the browser
=> [Feature] Differentiating input and button versions of Toggle

src/components/Form/ToggleInput.tsx, src/core/Form/Toggle/Toggle.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Fixes the basic functionality issues that Toggle component did have; including structure changes for Toggle's input-version.
This is second PR of the "series" and should be merged after the PR #224 is merged.
Related issue #154 
Toggle is now usable and it will no longer trigger the state change twice.
- manually testing in the browser (Chrome)
=> [Bugfix] Toggle functionality

src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/utils/css.ts, src/core/Button/Button.baseStyles.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap
When hovering mouse over disabled button, mouse cursor will now change to give better feedback to the user.
Related #228 
This PR will add the disabled cursor only for the Button-component. Other components will be changed in later PRs.
To give better feedback for the user when the component is in disabled state.
- yarn test
- yarn validate
- manually testing with browser
=> [Feature] Mouse cursor change for disabled Button

package.json, src/core/theme/colors.ts, src/core/theme/index.ts, src/core/theme/spacing.ts, src/core/theme/typography.ts, src/core/theme/utils/colors.ts, src/core/theme/utils/spacing.ts, src/core/theme/utils/typography/fontsize.ts, src/core/theme/utils/typography/typographyutil.ts, yarn.lock
Update to suomifi-design-tokens to 0.3.0. This update includes only fixes for typos in typings, especially interface names.
Introduces a breaking change as some of the interfaces from suomifi-design-tokens are exported indirectly. Names of these interfaces have changed. For further details see https://github.com/vrk-kpa/suomifi-design-tokens/releases/tag/0.3.0 
Tested using yarn build and yarn test and locally using Verdaccio and create-react-app TypeScript project.
=> [BreakingChange] Update suomifi-design-tokens to 0.3.0

src/components/Form/ToggleInput.tsx, src/core/Form/Toggle/Toggle.tsx
Toggle's `defaultChecked` prop was not showing visible change in the Toggle component. 
Closes #154 
`defaultChecked` prop only added the `checked` attribute for the input (previously there was only input-version available of the Toggle).
- manually testing in the browser
=> [Bugfix] Fix Toggle's 'defaultChecked' property

package.json, src/components/Svg/Svg.tsx, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Icon/Icon.tsx, src/core/Icon/__snapshots__/Icon.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/Panel/__snapshots__/PanelExpansion.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, yarn.lock
This PR update suomifi-icons to version 0.0.10 and introduces support for Icon component custom props. The custom props are now passed forward to underlying svg.
In addition, includes a fix to restore support for custom icon colors.
Closes #156 
Relates to #250 
This update adds support for strict CSP when using Icons and setting the colors.
Tested by creating a new local package using Verdaccio and with create react app typescript application with strict CSP.
=> [Feature] Icon component custom props

.styleguidist/typography.md, package.json, src/core/Heading/Heading.md, src/core/Heading/Heading.test.tsx, src/core/Heading/Heading.tsx, src/core/Heading/__snapshots__/Heading.test.tsx.snap, src/reset/HtmlH/HtmlH.tsx, yarn.lock
Update design tokens to version 0.4.0, which removes h6 from there. Remove any instances of h6 from the reset, core, tests and examples.
The heading level 6 is no longer part of the design.
`yarn test ` and by running and manually testing locally
=> [BreakingChange]Remove heading 6 variant

src/core/Colors/Colors.baseStyles.tsx, src/core/Colors/Colors.test.tsx, src/core/Colors/Colors.tsx, src/core/Colors/__snapshots__/Colors.test.tsx.snap
- Using `figure` and `svg` to show the color token
- Able to use keyboard to switch between color tokens with `Tab`-key
- Able to use keyboard to copy the key of currently selected color token with `Enter`-key
- Added snapshot test to see possible structure changes in the future
Closes #173 
Change increases accessibility of the colors by changing the semantics and adding support for keyboard actions.
- manually in the browser (macOS 10.15.1:  Firefox, Chrome, Safari, Opera)
=> [Fix] Color token presentation accessibility

package.json, src/core/Icon/Icon.md, yarn.lock
Release 0.4.1
- Updated to use `suomifi-icons`  0.0.12
- Showing the new docType icons in the styleguidist
=> Release 0.4.1

src/core/Form/Toggle/Toggle.baseStyles.tsx, src/core/Form/Toggle/Toggle.md, src/core/Form/Toggle/Toggle.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Added styling to match the implementation to the updated designs at https://app.goabstract.com/share/92d4527a-036e-4f0f-89b2-f8d841a6ef9c
This was done mostly in the toggle basestyles, but the label color is changed by a conditional color prop in the text component inside the toggle component.
There was no clear visual cue for when a toggle component is disabled. Now the toggle component has a visually distinctive style for all combinations of checked/disabled.
By testing manually in local environment and yarn test.
=> [Feature]Add styles for toggle component disabled variants

.styleguidist/styleguidist.styles.js, src/core/Button/Button.baseStyles.tsx, src/core/Button/Button.md, src/core/Button/Button.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap
Button variant 'negative' changed to 'inverted' to match design. 
This is a breaking change, so users should use 'inverted' instead of previous 'negative' after this change goes live.
**Before**: `<Button.negative>Button.negative</Button.negative>`
**Now**: ` <Button.inverted>Button.inverted</Button.inverted>`
Naming of the variant changed to reflect the design to prevent any possibility of miscommunication or confusion.
- Run locally in the browser
=> [BreakingChange] Button variant 'negative' changed to 'inverted'

src/core/Form/Toggle/Toggle.baseStyles.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Gave the toggle input a size that matches the icon(s) used. This allows for the component to be found by mobile screen readers. Some issues regarding focus remain, but they will be addressed in another ticket.
Closes #268 
Tested manually on a pc as well as a mobile phone (android) and snapshot tests.
=> [Bugfix] Make toggle input match icon size

src/components/Form/ToggleInput.tsx, src/core/Form/Toggle/Toggle.baseStyles.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
- Fixes the focus outline of Toggle for both, the input- and button-version
- Fixes the disappearing focus issue when toggling the state of input-version
- Updated snapshot test accordingly
Here are some additional info to support the changes made.
> If present on a checkbox type, it indicates that the checkbox is checked by default (when the page loads). It does not indicate whether this checkbox is currently checked: if the checkbox’s state is changed, this content attribute does not reflect the change.
Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefchecked
Therefore the `key={String(toggleState)}` was removed from the ToggleInput.
Using `Space` or `Enter` will not read the state on **Safari** when toggling the state of the ToggleButton. _(On Chrome, …
=> [Bugfix]Toggle focus

src/core/Breadcrumb/Breadcrumb.baseStyles.ts, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
The breadcrumb component had no height and thus didn't position correctly (as a block-level element). Added height attribute to the nav element of the component to make it behave like a block-level element.
The issue was risen by one of the project teams using the ui-library. No issue ticket on github though. 
Now breadcrumb behaves like a block-level element. If in the future we want to support treating it as an inline element that will require some additional tweaking. Not many use cases for that though.
Yarn test and running locally in a CRA test project.
=> [Bugfix] Fix breadcrumb alignment

package.json, yarn.lock
Updated to use `suomifi-icons` version **0.0.14**
- run locally
- `yarn build`
=> [Feature] Update to use suomifi-icons version 0.0.14

src/components/Button/Button.tsx
- Previously Button's Assertive component's text was based on the state
- Now it is changed to be based on the `disabled`-prop instead
- Fix the wrong state of Assertive component's text at start
Idea of this issue (#206) was originally to prevent unneeded render, but with the changes suggested and others solutions tried there was no benefit gained.
Because using the `this.setState` it will cause render, therefore using the `firstState` does not really help, as when toggling it to false it will render and the result is still same. 
> And here comes the caveat in a React application; we need to ensure that the live region is already rendered when we send our first message and that it stays rendered until we no longer require it.
Source: [ARIA live regions in …
=> [Bugfix] Button's Assertive component

src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
- Allow the input-field to take all width it can on the `TextInput`
- Fixes also the `SearchInput` as it uses `TextInput` under the hood
- Updated also the snapshots
- locally on the browser
- on CRA TS-project
=> [Bugfix] Allow the input-field to take all width it can on the TextInput

src/components/LanguageMenu/LanguageMenu.tsx, src/core/LanguageMenu/LanguageMenu.baseStyles.tsx, src/core/LanguageMenu/LanguageMenu.tsx
Adjust language menu-button size to match designs (height 40px) and change menu icon rotation when menu is open.
To allow menu to be used with buttons in designs where height is based on button defaults, the language menu height needed to be changed. Also, in order to better communicate the functionality of the menu button when the menu list is visible, the icon should be rotated 180 degrees from the original.
Tested using styleguidist, CRA typescript project and design system site using verdaccio.
=> [Feature] Language menu improvements

src/components/Form/TextInput.tsx, src/core/Form/SearchInput/SearchInput.test.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
- Adds new prop `statusText` for the TextInput
- it is shown under the text field
- will not reserve space when the prop is given; space is taken only when the prop actually has some value ( !== undefined)
- TextInput text color won't anymore change based on variant as per design
- TextInput will now have the `status`-prop exposed publicly (previously `variant`)
- status = 'default' | 'error' | 'success'
- Added example to styleguidist how to use new `statusText` in conjunction with `status` prop
- The possibility to use the static ones (TextInput.success / TextInput.error) were removed
Changes made so that it will match the design and able to show the statusText for giving more context if needed.
- Locally on the browser
=> [Feature] TextInput state text & colors

package.json, src/components/Dropdown/Dropdown.tsx, src/components/LanguageMenu/LanguageMenu.tsx, src/components/index.ts, src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown.test.tsx, src/core/Dropdown/Dropdown.tsx, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/LanguageMenu/LanguageMenu.baseStyles.tsx, src/core/LanguageMenu/LanguageMenu.md, src/core/LanguageMenu/LanguageMenu.test.tsx, src/core/LanguageMenu/LanguageMenu.tsx, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/utils/test/axe.ts, types/index.d.ts, yarn.lock
This pull request introduces a fix for language menu positioning and enables variable menu name length. In addition, issues with keyboard navigation are now fixed for both, language menu and dropdown.
Dropdown component keyboard navigation issues are fixed with this PR as well.
The language menu component did not allow following designs and using longer language names in the button (e.g. Suomi (FI)). The underlying component was switched to lower level Reach-UI wrapper to allow using custom function for positioning. This revealed an issue with the list menu items used for dropdown as well. This issue was also fixed.
Test were updated to use snapshots. Aria attribute validity checks had to be disabled due to use of Portal with useLayoutEffect hook.
Manual testing was done using …
=> [BugFix] Language menu positioning

.styleguidist/spacing.md, .styleguidist/styleguidist.sections.js, package.json, src/core/Block/Block.md, src/core/Block/Block.test.tsx, src/core/Block/Block.tsx, src/core/Block/__snapshots__/Block.test.tsx.snap, src/core/Button/Button.baseStyles.tsx, src/core/Colors/Colors.baseStyles.tsx, src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Expander/Expander.baseStyles.tsx, src/core/Expander/ExpanderGroup.baseStyles.tsx, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/Toggle/Toggle.baseStyles.tsx, src/core/LanguageMenu/LanguageMenu.baseStyles.tsx, src/core/Link/Link.baseStyles.ts, src/core/Paragraph/Paragraph.tsx, src/core/Text/Text.md, src/core/Text/Text.test.tsx, src/core/Text/__snapshots__/Text.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, src/core/theme/reset/index.ts, src/core/theme/spacing.ts, src/core/theme/utils/spacing.ts, yarn.lock
This PR introduces new 5px based spacing tokens and inset spacing tokens and updates the components to use those internally.
The components remain mostly as-is. The exported theme will change and some existing exported spacing values will change.
To match current designs, spacing system needed to be changed to be 5px based, but also support for smaller 2px based system for component internal spacing was needed.
Tested with suomifi-design-system and create-react-app using verdaccio.
=> [BreakingChange] Update to 5px based spacing and inset spacing.

src/core/Link/Link.tsx, src/index.tsx
Fixes the Link's styleguidist page where LinkExternal was too greed to present itself.
Closes #137
To prevent user from getting confused when reading Link-component's manual
Locally ran the styleguidist, `yarn start`
=> [Fix] Link's styleguidist page

.styleguidist/webpack.config.js, README.md, package.json, tsconfig.json, types/index.d.ts, yarn.lock
This PR enables libCheck for TS-build. In addition it replaces Styleguidist webpack build awesome-typescript-loader with ts-loader. Also some related type issues are now fixed.
Styleguidist build related typings are also added as dev dependencies. Some typings that are required with `skipLibCheck: false` configuration are added as peer dependencies.
Based on feedback from test projects, but actual open issues.
To allow strict type checking in projects using the ui-components library, also typings for dependencies have to be valid and available.
Tested with Suomi.fi design system site, Create React App TS project and React SSR project template.
=> [BugFix] skipLibCheck related type issues

.styleguidist/styleguidist.sections.js, src/components/Link/LinkSkip.tsx, src/core/Link/Link.baseStyles.ts, src/core/Link/Link.md, src/core/Link/Link.tsx, src/core/Link/LinkSkip.tsx, src/index.tsx
Adds Skip-variant for Link-component
Currently the example for this is kind of component is hard to show. I added some context before the example. User of library can see how to use the component and put it to right context when using it.
Closes #170 
Able to provide skip link for users using keyboard navigation.
Firefox by default is not behaving nicely with the links when trying to use tab
- https://support.mozilla.org/en-US/questions/846320
- https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox/11713537#11713537
- Locally on DS-site to replace the **BypassLink.tsx**
- Locally on create-react-app skeleton
=> [Feature] Skip variant added for Link

src/components/Form/Toggle.tsx, src/components/Form/ToggleButton.tsx, src/components/Form/ToggleInput.tsx, src/core/Form/Toggle/Toggle.md, src/core/Form/Toggle/Toggle.test.tsx, src/core/Form/Toggle/Toggle.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
This PR replaces UNSAFE_componentWillReceiveProps lifecycle methods with getDerivedStateFromProps for Toggle component. Functionality or API of the component does not change.
UNSAFE_componentWillReceiveProps has been deprecated and should be replaced with other approaches. For Toggle component it should be relatively straight forward since rendering is always based on state. We are only interested on changes in checked prop when it is defined and differs from state (provided by parent component thus making the state controlled from outside). By using getDerivedStateFromProps we can achieve similar approach as was previously used with UNSAFE_componentWillReceiveProps.
Tested with Suomifi-design-system site, CRA TS project using controlled and uncontrolled approaches with checked.
=> Replace UNSAFE_componentWillReceiveProps with getDerivedStateFromProps

src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, src/core/theme/colors.ts, src/core/theme/radius.ts, src/core/theme/utils/focus.ts, src/core/theme/utils/outline.ts
Update for current focus styles so that they match the new style guide focus styles.
Current focus styles were following the design system specification which was never taken into use outside design system implementation. This was blocking ui-components usage in projects. Focus styles were redesigned to better match default styles that are in use in may services and applications.
Tested using styleguidist and Create React App TypeScript version with long contents for components.
=> [Fix] Focus style align with style guide

src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, src/core/theme/colors.ts, src/core/theme/utils/focus.ts, src/core/theme/utils/outline.ts
This PR implements a focus variant that only uses box shadow instead of a pseudo element. This can be used for inline elements to allow row wrapping focus styles as well as for pseudo elements such as the box in checkbox. This PR also implements the new focus style for checkbox.
The previous focus styles didn't work correctly for inline elements and pseudo elements.
Tested by running locally and manually testing as well as with automated tests.
=> [Feature] Add non-pseudo focus style

src/core/Breadcrumb/Breadcrumb.baseStyles.ts, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
The breadcrumb implementation in the library didn't match the current design in the styleguide. This PR contains style changes that match the implementation with the design.
To be a viable option for projects, the library needs to offer up-to-date components that match the styleguide.
Running locally and automated tests
Before:
After:
=> [Bugfix] Align breadcrumb styles with styleguide

src/core/Expander/Expander.baseStyles.tsx, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap
This PR sets the expander component styles to match the latest design and adds a word break rule for the expander content to prevent it from stretching the component.
Components need to be up-to-date with designs in order to be useful.
Tested manually in local environment
=> [Bugfix] Align expander styles with the design

src/core/Button/Button.baseStyles.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, src/core/theme/colors.ts, src/core/theme/reset/index.ts
Button styles now match the style guide. Adjustments to paddings, colors and font-size. No changes to component APIs. Includes improvements to gradient color names.
Some components had not been updated when style guide updates were introduced. These components now have to be aligned with style guide.
Since APIs were not changed, testing with styleguidist should be sufficient. No issues found during testing locally with styleguidist or build.
=> [Feature] Align button styles with style guide

src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/theme/colors.ts, src/core/theme/reset/index.ts
Align dropdown component colors and spacing with style guide. Add missing shadow.
Style guide has been updated without updating the ui-components implementation. Projects mostly follow the style guide, which prevents taking the library in use in the projects. This needs to be addressed by aligning the ui-components styles with the style guide.
Tested with styleguidist and create react app project using long texts for contents.
=> [Feature] Align dropdown styles with style guide

src/components/Form/TextInput.tsx, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR aligns the TextInput and SearchInput styles to the design. Some larger rebuilding still remains in the searchinput, but that's outside of the scope of this PR.
While adjusting styles, a couple of related matters got sorted. The statustext element is now conditionally rendered depending on if it has content or not. Also, the button in the styleguidist example was changed to suomifi button.
Textinput and searchinput had styles that differed from the latest designs. 
Running locally and manually testing.
=> [Bugfix] Align textinput and searchinput styles with design

src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/theme/colors.ts
This PR adds inset box shadows to textinput and searchinput as well as fixes an issue with the placement of the searchinput icon.
Since the shadow being used in dropdown is exactly the same, it was renamed to inputBoxShadow and implemented in the textinput and searchinput as well as in dropdown.
Implementations need to match styleguide in order to be usable in projects.
Manual testing plus automated tests.
=> [Feature] Update textinput styles to include inner shadow

README.md
- Added more detailed information about the required React-version
- Minimum working version of React is 16.3 but >= 16.8 is recommended.
- Added missing links for the mentioned packages
Updated documentation so that the library user has info for easier introduction to library usage.
=> [Fix]README update

package.json, src/core/Form/Toggle/Toggle.baseStyles.tsx, src/core/Form/Toggle/Toggle.md, src/core/Form/Toggle/Toggle.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap, yarn.lock
This PR aligns Toggle component styles with style guide. Focus styles have now rounded corners and only focus on toggle button / input instead of label also. Positioning of the toggle knob has been slightly adjusted. A stronger shadow is also present.
Due to the changes, the component width changes slightly.
Tested with Create react app Typescript project and styleguidist build.
=> [Feature] Align toggle styles with style guide

src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, src/core/theme/utils/outline.ts
Fix after-pseudo based focus styles to ignore all pointer events. A recent update to chrome causes input elements with this style to crash the page with "Aw, Snap!" message.
Apparently there is a new feature or a bug in the latest chrome / chromium browser which causes the browser to crash the page when encountering bad focus styles.
Tested with deploy preview styleguidist build.
Remove pointer events from after pseudo focus style element to fix browser crash.
=> Remove mouse-events from focus pseudo element

src/components/Expander/Expander.tsx, src/components/Expander/ExpanderGroup.tsx, src/core/Expander/Expander.md, src/core/Expander/Expander.test.tsx, src/core/Expander/Expander.tsx, src/core/Expander/ExpanderGroup.test.tsx, src/core/Expander/ExpanderGroup.tsx, src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap
Expander components props `open`, `defaultOpen` and `onClick` was not working when Expander was inside ExpanderGroup.
When talking about **controlled** state it means that the Expander is given a `open` prop. User is then required to handle the open state of the Expander self.
- `open`, `defaultOpen` and `onClick` should now work as intended and documented.
- Added an example of the controlled state for the Expander. It can be seen on the Expander's styleguidist page.
- Opening state of the individual Expander is stored inside itself, not by parent.
- Parent will keep own state to handle logic to show icon (*caret*) and text (*Open/Close all*)
- Added tests to verify the use of `open`, `defaultOpen` and `onClick`props when inside ExpanderGroup and when being just standalone Expander.
Some …
=> [Fix] Expander's defaultOpen, open and onClick properties not working when inside ExpanderGroup

src/components/Expander/Expander.tsx, src/core/Expander/ExpanderGroup.baseStyles.tsx, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap
- Fixed the Expander's corner rounding when inside ExpanderGroup
- Added separator between Expanders when inside ExpanderGroup
Showing the rounded corners only on top and bottom like in the [Material-UI](https://material-ui.com/components/expansion-panels/)
- This is not currently yet in the designs but was discussed for this change to be good to go
- Previously the rounding in the designs were all over the place and it was not possible to do it with just the CSS. It would have required also code changes to get it to match the design 100% and not really worth the effort as Material-UI way is simplistic and good looking.
To better match with the design and component to look good.
- Locally in the Chrome
Explanation to the screenshot (with the changes of this PR)
- Rounded corners …
=> [Fix] Grouped expanders corners rounded and separator between

src/components/Form/Checkbox.tsx
Checkbox controlled checked status wasn't working correctly, which resulted in conflicted internal state as well as screen readers announcing wrong states. This PR fixes the problem.
Components need to work reliably and be accessible. Checkbox was neither without the fix.
Running locally and testing changing the state with different methods both in controlled and regular mode.
Fixed a bug in checkbox internal state handling.
=> [Bugfix] Fix incorrect internal state handling in checkbox

src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Link/Link.baseStyles.ts, src/core/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap
Adjust Link component focus styles to use box shadow to allow multiline links and not show underline while focused. Update related snapshots.
Affects all Link variants including skip link. Also snapshot for Language Menu was updated, but none of the changed styles have an actual effect on the visible styles.
Change was needed to support links that have line breaks in between or don't fit into one line. Using box shadow instead of after pseudo based focus style allows inline elements to span across multiple lines without breaking the focus style. Style was also adjusted to not show underline when navigating with keyboard.
Tested using Styleguidist build and Create React App TypeScript project. Tested with Brave, Chrome, Firefox and Safari browsers.
Add support for multiline link focus …
=> [Feature] Adjust link focus styles

.styleguidist/modules.md, .styleguidist/primitive.md, src/components/README.md
Remove mentions of bare accessible components as it is not possible.
Related #303 where the cleanup was previously done but these were left behind.
To keep documentation updated
Removed mentions of bare accessible components as it is not possible to use library that way.
=> [Fix] Remove mentions of bare accessible components as it is not possible

src/components/Form/Checkbox.tsx, src/components/Form/ToggleInput.tsx
In cases where a confirm dialog or similar prompt interrupts the state change of checkbox and toggle input, instead of announcing the state change, screenreaders might read the wrong (previous) state upon focus returning to the input element.
This is a matter of how fast the changed state takes effect and might not occur on all machines and screenreaders. The solution in this PR is to use the event data of the onChange event instead of the old state to set the new state. This seems to be fast enough for the change to take effect before the focus returns to the input element.
Components need to be accessible in all cases. Having wrong states announced in input elements is not tolerable.
Tested by running locally and using components with NVDA and android with TalkBack on.
Fixed an …
=> [Bugfix] Set checkbox and toggle input variant to use event data for state change

src/core/LanguageMenu/LanguageMenu.baseStyles.tsx, src/core/LanguageMenu/LanguageMenu.md, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
The designs for the language menu were updated lately, and the component needs to be aligned with the new designs to be usable.
This PR contains changes to align the implementation with the latest designs. Changes in short:
- Size and spacing of the menu button changed
- Borders for menu button only visible on hover and when menu is open
- Popover spacing changed
- Popover border 'notch' now uses sub-pixel values to make it look better
- Popover selected and hover styles changed to show the left side marker both for the selected option and when hovering on an option.
Implementation needs to match the design to be usable in projects.
Running locally and testing with multiple browsers as well as on mobile (android with chrome).
- Language menu styles adjusted to match latest designs
=> [Feature] Align languagemenu styles with design

src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Changed the CheckBox hintText to use different color token: `depthBase` --> `depthDark1`
Using the color that was in the design. The wrong color was noticed as it was not accessible, because of it's low contrast.
Ran in local styleguidist.
**Fix**
- Checkbox `hintText` color changed
=> [Fix] CheckBox hintText to use different color token

src/core/LanguageMenu/LanguageMenu.baseStyles.tsx
Fixed a bug where language menu menuitem had wrong margin.
Tested by running locally.
- Fix spacing of language menu items
=> [Bugfix] Replace wrong token in languagemenu styles

src/core/Button/Button.baseStyles.tsx, src/core/Button/Button.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/theme/colors.ts
- Fixes the invert text shadow to have opacity of 50%
- Disabled Button text-shadow to have opacity of 50%
- Disabled Button icon is now showing correct cursor, `not-allowed`
- Disabled inverted button opacity changed from 50% to 41% to match with the design
- Button icon color is now using the `currentColor` so that it will use same color as the text
Wanted to match the Button styles with the design.
Locally ran in Styleguidist on Brave.
**Fix**
- Button text-shadow and icon color changes.
=> [Fix] Button style fixes

src/components/Form/SearchInput.tsx, src/components/Form/TextInput.tsx, src/core/Form/SearchInput/SearchInput.md, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
TextInput had a somewhat strange placeholder logic since inaccessible use of placeholders wanted to be kept to the minimum. This PR introduces a visualPlaceholder prop that gets passed to the component as placeholder.
These changes also slightly affected SearchInput, so the necessary changes were made to accommodate the changes.
The examples were also adjusted to show the new prop and logic.
https://github.com/vrk-kpa/suomifi-ui-components/issues/259
Closes #259
Placeholders are in use in many of the designs for Suomi.fi. To aid the implementation of the ui-components, a concession was made to implement it. However, the API description should guide the developers to the right track in terms of placeholders.
Yarn test and running locally
Implemented placeholder text for TextInput
=> [Feature] Add visual placeholder for TextInput

src/core/Breadcrumb/BreadcrumbLink.tsx, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Icon/Icon.md, src/core/Icon/Icon.tsx, src/core/Icon/__snapshots__/Icon.test.tsx.snap, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap
**Changes**
- Icon is now using `currentColor` by default
- BreadCrumbLink was tellin wrong and unnecessary color token on the code side as it was overrided by the css
- SearchInput has now fill color set explicitly as it no longer can use the default color
- Added example how `currentColor` affects the icon
- Icon now have baseClassName: `fi-icon`
- Snapshots updated
Related issue is no longer totally valid with the colors mentioned there.
Closes #229 
Icon usage is easier to have same color as the text without the need of complex logic to handle all different cases.
It is now possible to use the `fi-icon` also to override the colouring if needed.
- Locally with the styleguidist
- Locally with CRA JS-project
🚨**Breaking change**
- Icon is now using `currentColor` by default
=> [Fix] Icons to use currentColor

src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/Checkbox.test.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Checkbox status text element styles were off. The top margin was applied only with the error status. It now applies to the statustext element regardless of the actual status.
Also found a naming error in the tests while doing this and fixed it since it was a minor thing and didn't affect anything else. 
We want the library to be as bug-free as possible. 
Running locally and automated tests.
Fixed a bug in checkbox status text spacing
=> [Bugfix] Checkbox statustext margins

src/components/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown.md, src/core/Dropdown/Dropdown.test.tsx, src/core/Dropdown/Dropdown.tsx, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, types/index.d.ts
This PR adds mandatory label and related options for dropdown. In addition, name prop is renamed to visiblePlaceholder and is now ignored by screen readers.
The dropdown component was not accessible due to lack of label. Label is now added as mandatory prop. Label can be hidden, when it's only available for screen readers. When label is hidden, a visualPlaceholder or other means should be used to communicate the purpose of the dropdown for non screen reader users.
Name prop is now renamed as visualPlaceholder which is intended to be shown as additional visual hint when there is no selection for the dropdown.
Tested with Create React App TS project and Styleguidist using both mouse and keyboard navigation and VoiceOver for macOS. Tested using all supported browsers on Mac. Still needs …
=> [Feature] Dropdown label and placeholder

src/core/Form/Toggle/Toggle.baseStyles.tsx, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap
Toggle had a bug where the first instance of Toggle following some other element had incorrect focus styles. This was due to an erroneous CSS selector, which this PR fixes.
Component default styles need to be uniform and correct in all situations.
Running locally (only styleguidist).
Fixed a bug in Toggle focus style logic
=> [Bugfix] Toggle focus styles not applied to first instance

package.json, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, yarn.lock
Locking the Reach UI versions with resolutions added to `package.json`.
Want to prevent breaking changes from the Reach UI as they are not currently using semantic versioning in their packages outside or inside.
Tested locally and could not reproduce the problem (The error can be see when using e.g 0.10.0 version).
**Fixes**
- Reach UI versions locked with **resolutions** in `package.json`
=> [Feature] Locking Reach UI versions with resolutions

src/components/Button/Button.tsx, src/core/Button/Button.test.tsx
Disable generated button -element properly, if instantiating Button with disabled={true}.
Closes #
Current implementation doesn't actually disable button, it only makes the button look like disabled.
=> [Fix] Disable generated button with disabled-attribute

src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Checkbox's hintText had problem with the style for font. Snapshot test updated accordingly.
It was not having any visual glitch in the styles, but still an error in the styles that might later come as a problem or just needless to have error that was fixable.
Tested locally in the styleguidist.
Fix
- Checkbox's hintText style for font fixed.
=> [Fix] Checkbox's hintText style for font

src/components/Form/Checkbox.tsx, src/core/Form/Checkbox/Checkbox.test.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- Adds `name` and `value` props for Checkbox.
- Checkbox is now usable when using in form.
- Small refactoring to tests.
- More tests added.
Checkbox was not working correctly when used in forms as the value and name was not available for form.
- Locally run on CRA-TS project
- Locally run on CRA-JS project with form
Feature
- Adds `name` and `value` props for Checkbox.
=> [Feature] name and value props for Checkbox

src/components/Form/TextInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
- `hintText` prop for the TextInput
- Able to give `type` to TextInput: ```'text' | 'email' | 'number' | 'password' | 'tel' | 'url'```
- More tests added.
These changes were made because those were wanted by the designs and users of the library. 
Now user is able to give some different **type** than the previous `text` if it is needed. Not every type is supported as it makes no sense to give e.g _checkbox_ or _button_ as types because we have separate component for those.
Tests were added to increase test coverage and to hopefully help in future to catch some possible bugs.
Feature
- TextInput now has `hintText` and `type` props.
=> [Feature] TextInput improvements

package.json, yarn.lock
elliptic and prismjs had security vulnerabilities and needed to be updated. Since they are dependencies of webpack and styleguidist respectively, those libraries were updated to fix the issue.
Dependabot alerted about potential security issues in these libraries.
By running styleguidist as well as in a CRA project
Update dependecies to fix potential vulnerabilities
=> [Update] Update webpack and styleguidist to latest stable releases

yarn.lock
Upgrade suomifi-icons to latest 1.0.1 version and fix related security issues.
suomifi-icons had vulnerable dependencies which have now been fixed.
Tested using a create react app project, SSR template project and styleguidist build.
- Suomifi-icons upgraded to 1.0.1
=> [BugFix] Upgrade suomifi-icons to latest 1.0.1.

src/core/Button/UnstyledButton.tsx, src/core/Expander/__snapshots__/ExpanderGroup.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap
Tokens prop is now discarded for unstyled Button variant.
Tokens object was passed to DOM when provided to unstyled variant of button.
All buttons accept the tokens prop, but unstyled Button variant does not utilize it. In some cases it is dynamically passed anyways, so the best approach is just to remove it before render to keep the Button API's consistent.
Tested with Create React App TS and SSR template test projects.
- Tokens prop is now discarded for unstyled Button variant.
=> [BugFix] discard passProps tokens for unStyled Button

src/components/Form/TextInput.tsx, src/components/Form/Textarea.tsx, src/components/Form/Toggle.tsx, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/Textarea/Textarea.test.tsx, src/core/Form/Toggle/Toggle.test.tsx
This PR adds name property to form components that didn't previously have them.
ToggleInput is not really a form component, but is a checkbox under the hood, so name prop was added for that as well.
Also added documentation for the children prop in TextInput.
Form elements should support different ways of using them, and those ways should be documented. With the addition of documentation for the name prop the support for a classic way of building a form is effectively conveyed.
Running locally & automated tests.
Added name property to form component APIs.
=> [Feature] Add name prop to form component APIs

src/components/Form/Checkbox.tsx
This PR adds a logger warning to checkbox when either name or value props have an empty value.
Name and/or value props having empty values can lead to issues. Therefore it should be avoided. To help that, the library should warn the developer when an empty value for those props is given.
Tested by running locally and manually giving the props different values as well as with automated tests.
Added empty value or name warning to checkbox.
=> [Feature] Add logger warning to checkbox when name or value props have an empty value

src/components/Form/Checkbox.tsx, src/components/Form/TextInput.tsx, src/components/Form/Textarea.tsx, src/core/Form/Checkbox/Checkbox.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/Textarea.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
This PR adds aria-invalid attributes to inputs that already have the status prop. Aria-invalid is set to true when status equals "error".
Additionally, redundant aria-describedby attributes have been removed TextInput and those are now only read once by screenreaders.
Cases where there are errors are now natively announced by screen readers. This is a better practice than only relying on error messages.
Tested with Mac OS Safari, Chrome and Firefox browsers using VoiceOver and Windows Chrome, Firefox and Edge browsers using NVDA.
- Form components with status now also use aria-invalid to communicate errors.
- TextInput labels and texts are not read twice any more.
=> [Feature] Aria-invalid attributes

src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR implements support for using icons inside the text input component. User can give the icon name as well as any preferred icon props to the component. Those get passed to the corresponding elements. The necessary styling is also applied when an icon is given.
Text input with an icon is part of the designs for this component, but it hasn't been implemented until now.
So far only tested by running locally.
Added support for icons inside text inputs.
=> [Feature] Text input icon support

src/core/Chip/Chip.baseStyles.tsx, src/core/Chip/__snapshots__/Chip.test.tsx.snap
This PR fixes a couple of small bugs in the chip component:
- The background color of the disabled variant now has the correct color token (darker than previously)
- The disabled cursor now applies to the icon as well, if one is present.
Components should match the designs and not have bugs.
Tested by running locally and checking visually.
Disabled chip now has correct color
=> [Bugfix] Disabled chip color and cursor

src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
Text input icon color was unaffected in disabled styles, which made it stand out and take away from the visual cue of the input being disabled. This PR applies a style to set the icon color to a lighter one when the component is disabled.
Tested in styleguidist in local environment.
Apply disabled styles to text input icon as well
=> [Bugfix] Disabled text input icon color

README.md
The readme section instructed the user to add our custom CSS file in order to make the library work as intended. This is not the only way, so this PR adds a mention of alternative ways of implementing the necessary styles.
The issue was brought up by a developer using the library.
Running locally.
-Update readme on implementing required styles
=> [Feature] Update readme to cover alternative css imports

src/components/Form/TextInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR implements optionalText prop for text input. The implementation is similar to that in Textarea. Through the prop the user of the component can mark the field optional with the text of their choice.
This feature is part of the design, so it needed to be implemented.
Automated tests and running locally in styleguidist.
-Added a way to mark text input as an optional field
=> [Feature] Text input optionalText prop

src/components/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown.baseStyles.tsx
This PR adds a styling for the currently selected item in dropdown.
Previously the styling was tied to the hover styles, which meant that hovering over an option in the dropdown made the selected style disappear. The styling also didn't match the current designs. This PR fixes both of those issues.
Tested by running locally in styleguidist.
-Improve styling of selected element in dropdown
=> [Feature] Create separate styling for selected items in dropdown

src/components/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown.md, src/core/Dropdown/Dropdown.test.tsx, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap
This PR implements disabled prop and the corresponding styling for the dropdown component.
Being able to disable a component is one of the key functions of any input component and needs to be supported.
Only tested by running locally in styleguidist.
-Added disabled prop for Dropdown component
=> [Feature] Dropdown disabled state

src/core/Chip/Chip.md
The Chip component styleguidist example used inline styles, which are not actually supported by the component. This PR removes the bad practice from the example by moving the inline style to a wrapping span element.
We shouldn't demonstrate unsupported uses of the components.
Tested by running locally.
-Fixed unsupported use of inline styles from Chip example
=> [Bugfix] Move Chip example inline styling to wrapping element

src/core/LanguageMenu/LanguageMenu.baseStyles.tsx, src/core/LanguageMenu/LanguageMenu.tsx, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
Long text will now wrap more nicely in the **LanguageMenu**
* In the button that opens the menu
* ...and in the opened menu
Long text was not wrapping as wanted on the LanguageMenu.
- Locally in styleguidist
_In the screenshot the area circled shows the gap that is intentionally left on the left side, so that menu is not "touching" the edge._
Fix wrapping of long text in the LanguageMenu (#408)
=> [Fix] LanguageMenu text wrapping

package.json
Increase version number to 3.0.0-beta.0 for a preview beta release.
Includes the following PR's:
#408 LanguageMenu text wrapping
- Fix wrapping of long text in the LanguageMenu
#409 Upgrade dependencies to latest
- Breaking Change: Styled components and related types upgraded to version 5 and require configuration to allow skipLibCheck true. Also peer dependencies have been updated accordingly. Additional non breaking dependency upgrades.
#410 Update suomifi-icons and suomifi-design-tokens dependencies
- Breaking change: changes to color token values
- Other changes: new tokens and icons due to updated suomifi-icons and suomifi-design-tokens
#411 TextInput improvements
- Breaking changes: TextInput - Remove labelProps, labelTextProps and children props + classname changes because of …
=> [Release] 3.0.0-beta.0.

src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR removes the clear button and "show password" pseudo elements for text/password input in Internet Explorer.
These elements are not part of the design and are not shown in other browsers. This PR will put IE behavior in line with other browsers and the design.
Tested by automated tests and by running in design system site.
Input in internet explorer before the change:
Input in internet explorer after the change:
*Remove Internet Explorer native pseudo elements from text input
=> [Bugfix] Remove native internet explorer pseudo elements from text input

src/core/Block/__snapshots__/Block.test.tsx.snap, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Chip/__snapshots__/Chip.test.tsx.snap, src/core/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap, src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap, src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/RadioButton/RadioButton.baseStyles.tsx, src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap, src/core/Form/Toggle/__snapshots__/Toggle.test.tsx.snap, src/core/Heading/__snapshots__/Heading.test.tsx.snap, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/Link.baseStyles.ts, src/core/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/core/Paragraph/__snapshots__/Paragraph.test.tsx.snap, src/core/Text/__snapshots__/Text.test.tsx.snap, src/core/theme/__snapshots__/tokens.test.tsx.snap, src/reset/utils/index.ts
This PR fixes a couple of reported issues where global styles caused inherited box-size CSS rules to cause some issues with radiobutton and external link. External link icon size was also wrong. That was fixed in the process.
This was a reported bug, which, while it was caused by a global rule in a different project, was easier to fix on our end.
Tested in styleguidist in chrome.
-External link and RadioButton pseudo elements now have explicitly set box-size.
=> [Bugfix] Box sizing inheritance

package.json, yarn.lock
This PR adds resolution for react-styleguidist - react-devtools - immer to fix security issue. The resolution is added for all styleguidist immer sub-dependencies (react-styleguidist/**/immer) and sets the immer version to ^8.0.1.
Dependabot security alert.
There is no updated version of styleguidist available, so a temporary resolution for immer is needed.
Tested with styleguidist build using Mac OS and Chrome. This only concerns the styleguide.
- Set styleguidist immer sub-dependency resolution to ^8.0.1
=> [BugFix] Add resolution for react-styleguidist immer dependency

package.json
This PR increases version to 3.0.0. 
Changes since 2.0.0:
- _Breaking Changes_:
- Styled components and related types upgraded to version 5 and require configuration to allow skipLibCheck true. Also peer dependencies have been updated accordingly. Additional non breaking dependency upgrades.(#409)
- Changes to color token values (#410)
- TypeScript minimum supported version updated to 3.8. (#421)
- Add new tokens and icons due to updated suomifi-icons and suomifi-design-tokens (#410)
- All dependencies but webpack updated to latest. (#421)
- Improve test run speeds (#422)
- Fixes and improvements for aria attribute handling. (#423)
- Add internal FilterInput component (#425)
- Styleguidist immer sub-dependency resolution is now set to ^8.0.1 (#430)
- Fix wrapping of long text in the …
=> [Release] 3.0.0

src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/SearchInput.md, src/core/Form/SearchInput/SearchInput.test.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
This PR adds AutoId for SearchInput and replaces the old uuid implementation. By doing so SSR support is improved and the id mismatch between server and client no longer happens.
In addition, this PR introduces an intermediate style wrapper so that it is now possible to add margin/display etc styles directly to SearchInput without breaking the component.
SSR Should be fully supported to allow faster page loads and hydration on client side. Positioning the components should be possible without the danger of breaking the internal layout and styles and this can be achieved by adding an additional style wrapper inside the component.
Tested with Mac OS and VoiceOver using Firefox, Safari and Chrome and with Win10 and NVDA using Chrome, Firefox and Edge.
**SearchInput**
- Add better support for …
=> [Feature] SearchInput auto id

src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR implements AutoId, aria util, style wrapper and fixes non-neutral status border width. 
Style wrapper safeguards against alignment issues and ensures the integrity of the component. AutoId helps with server side rendering by ensuring the ID on the server and client side match. Internal aria util ensures the conditional aria props are put in place in a clean manner. Border was previously 1px wide for all states, but in designs it is 2px for the error and success statuses. 
Tested by running in styleguidist and by automated tests.
Text Input
* **Breaking change**: inputContainerProps renamed to wrapperProps
* Error and success status border width now 2px
=> [BreakingChange] Text input AutoId, aria util and styling

src/core/Form/TextInput/TextInput.tsx
This PR addresses an issue where a missing spread operator caused icon props not to be conveyed to the icon component within a TextInput correctly.
This bug was found after merging recent changes to the TextInput component. It's an easy fix, so it was decided to fix it asap.
Tested in styleguidist in chrome
* Fixed a recent bug that caused icon props to not work correctly
=> [Bugfix] Add missing spread operator to TextInput icon props

package.json, src/utils/AutoId.tsx, yarn.lock
This PR upgrades two vulnerable transitive dependencies. These were scoped so that it was possible to update by simply uninstalling and reinstalling both react-styleguidist and webpack without changing direct dependency versions.
In addition, styleguidist immer resolution could be removed because it was updated already.
Also small linter related issue with AutoId return condition was fixed to allow better functionality with VSCode plugins. (Would not pass linters if related dependencies were updated to latest).
Prims and Elliptic versions defined in yarn.lock were vulnerable.
These are dev dependencies, but were updated just to be on the safe side.
Tested using Chrome on MacOS and styleguidist build. Should not introduce any changes to functionality as no major version updates were made …
=> [BugFix] Update vulnerable dependencies

src/utils/AutoId.tsx
This PR fixes AutoId issues with Server Side Rendering. Current implementation returns no children wrapped in AutoId when rendering in server for dehydrate/rehydrate. Desired behaviour would be to render the DOM in server, as closely to what is rendered in client, as possible. In this case, ids should be empty when rendered on server and patched in place with hooks on client. Current behaviour does not break anything, but may cause additional renders on client.
To enable efficient rendering and utilisation of SSR, rendered DOM's should match between server and client, with the exception of portals and and content that has to be positioned based on rendered content.
Tested with Styleguidist, Create React App TypeScript project and SSR test project on Mac OS and Chrome. Also DOM contents …
=> Fix SSR issue with AutoId.

package.json, src/core/Button/Button.baseStyles.tsx, src/core/Button/Button.md, src/core/Button/Button.test.tsx, src/core/Button/Button.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Colors/__snapshots__/Colors.test.tsx.snap, src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap, src/core/theme/colors.ts, yarn.lock
This PR replaces the button tertiary variant with link variant. It also adjusts the button secondary noborder styles to work on different backgrounds. To make these changes, suomifi-design-tokens dependency was updated to get the recently updated color token values.
The implementation differed from the designs, and there were requests from the projects using the library to make button secondary noborder compatible with other background colors than white.
Automated tests and running locally in Windows using Chrome, Firefox and Edge.
secondary noborder hover styles with colored background
* Button tertiary variant replaced by link button variant
* Button secondary-noborder variant renamed to secondaryNoBorder
* depthSecondaryDark1 color token value changed
* suomifi-design-tokens dependency …
=> [Feature] Button secondary noborder styles and button link variant

package.json, src/utils/uuid.ts, yarn.lock
This PR removes the uuid dependency, its type definitions and related util from the library.
uuid seems to be replaced by AutoId in all cases, which means uuid dependency, type definitions and util can be removed from the library.
Tested by running locally in styleguidist on Chrome. I found no instances of the generateId util based on the uuid, so it should be safe to remove.
* uuid removed from dependencies
=> [Fix] Remove uuid dependency, type definitions and util

src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/TextInput/TextInput.tsx
This PR fixes an issue where debounce prop was unnecessarily passed onto the input element in TextInput and SearchInput.
Debounce has no function in the input element and needed to be destructured out.
Running locally in styleguidist on Chrome + automated tests.
* Prevent debounce prop from passing onto the input element
=> [Bugfix] Destructure debounce out of TextInput and SearchInput props

src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap, src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap, src/core/Text/Text.baseStyles.ts, src/core/Text/Text.tsx
This PR fixes the broken color prop in the Text component. The color prop was not passed on or utilized in any way after the recent tokens revamp.
This was an obvious bug that needed to be fixed asap.
Tested by running locally in styleguidist in Chrome.
* Fix broken color prop
=> [Fix] Text component color prop

src/core/Form/Checkbox/Checkbox.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/FilterInput/FilterInput.tsx, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/StatusText/StatusText.baseStyles.tsx, src/core/Form/StatusText/StatusText.test.tsx, src/core/Form/StatusText/StatusText.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/Textarea.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap, src/core/Form/types.ts, src/utils/aria.ts
This PR makes status text an aria-live region, so screen reader users get information of status changes immediately. It also implements this change into form components using StatusText.
The lack of information about component status changes was something that has come up in the recent accessibility clinics and needed to be addressed.
Tested with NVDA + chrome + FF and Talkback + Chrome.
* Status text now has `aria-live="assertive"` by default. This can be changed via `statusTextAriaLiveMode` prop.
=> [Fix] Form element status accessibility

package.json, yarn.lock
This PR updates the `suomifi-design-tokens` dependency to 3.1.1. There are no changes in the tokens themselves. This update simply fixes a vulnerability in the dependencies of `suomifi-design-tokens`.
Vulnerable dependencies should be updated asap.
Tested that the build works and everything looks like it should in styleguidist on Chrome.
* Suomifi-design-tokens updated to 3.1.1
=> [Dependencies] Update suomifi-design-tokens to 3.1.1

src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/StatusText/StatusText.test.tsx, src/core/Form/StatusText/StatusText.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
This PR adds aria-atomic to the StatusText component in order to have screen readers read the status messages in their entirety even when only a part of them changes. It also adds a test for the new prop.
It was decided that it would be better to ensure that the error and other status messages are read in their entirety even when only a part of them changes.
Tested by running locally in styleguidist in Chrome and FF. Changing content triggers reading the whole content of the StatusText element.
* Status texts now have `aria-atomic` set to true
=> [Feature] Add aria-atomic to StatusText component

package.json, yarn.lock
This PR updates some dependencies in order to fix vulnerabilities in the library. The updated dependencies are react-styleguidist, rollup-plugin-ts. Lodash is also resolved to a newer version to apply patches to some vulnerabilities.
The same changes will be made to develop branch as well so they will be included in the future releases.
Critical vulnerabilities in the library or its dependencies should be patched as soon as possible.
Tested by running in styleguidist, building and running in a CRA project and by manually comparing the dist files before and after the updates.
* Internal dependencies updated to fix vulnerabilities
=> [Fix] Update vulnerable dependencies

package.json, yarn.lock
This PR updates some dev dependencies in order to patch vulnerabilities in transitive dependencies.
The dev dependencies had some critical vulnerabilities that needed to be patched. With the 4.0.0 release looming, it makes sense to do this now.
Tested by building and running locally in styleguidist. 
* Patches to vulnerabilities in dev dependencies
=> [Fix] Update vulnerable dependencies for 4.0.0

src/core/Button/Button.tsx, src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx, src/core/Expander/ExpanderTitle/ExpanderTitle.tsx, src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Modal/Modal/Modal.md, src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalContent/ModalContent.baseStyles.tsx, src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
This PR fixes some component styles to enable focusing inside modal using tab-key. In addition, this PR introduces scroll padding for the ModalContent to ensure focused content fits into view. 
**NOTE: React-modal does not consider some inline elements to be focusable. To ensure focusability inside Modal, components must have non zero size, be visible, have tabindex of 1 or 0, must be of node type /input|select|textarea|button|object or a with either tabIndex or href attribute and cannot be disabled!**
(https://github.com/reactjs/react-modal/blob/master/src/helpers/tabbable.js)
After refactoring the Modal to use react-modal under the hood, some components became impossible to focus using tab-key when placed inside modal. This was caused by react-modals white-listing strategy for focus …
=> [Fix] Component focusability in modal

package.json, yarn.lock
This PR bumps the version of `dns-packet` and `ws` transitive dev dependencies in order to fix vulnerabilities.
`react-styleguidist` was removed and reinstalled in order to bump `dns-packet`, hence the large number of changes in yarn.lock.
Vulnerable dependencies should be fixed asap.
Tested by running styleguidist locally on chrome.
* Updates to some dev-dependencies in order to fix vulnerabilities
=> [Fix] Bump dns-packet and ws to fix vulnerabilities

src/core/Dropdown/Dropdown/Dropdown.tsx
This PR adds additional logic for Dropdown tab-key event handling. Current version of Reach-UI has a focus issue with the used Listbox component that allows focus to default if tab key is pressed when the listbox menu is open. This PR introduces logic to prevent the focus from escaping.
https://github.com/reach/reach-ui/issues/691
Current behaviour of Dropdown allowed focus to escape when using tab while the dropdown is open. Usually focus defaults to document body, which is really bad for keyboard, let alone screen reader, users. To temporarily address the issue:
- default tab-keypress event behviour is prevented if the Dropdown is open 
- Dropdown is closed
- Focus is returned to the Dropdown.
Tested with styleguidist build using MacOS Safari, Chrome and Edge.
- Fix Dropdown focus issue …
=> [Fix] Dropdown tab-key focus issue

src/core/Chip/Chip/Chip.md, src/core/Chip/Chip/Chip.test.tsx, src/core/Chip/Chip/Chip.tsx, src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap
Adds soft disable support for a Chip. Implementation is mimicked from the Button, where the same functionality exists.
Soft disabled Chip was needed for currently in progress component, Combobox (MultiSelect). It enables screenreader users also to "see" selected but disabled Chips in the listing under the input.
Locally in styleguidist.
* Soft disable support for Chip (#476)
=> [Feature] Soft disable support for Chip

.styleguidist/styleguidist.sections.js
MultiSelect was not showing up in styleguidist because styleguidist config still had the previous name, Combobox.
Ran styleguidist locally AFTER changes to styleguidist config as it seems to be culprit and initially introduced this mistake.
* Fix: MultiSelect was not showing up in styleguidist
=> [Fix] MultiSelect not showing up in styleguidist

.styleguidist/styleguidist.sections.js, package.json, src/index.tsx
This PR increases version number to 4.0.0 and hides MultiSelect component from Styleguide and exports. MultiSelect will be released with 4.1 once accessibility improvements have been finalised.
* Breaking change: Reach-ui peer dependency versions upgraded.
* Update for vulnerable dependencies
* Suomifi-design-tokens updated to 3.1.1
* Remove uuid dependency
* Fix AutoId SSR issue and return children always, also on server but with empty string as id.
* Breaking Change: Tokens prop is now removed from all components
* Breaking change: Replace Button tertiary variant with link button variant
* Breaking change: Rename Button secondary-noborder variant to secondaryNoBorder
* Breaking change:  Change depthSecondaryDark1 color token value
* Update suomifi-design-tokens
* Change Button …
=> [Release] 4.0.0

src/core/StaticIcon/StaticIcon.tsx
Destructure the `baseColor` prop from the props of StaticIcon, so it will not end up in the DOM anymore.
`baseColor` prop was not destructured from props, so it ended up in the DOM.
The error was like following:
```
React does not recognize the `baseColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `basecolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Locally in styleguidist
- Fix: Destructure baseColor from props in the StaticIcon
=> [Fix] Destructure baseColor from props in the StaticIcon

src/core/Form/Toggle/ToggleButton/ToggleButton.md
Fix for ToggleInput example. This PR combines two separate onClick handlers for a single ToggleInput component example.
Having more than one of the same event handlers in a React component is considered an error. This error had gone unnoticed due to md file formats not being checked by linters or build.
ToggleInput
- Fix example onClick handler.
=> [Fix] ToggleInput example

.styleguidist/styleguidist.sections.js, package.json, src/core/Form/FilterInput/FilterInput.tsx, src/core/Form/MultiSelect/MultiSelect/AriaAnnounceText.tsx, src/core/Form/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/index.tsx
Following changes improves the accessibility of the MultiSelect component. These issues were noticed in the accessibility clinic.
- `hintText` prop for MultiSelect as optional prop. Useful for user to tell that the input field can be used to filter available options.
-  `ariaOptionsAvailableText` prop as required prop for MultiSelect. It will be used to tell for screen reader user how many options are available after filtering.
-  `ariaOptionChipRemovedText` prop as required prop for MultiSelect. It will be read when selection chip is removed.
- MultiSelect is now made visible again in the styleguidist and exported from the library
This improves accessibility of the MultiSelect, especially for screen reader users.
Locally in styleguidist on macOS Safari and Brave browsers.
- Add …
=> [Fix] MultiSelect accessibility improvements 

.styleguidist/styleguidist.require.js, package.json, src/core/Breadcrumb/Breadcrumb.baseStyles.ts, src/core/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap, src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap, src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap, src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Icon/Icon.baseStyles.tsx, src/core/Icon/Icon.md, src/core/Icon/Icon.tsx, src/core/Icon/__snapshots__/Icon.test.tsx.snap, src/core/LanguageMenu/LanguageMenu.baseStyles.tsx, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/__snapshots__/LinkExternal.test.tsx.snap, src/docs/iconExampleStyles.css, yarn.lock
This PR updates the suomifi-icons dependency to the latest version of 5.0.0. It adjusts examples and component styles to accommodate for the changes in suomifi-icons.
New icons were needed in projects using suomifi-ui-components and icons. The styling logic now also offers more control over the internal styles of the svgs themselves.
Tested in styleguidist in Chrome as well as a CRA project in Chrome.
* **Breaking change**: Update suomifi-icons to 5.0.0
* Includes changes to styling logic which might cause css-based styling to require adjustment
=> [Feature] Update suomifi-icons to 5.0.0

src/core/Form/InputClearButton/InputClearButton.baseStyles.ts, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
Fix SearchInput clear button positioning when focused. Internally affects also SingleSelect styles, but the actual visual bug did not concern SingleSelect.
InputClearButton is used in SingleSelect and SearchInput and it had a position relative style accidentally applied to focus state while it should have been applied all the time. This resulted the clear button to bounce outside SearchInput while focues. 
Tested with Styleguidist build using MacOS Chrome and Safari.
SearchInput
- Fix clear button positioning
=> Fix Input clear button focus position and update snapshots.

.styleguidist/styleguidist.sections.js, package.json, src/index.tsx
This PR increases version number to 6.0.0 and hides SingleSelect component from Styleguide and exports. SingleSelect will be released with 6.1 once accessibility has been validated.
- Update vulnerable dependencies.
- **Breaking change:** Remove font imports from library provided css. Font's have to be imported separately from now on.
- Add export for suomifiTheme and related interfaces
- Add and export SuomifiThemeProvider and related documentation
- Remove css.in-to-js dependency and replace it with static object
- Refactor theme generation and remove redundant focus utils. Include derived tokens to theme.
- Directory structure:
- Remove unused login icon and directory
- Move styleguidist components to docs directory
- Cleanup utils directory structure
- Types:
- Remove all custom …
=> [Release] v6.0.0.

.styleguidist/colors.md, .styleguidist/introduction.md, .styleguidist/spacing.md, .styleguidist/typography.md, CONTRIBUTING.md, DEVELOPMENT.md, README.md
This PR aligns documentation with previous static and components level removals.
Some of the documentation was still referring to statics and components level and needed to be updated to reflect the latest changes.
Tested using Styleguidst on MacOS using Chrome.
General changes
- Fix documentation related to use of statics and components level.
=> [Fix] documentation related to statics and component level.

src/core/Alert/Alert/Alert.baseStyles.ts, src/core/Alert/Alert/Alert.md, src/core/Alert/Alert/Alert.test.tsx, src/core/Alert/Alert/Alert.tsx, src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap, src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts, src/core/Alert/BaseAlert/BaseAlert.tsx, src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts, src/core/Alert/InlineAlert/InlineAlert.md, src/core/Alert/InlineAlert/InlineAlert.tsx, src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
The alert resize, coloring and icon alignment were broken after the latest updates to the component. This PR fixes these issues. In addition, it separates the Alert and InlineAlert styleguidist examples to separate files and removes the `ariaLiveMode` prop from Alert and replaces it with hardcoded `role="alert"`.
The component should look as in the designs and behave correctly when the window is resized.
Since the default Alert is meant to be used in the beginning of main content, even before the H1, it is easily accidentally passed by the user. It should thus have `role="alert"` to ensure it is not missed by screen reader users.
Tested by running locally in styleguidist in Chrome. Final accessibility testing needed especially for the `role="alert"` change.
* Remove `ariaLiveMode` prop …
=> [Bugfix] Alert spacing, role, colors and examples

src/utils/aria/aria.ts
Update internal aria util. getConditionalAriaProp documentation and parameter naming changed.
Util documentation says that it should receive one or multiple id's. But there are multiple use cases where we are giving just text value that needs to be read by screenreader and not the id of that element. See difference of using it with e.g `aria-describedby` vs `aria-label`.
Understanding how to use the util was confusing/harder than it should be.
No release notes as this is internal change.
=> [Fix] Update internal aria util

.styleguidist/styleguidist.sections.js, src/index.tsx
Commenting the Notification out from the 6.1.0 release.
Notification was not yet gone through the accessibility clinic and therefore not ready for stable release, yet.
=> Update Notification. Hide from 6.1.0 release

src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/Checkbox.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/FilterInput/FilterInput.baseStyles.tsx, src/core/Form/FilterInput/FilterInput.tsx, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/HintText/HintText.baseStyles.tsx, src/core/Form/HintText/HintText.md, src/core/Form/Label/Label.baseStyles.tsx, src/core/Form/Label/Label.md, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/Form/StatusText/StatusText.baseStyles.tsx, src/core/Form/StatusText/StatusText.md, src/core/Form/StatusText/StatusText.tsx, src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/Textarea.baseStyles.tsx, src/core/Form/Textarea/Textarea.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
This PR removes outer margins from StatusText, HintText and Label components. Components affected by this change have been adjusted accordingly. In addition, default aria-live mode for StatusText is changed to polite.
All exported components should follow the same principles and strategy for styling and API. This PR adjusts previously internal StatusText, HintText and Label components to be aligned with all other exported components.
Tested using Styleguidist using MacOS, Chrome and VoiceOver.
- Remove margins
- Add examples
- Remove margins
- Add examples
- Remove margins
- Change aria-live default to polite
- Add examples
- Fix missing status text margin
=> [Fix] Align inner form component styles

package.json, src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap, src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts, src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap, src/docs/Colors/Colors.tsx, yarn.lock
Suomifi-design-tokens has been updated to new version and now it has two new color tokens. With this PR we import those to UI components and start using one of those. colors are "successDark1" and "warningLight1".
Component layouts should look same after this PR. Only color section should change.
Better to use "theme" variables, than color codes in CSS.
On Mac and Chrome and Safari in Styleguidist. 
- Introducing new two new color tokens from Suomifi-design-tokens. "successDark1" and "warningLight1"
=> [Dependency] Upgrade suomifi-design-tokens to 3.2.0

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
- Fix the issue when using MultiSelect in controlled state and when selecting item. Before fix the filtering value in input was not affecting and it showed all the items after selection.
- Also removes the unnecessary logic that was remaining.
- Add tests for controlled and "normal" cases so that the item amount matches after filtering.
Here is the error report we got from service which found this:
> If in controlled state for MultiSelect, an user has filtered with text then changing the selectedItems-list will keep the filter text the same but it will show all options without filtering.
> 
> E.g like this, when writing "sn" and then choosing "Snail"
> 
> ```
> const [selectedAnimals, setSelectedAnimals] = React.useState([]);
> 
> const animals = React.useMemo(() => ([
>   {   
>     age: …
```
=> [Fix] MultiSelect's controlled state should now filter also after selection

src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalContent/ModalContent.baseStyles.tsx, src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap
Suomi.fi services needed text styles to be correct without html-tags. This PR fixes &.fi-modal_content divs styles for plain text.
Fixes the issue that look and feel does not look correct for plain text. Jira ticket is: SFIDS-574
Look and feel does not look correct for plain text.
On Mac and Chrome and Safari with Styleguidist.
=> [Fix] Modal text styles

src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
Duplicate use of MenuItems removed from the LanguageMenu. Causing problems at least because having duplicate ids and other possible issues.
We got report from a service about the accessibility issue with the LanguageMenu, v6.1.1, that the duplicate ids were causing.
Issue existed in the latest develop branch also.
We would want to have the component to be as accessible as possible.
Locally in styleguidist.
_Issue can be verified from the DOM before fix and how it is corrected after the fix, was no need to test in CRA-TS or similar test projects._
- Fix LanguageMenu issue with duplicate id.
=> [Fix] Duplicate div was removed from LanguageMenu

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
Fix the MultiSelect issue for not able to select items in non-controlled state.
We would like the component to work as intended.
Locally in styleguidist and cra-ts. 
Added new test that should ensure it is behaving as wanted in this case.
- Fix MultiSelect's item selection in non-controlled state
=> [Fix] MultiSelect's item selection in non-controlled state

src/core/Alert/Alert/Alert.baseStyles.ts, src/core/Alert/Alert/Alert.tsx, src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap, src/core/Alert/BaseAlert/BaseAlert.baseStyles.ts, src/core/Alert/BaseAlert/BaseAlert.tsx, src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts, src/core/Alert/InlineAlert/InlineAlert.tsx, src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
This PR changes regular Alert structure and styling in order to have a fixed width content area containing the icon, the main content and the close button. It also contains some previously overlooked changes in spacing for the small screen variant. Because of this, the `smallScreen` prop now appears in both Alert and InlineAlert.
In addition, the icon is removed from neutral variant InlineAlert as per the designs. 
This was discussed with developers and the designers, and the intended usage was further clarified resulting in the need to change the way the Alert looks and behaves when resized.
So far tested in styleguidist + chrome on windows. Needs to be tested in a project to make sure no styles leak inside the component etc. Preferably with breakpoint-dependent styling as well.
* Change …
=> [Fix] Fixed width layout for Alert

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
This PR makes a simple addition to MultiSelect API documentation after some feedback from users. The `onItemSelectionsChange` event is not fired when the component is in controlled state and this was not documented in the API docs. This mention is now added.
The API should be up to date and clear
Just a quick glance in styleguidist, since only documentation changed.
* Improve API documentation concerning `onItemSelectionsChange` event.
=> Clarify onItemSelectionsChange prop documentation

src/core/Form/Select/SingleSelect/SingleSelect.tsx
In SingleSelect list didn't open from clicking field after user removed selection once.
There was bug before and this fixes it.
Tested in StyleGuidist with mac and chrome.
* Fixes bug. In SingleSelect list didn't open from clicking field after user removed selection once.
=> [Fix] SingleSelect. Open list by clicking field

src/core/Link/ExternalLink/ExternalLink.tsx, src/core/Link/Link/Link.md
* In External link screen reader read labelNewWindow text even if it was not opening to new window. This is fixed.
* Prop was wrongly used in example. as={Component} is renamed to asProp={Component}
There were bugs before and this fixes them.
Tested in StyleGuidist with mac and chrome.
* In External link screen reader read labelNewWindow text even if it was not opening to new window. This is fixed.
* Prop was wrongly used in example. as={Component} is renamed to asProp={Component}
=> [Fix] External link's screen reader text and asProp

src/core/Form/FilterInput/FilterInput.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx
SingleSelect had some undesired behavior when loading list of options asynchronously. When the new list was loaded, the previous selection appeared in the input even if there was some filter text in there. This PR fixes the issue. 
As changes were made to FilterInput, MultiSelect was possibly affected as well, but I did not encounter any adverse side effects upon testing.
This was a bug reported by a service using the components.
So far in styleguidist (Win + Chrome) with delayed changes to the item list applied to simulate asynchronous content.
* Improve behaviour with asynchronous content
=> [Fix] SingleSelect async support

src/core/Chip/BaseChip/BaseChip.baseStyles.tsx, src/core/Chip/Chip/Chip.baseStyles.tsx, src/core/Chip/Chip/Chip.md, src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap, src/core/Chip/StaticChip/StaticChip.md, src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
This PR change Chip and StaticChip styles to allow content spanning to multiple lines. In addition, ellipsis styles have been removed and long words break to prevent overflow.
Related snapshots have been updated.
Quite often the max-width of the chip was not sufficient for real life use cases and using ellipsis did not solve the issue as users were not able to see the whole text content of a chip.
Tested using MacOs, Chrome and Styleguidist build.
Chip & StaticChip
- Add support for multiline content
- Remove ellipsis
=> [Feature] Multiline chips

src/core/Notification/Notification.baseStyles.ts, src/core/Notification/Notification.tsx, src/core/Notification/__snapshots__/Notification.test.tsx.snap
This PR fixes an issue with the Notification close button, where the text would span multiple lines and the icon size would change when the content was long. It also removes some unnecessary elements and styling from Notification.
It was a bug and it was reported from multiple sources.
Tested in styleguidist with different widths and content sizes. On Windows + Chrome.
* Fix button styling and clean up internal structure
=> [Fix] Notification button styles and structure

src/core/Chip/StaticChip/StaticChip.tsx
StaticChip is semantically a `span` element, yet it did not extend `HtmlSpanProps` as it should have. This PR fixes that issue, so the properties and typings are correct in the future. 
Couldn't figure out if there are some other span props aside from children that we need to omit. Spend a moment to think about that when reviewing.
This was bug that needed to be fixed.
Tested in a Next.js test project in order to check typings and to see if the IDE suggestions work correctly. Worked as it should.
* Update props to extend span props
=> [Fix] StaticChip property extension

jest.config.js
We were not utilizing the coverage reports and it just caused unwanted
delays for testing. It can be enabled again if there will rise actual
need for it.
Disable Jest coverage report.
We were not utilizing the coverage reports and it just caused unwanted delays for testing. It can be enabled again if there will rise actual need for it.
Before you checkout this PR branch, run `yarn test` in some other branch, e.g `develop`.
You can see that the coverage report will be run after the tests.
Then checkout this PR and after running the tests you can no longer see the coverage report and it will finish sooner.
_No need to have in release notes as this affects only internal developing of the library._
=> [Feature] Disable coverage collection fo Jest

src/core/Form/Textarea/Textarea.baseStyles.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap, src/core/Notification/Notification.baseStyles.ts, src/core/Notification/__snapshots__/Notification.test.tsx.snap, src/core/Toast/Toast.baseStyles.tsx, src/core/Toast/__snapshots__/Toast.test.tsx.snap
This PR adds background `whiteBase` as background color to Toast, Notification and the input element in Textarea. Previously those took on the background color of their parent, which was not in line with how the rest of the components work. 
Component styles should behave predictably across the library.
Tested in styleguidist on Chrome on windows by putting the components inside a div with a background color.
* Add `whiteBase` as default background color 
* Add `whiteBase` as default background color
* Add background color for the input element
=> [Fix] Toast, Notification and Textarea background color

package.json, yarn.lock
The recent changes to the build configuration caused some styles to be broken. The cause was tracked down to be `babel-plugin-styled-components` which didn't handle some styles correctly. The bug was reported in an issue and the developers released a patch shortly after fixing the issue.
This PR updates the `babel-plugin-styled-components` to its latest version of 2.0.7, which seems to be fixing the issue.
There was a bug and this update fixes it.
Tested in a CRA project on Windows with Chrome and Firefox.
* Resolve `babel-plugin-styled-components` version to 2.0.7
=> [Fix] Update babel-plugin-styled-components to 2.0.7

.github/CODEOWNERS
This PR removes a previous member of the team from the code owners list.
Former members should no longer be marked as code owners.
* Update github code owners list
=> [Fix] Remove parted member from code owners list

src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx, src/core/Form/InputToggleButton/InputToggleButton.baseStyles.ts, src/core/Form/Select/BaseSelect/SelectItem/SelectItem.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
This PR changes the MultiSelect component so that it uses our InputToggleButton component instead of a CSS-based way to display the caret icon.
This adds a new behavior to the component: the popover can now be closed (in addition to opening) by pressing the caret icon. This was not possible previously.
The height of the InputToggleButton was also set to 100% of parent height to avoid "dead zones"
Also fixed a flaky test in SingleSelect. Used waitFor() when determining what happens when the input is blurred. 
We wanted to unify the implementations of caret icons across the different select components. The use of the InputToggleButton was copied from SingleSelect. 
With Chrome & Firefox, Mac VoiceOver in Styleguidist and a CRA app
https://user-images.githubusercontent.com/17459942/163395066- …
=> [Feature] Make MultiSelect use InputToggleButton

src/core/Expander/ExpanderGroup/ExpanderGroup.baseStyles.tsx, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
This PR fixes an issue where a generic CSS selector in Expander group component targeted all icons (.fi-icon) inside the Expander component and changed their color. This misbehaving CSS selector can be removed altogether since the correct color for the toggle icon is inherited from its parent. 
Component stylings need to be robust and predictable and not cause side effects.
On MacOS: Chrome, Safari & Firefox. Manually in Styleguidist.
* Fix CSS selector which targeted all `.fi-icon` elements inside the component and determined their color
=> [Fix] Expander group - CSS selector for .fi-icon

src/core/Form/Toggle/ToggleBase/Toggle.baseStyles.tsx, src/core/Form/Toggle/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap, src/core/Form/Toggle/ToggleInput/__snapshots__/ToggleInput.test.tsx.snap
Remove the white background color from ToggleButton and ToggleInput
Allows users to decide what color the background is.
With Firefox and Chrome.
=> [Fix] Remove background color from Toggle components

package.json, yarn.lock
This PR updates suomifi-icons version to 6.2.0. This version adds the loading spinner icon. 
On MacOS, Styleguidist, Chrome, Safari & Firefox
*  Update suomifi-icons version to 6.2.0
=> [Feature] Raise suomifi-icons version to 6.2.0

src/core/Form/RadioButton/RadioButton.baseStyles.tsx, src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
This PR adds a white fill color to radio button icon's `.fi-icon-radio-base` class, effectively making the SVG opaque
Radio button should be usable and visually pleasing on non-white backgrounds
On MacOS, Styleguidist, Chrome, Safari & Firefox
* Add white background to RadioButton icon
=> [Fix] Radio button icon background color

src/core/Form/FilterInput/FilterInput.baseStyles.tsx, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/InputClearButton/InputClearButton.baseStyles.ts, src/core/Form/InputToggleButton/InputToggleButton.baseStyles.ts, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
This PR adds the disabled state to SingleSelect and MultiSelect. The disabled prop is optional and is passed further into subcomponents like FIlterInput, InputClearButton and InputToggleButton to provide correct behavior. 
When disabled, the components are non-focusable and out of the tab order. In MultiSelect, however, the chip list items are still focusable (assuming that there are preselected values in the input).
This PR is built on top the commits of PR #600 which adds the InputToggleButton to MultiSelect.
There is a need to use these components in a disabled state.
On Mac. Chrome, Safari, Firefox. VoiceOver. In Styleguidist. 
SingleSelect
MultiSelect
* Add optional prop `disabled`
* Add optional prop `disabled`
=> [Feature] Disabled state to SingleSelect & MultiSelect

src/core/Chip/BaseChip/BaseChip.baseStyles.tsx, src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap, src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
Clean up the duplicate CSS code in BaseChip component. 
Also move focus related styling so it's inside fi-chip class.
Makes the CSS code easier to read and modify.
MacOs: Firefox, Chrome. Styleguidist, CRA. 
- Cleaned up the styling code of BaseChip component
=> [Fix] BaseChip styling cleanup

src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Link/BaseLink/BaseLink.baseStyles.ts, src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap, src/core/Link/Link/Link.baseStyles.ts, src/core/Link/Link/Link.tsx, src/core/Link/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/SkipLink/__snapshots__/SkipLink.test.tsx.snap
This PR moves the styles of `<Link>` component inside `.fi-link` class to avoid same specificity issues with `<a>` element reset styles. 
Also fixed issue with a redundant file `src/core/Link/Link/Link.baseStyles.ts` which now exports correctly named styles. 
Suomi-fi library stylings should be predictable and robust. Component styles should be more important than HTML reset styles. 
On MacOS, Styleguidist, Chrome, Safari & Firefox
* Fix CSS specificity issue which caused unpredictable component styling
=> [Fix] Link styles specificity

src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx
This PR fixes a bug in SingleSelect. The bug was as thus: When the component was in controlled state, and its `selectedItem` was changed from a defined value to `null`, the previous value was still present in the text input field. This was due to `filterInputValue` not being handled correctly in `getDerivedStateFromProps` hook. 
Components should work predictably and without bugs in all use cases.
On MacOS: Chrome, Safari, Firefox. Styleguidist. 
* Fix an issue regarding controlled state nullification
* Add `onClearSelection()` prop
=> [Fix] SingleSelect controlled state bug

.styleguidist/styleguidist.styles.js
This PR improves the readability of the API descriptions in styleguidist. Previously there was an unnecessary fade at the bottom of the prop descriptions. This PR removes that and adds lines between props as well as vertically aligns content in rows.
API descriptions should be clear and easily readable and skimmable.
By running styleguidist on Chrome on Windows
* Improve API documentation readability in Styleguidist
=> [Fix] API documentation styling

.styleguidist/ComponentsList.tsx, .styleguidist/modules.md, .styleguidist/primitive.md, .styleguidist/styleguidist.sections.js
This PR changes the Styleguidist navigation and structure. 
- Removed the Modules and Primitive categories altogether and moved all components under the Components heading
- Components are displayed in an alphabetical order
We want our documentation to be clearer and make it easier to find what you are looking for
* Remove subsections from Styleguidist components menu and put all components under one heading
* Order components alphabetically in Styleguidist menu
=> [Feature] Styleguidist menu: remove Modules & Primitive categories and sort components alphabetically

src/core/Link/ExternalLink/ExternalLink.test.tsx, src/core/Link/ExternalLink/ExternalLink.tsx, src/core/Link/Link/Link.md
This PR addresses an issue where ExternalLink would have a required prop `labelNewWindow` even when `toNewWindow` prop was set to false. The solution utilizes conditional props to change the logic as follows:
* if `toNewWindow` is true, which is also the default value, `labelNewWindow` must be set as well
* if `toNewWindow` is false, `labelNewWindow` cannot be set.
A redundant prop was required when `toNewWindow` was set to false
Tested in styleguidist on Chrome as well as in a CRA project on Chrome. Also checked that VSCode tooltips show and support the new logic.
* **Breaking change:** `labelNewWindow` no longer required or allowed when `toNewWindow` is set to false
=> [Fix] ExternalLink new window props

src/core/Notification/Notification.baseStyles.ts, src/core/Notification/Notification.md, src/core/Notification/Notification.test.tsx, src/core/Notification/Notification.tsx, src/core/Notification/__snapshots__/Notification.test.tsx.snap
This PR changes the way accessibility is taken into account in Notification. The Notification now has `role="region"` which allows the main container to have its own `aria-label` as well as to inform screen reader users upon entering and leaving the element making it clear that the notification is its own entity and thus providing context for the internal interactive elements.
Furthermore, the `ariaLiveMode` prop was discarded, as it is not used in most cases and can still be added by targeting the main content area via id if needed.
Notification had some accessibility issues, and this should fix them. The changes will need to be validated before publishing though.
So far in styleguidist using Chrome and Firefox on Windows. Will need to be tested in another project and on mobile before …
=> [Fix] Notification accessibility

src/core/Form/Checkbox/Checkbox.md, src/core/Form/Checkbox/Checkbox.tsx, src/core/Form/Checkbox/CheckboxGroup.test.tsx, src/core/Form/Checkbox/CheckboxGroup.tsx, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
Add `groupStatus` and `groupStatusText` props.
`groupStatus` will affect the children Checkboxes by passing the status to them.
If individual Checkbox has given `status` already it will be overriding the group's `groupStatus`.
Able to give status for every Checkbox that are children of the group.
So far locally in styleguidist
```
// Props given
groupStatus="error"
groupStatusText="Please choose at least one"
```
- Add `groupStatus` and `groupStatusText` props.
=> [Feature] CheckboxGroup status & status text

src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap, src/core/Form/FilterInput/FilterInput.baseStyles.tsx, src/core/Form/FilterInput/FilterInput.test.tsx, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/Label/Label.baseStyles.tsx, src/core/Form/Label/Label.test.tsx, src/core/Form/Label/Label.tsx, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, src/core/Form/SearchInput/SearchInput.test.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/Textarea.test.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
This PR changes a couple of the `<Label>` component's classnames to follow a more suitable naming convention
We want the CSS classnames to be coherent with each other and follow established naming conventions
Styleguidist
* **Breaking change**: Rename main class `.fi-label-text` to `.fi-label`
*  **Breaking change**: Rename class `.fi-label-text_optionalText` to `.fi-label_optional-text`
=> [Fix] Adjust label classnames

src/core/Tooltip/Tooltip.tsx, src/core/Tooltip/TooltipContent/TooltipContent.baseStyles.tsx
This PR fixes an issue with Tooltip's arrow borders.
We want our components to have a professional and polished visual look.
Styleguidist on MacOS Chrome, Safari & Firefox
Before:
After:
* Fix arrow borders visual glitch
=> [Fix] Tooltip arrow borders

.styleguidist/styleguidist.sections.js, src/core/Link/Link/Link.md, src/core/Link/RouterLink/RouterLink.baseStyles.ts, src/core/Link/RouterLink/RouterLink.test.tsx, src/core/Link/RouterLink/RouterLink.tsx, src/core/Link/RouterLink/__snapshots__/RouterLink.test.tsx.snap, src/core/Link/index.ts, src/index.tsx
This PR adds a new component called `<RouterLink`>. The solution is based on the work started in the branch https://github.com/vrk-kpa/suomifi-ui-components/tree/fix/as-prop
As the name suggests, the component is intended to be used with external (routing) libraries. It takes a prop called `asComponent` and renders itself as that component while applying the correct Suomi.fi styles on top of it. 
Features:
- Full Typescript support for props based on the component passed to `asComponent`
- Full theme customisation support through `SuomifiThemeProvider`
Usage example:
```
import { Link as ReactRouterLink } from "react-router-dom";
import { RouterLink } from "suomifi-ui-components";
<RouterLink asComponent={ReactRouterLink} to="/">
Home
</RouterLink>
```
We want to have a polymorphic link …
=> [Feature] Add polymorphic RouterLink component

src/core/Button/Button.tsx, src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Form/Select/BaseSelect/SelectItem/SelectItem.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Tooltip/Tooltip.tsx, src/core/Tooltip/TooltipContent/TooltipContent.tsx
Button onClick function was showing the `MouseEvent` type as a "native" version instead of the React version. Actually the React version was used. This was already fixed in the tooltip PR #596 
Now also the typings in the code are fixed. 
Also the type `KeyboardEvent` is removed from places where it's not actually used.
Removes unnecessary code and makes it a bit easier to read and use.
Typescript CRA app
- **Breaking Changes:** 
- `onClick` event is now React `MouseEvent` instead of native `MouseEvent`
- `KeyboardEvent` removed from `onClick` event type alternative
=> [Fix] Improve typings for MouseEvent and KeyboardEvent

src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/LanguageMenu/LanguageMenu/LanguageMenu.tsx
This PR merges into develop the changes from a hotfix done directly into the master branch. The original PR: #639 
* Prevent event propagation when Escape key is pressed to close the popover
* Prevent event default when pressing Enter key
* Prevent event propagation when Escape key is pressed to close the popover
=> [Hotfix] Keyboard event propagation (from master)

src/core/Block/Block.baseStyles.ts, src/core/Block/Block.md, src/core/Block/Block.tsx, src/core/Block/__snapshots__/Block.test.tsx.snap, src/core/theme/utils/spacing.ts
This PR introduces new props to the `<Block>` component. Margins and paddings can now be added separately to all sides of the component as well as to the x-axis and y-axis.
Make the `<Block>` component more usable as a wrapper
Styleguidist
* Add separate props for margin & padding to each side. The props accept suomifi-design-token spacing values.
- mt (margin-top)
- mr (margin-right)
- mb (margin-bottom)
- ml (margin-left)
- mx (margin-left & margin-right)
- my (margin-top & margin-bottom)
- pt (padding-top)
- pr (padding-right)
- pb (padding-bottom)
- pl (padding-left)
- px (padding-left & padding-right)
- py (padding-top & padding-bottom)
=> [Feature] Add all around margin & padding props to Block

src/core/Alert/InlineAlert/InlineAlert.tsx, src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Form/Checkbox/CheckboxGroup.tsx, src/core/Form/FilterInput/FilterInput.tsx, src/core/Form/RadioButton/RadioButtonGroup.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/Textarea/Textarea.tsx
This PR changes the prop type of label content from `string` to `ReactNode` in all applicable components. This allows the labels to contain other elements than just text, such as tooltip icons etc. 
The Label component itself that's used by many of the components already supports ReactNode as content, but the APIs of the components were dragging behind.
There is current and future need for more varied content in the labels.
Tested by running styleguidist locally on Chrome and adding different kinds of content to labels. Also checked that screen readers behave predictably. Optional text works as before in most cases as well.
* **Breaking change:** Change label content type from `string` to `ReactNode` (#652)
=> [Fix] Label content types

src/core/Expander/Expander/Expander.md, src/core/Expander/ExpanderGroup/ExpanderGroup.test.tsx, src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
This PR adds support for hiding the ExpanderGroup open / close all button.
In cases where there are only a couple of expanders, there is no need to show the toggle all button. Yet using a group over individual expanders is often required.
Tested using Chrome on MacOS with VoiceOver.
- Add `showToggleAllButton` prop with a default value of true
=> [Feature] Hide / show ExpanderGroup toggle all button

src/core/Block/Block.baseStyles.ts, src/core/Block/Block.md, src/core/Block/Block.tsx
This PR adds two new variant options for the `<Block>` component:
- div
- span
The existing `default` variant renders the component as a `<div>`, but it applies the reset styles from the suomifiTheme (including margin: 0 and padding: 0). This has been deemed cumbersome by our users. Now the `<Block>` component can be rendered as a plain div without the reset styles. 
In addition, there was a request to add `span` as one of the available variants. Span renders as an inline-block without reset styles
Styleguidist
* Add `div` and `span` as a possible variants. "Div" renders as a plain HTML div without suomifiTheme div reset styles. "Span" renders as an inline-block without suomifiTheme reset styles
=> [Feature] Add plain div and span as variants for Block

.styleguidist/webpack.config.js, DEVELOPMENT.md
Enables hot module replacement for styleguidist dev server.
Styleguidist's HMR has stopped working at some point. No updates were being sent to browser after compiling.
Running dev server on Windows and Mac.
\-
=> [Fix] Styleguidist HMR

.styleguidist/styleguidist.sections.js, src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.baseStyles.tsx, src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.md, src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.test.tsx, src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.tsx, src/core/Navigation/WizardNavigation/WizardNavigation/__snapshots__/WizardNavigation.test.tsx.snap, src/core/Navigation/WizardNavigation/WizardNavigationItem/WizardNavigationItem.baseStyles.tsx, src/core/Navigation/WizardNavigation/WizardNavigationItem/WizardNavigationItem.tsx, src/core/Navigation/WizardNavigation/index.ts, src/index.tsx, src/reset/HtmlNav/HtmlNav.tsx
This PR introduces the `<WizardNavigation>` component. As children, it takes `<WizardNavigationItem>` components which in turn takes a ReactNode as child. In practice, the child of a `<WizardNavigationItem>` is supposed to be a `<RouterLink>` which is polymorphic and can thus be rendered as any semantic HTML element as well as third party library elements such as React Router Link, Gatsby Link etc. 
A `<WizardNavigationItem>` can have one of these 5 statuses (affects styling and link availability):
- default: reachable & incomplete step
- current: currently active step
- completed: a step where the user has filled all necessary information
- current-completed: a combination of current and completed statuses
- coming: a step which is unreachable at the moment (but will become available …
=> [Feature] WizardNavigation

.styleguidist/styleguidist.sections.js, src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.baseStyles.tsx, src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.md, src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.test.tsx, src/core/Navigation/ServiceNavigation/ServiceNavigation/ServiceNavigation.tsx, src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap, src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.baseStyles.tsx, src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.tsx, src/core/Navigation/ServiceNavigation/index.ts, src/index.tsx
This PR introduces the `<ServiceNavigation>` component. As children, it takes `<ServiceNavigationItem>` components which in turn takes a ReactNode as child. In practice, the child of a `<ServiceNavigationItem>` is supposed to be a `<RouterLink>` which is polymorphic and can thus be rendered as any semantic HTML element as well as third party library elements such as React Router Link, Gatsby Link etc. 
We want to have ready-made navigation components available in the library. Having the polymorphic `<RouterLink>` component available was the key to implementing this component in a way which allows a wide range of usecases. 
Styleguidist, CRA app, NextJS app
* Introduce `<ServiceNavigation>` component
=> [Feature] ServiceNavigation

src/core/Link/Link/Link.md, src/core/Link/RouterLink/RouterLink.tsx, src/core/Link/RouterLink/__snapshots__/RouterLink.test.tsx.snap
This PR introduces support for React ref to `<RouterLink>`. It complies with the polymorphic nature of the component, maintaining Typescript type integrity on the ref side as well. 
Example: `<RouterLink asComponent="button" />` only accepts a ref the type of which is `HTMLButtonElement`.
Like our other components, this one now also has a prop called `forwardedRef` in its API. It works exactly the same as `ref`.
We want to have support for React ref in all our components. This one was still missing it. 
Typescript manual tests, Styleguidist
* Add support for React ref
=> [Feature] Ref to RouterLink

src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Link/BaseLink/BaseLink.baseStyles.ts, src/core/Link/BaseLink/BaseLink.tsx, src/core/Link/ExternalLink/ExternalLink.tsx, src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap, src/core/Link/Link/Link.md, src/core/Link/Link/Link.test.tsx, src/core/Link/Link/Link.tsx, src/core/Link/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/RouterLink/RouterLink.baseStyles.ts, src/core/Link/RouterLink/RouterLink.test.tsx, src/core/Link/RouterLink/RouterLink.tsx, src/core/Link/RouterLink/__snapshots__/RouterLink.test.tsx.snap, src/core/Link/SkipLink/SkipLink.baseStyles.ts, src/core/Link/SkipLink/__snapshots__/SkipLink.test.tsx.snap, src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap, src/core/Navigation/WizardNavigation/WizardNavigation/__snapshots__/WizardNavigation.test.tsx.snap
Adds property `underline` to components `Link`, `ExternalLink`, `SkipLink`, and `RouterLink`.
Links that have no underline can be hard to distinguish from other text content. Underlining links improves accessibility for users with decreased (or no) color discrimination.
Styleguidist and CRA.
- Add `underline` property to Link, ExternalLink, SkipLink, and RouterLink.
=> [Feature] Link underline option

src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Label/Label.tsx, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap
This PR addresses a bug where the hidden variant of Label was missing the passed props
The bug was noticed when developing Pagination component. For example for and id tags were not properly passed to VisuallyHidden inside the Label.
Firefox and Chrome on mac. Styleguidist.
* Fix passed props on hidden variant
=> [Fix] Add passProps for the hidden Label

src/core/Dropdown/Dropdown/Dropdown.md, src/core/Form/Checkbox/Checkbox.md, src/core/Form/RadioButton/RadioButton.md, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/TextInput/TextInput.md, src/core/Form/Textarea/Textarea.md
This PR fixes a copy-paste mistake in Tooltip related Styleguidist examples. The prop `ariaToggleButtonLabelText` was present twice and `ariaCloseButtonLabelText` was missing altogether. 
-
=> [Fix] Tooltip related styleguidist examples

src/core/Navigation/SideNavigation/SideNavigation/__snapshots__/SideNavigation.test.tsx.snap, src/core/Navigation/SideNavigation/SideNavigationItem/SideNavigationItem.baseStyles.tsx
This PR fixes a visual issue in `<SideNavigation>` component. There was 5px padding missing from the top and bottom of the level 3 list
Components need to follow the design laid out by our designers :) 
Before:
After:
* Add top and bottom padding to level 3 list
=> [Fix] SideNavigation - Add padding to level 3 list

src/core/Navigation/SideNavigation/SideNavigation/__snapshots__/SideNavigation.test.tsx.snap, src/core/Navigation/SideNavigation/SideNavigationItem/SideNavigationItem.baseStyles.tsx
This PR changes SideNavigation's focus style from `boxShadowFocus` to `absoluteFocus`
`boxShadowFocus` is placed directly to the borders of an element. This was not optimal for SideNavigation since its selected style is a deep blue color and therefore focus was not clearly visible. `absoluteFocus` is a better choice for this due to its spacing. Not a 100% optimal but better. 
Styleguidist, CRA
Before:
After:
* Adjust focus style for better visibility
=> [Fix] Adjust SideNavigation focus style

src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap, src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.baseStyles.tsx
This PR adds a CSS line which makes sure that a focused item gets the correct `blackBase` color in `<ServiceNavigation>` component
During further testing it became apparent that the focus color was not explicitly set, and due to same-specificity-issues could sometimes be set as `highlightBase` instead (inherited from regular `.fi-link--router` class)
Styleguidist, DS-site
Before:
After:
* Fix color in focus style
=> [Fix] ServiceNavigation focus color

src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap
Fix for an issue with NVDA and clear button in SearchInput
Closes https://jira.dvv.fi/browse/SFIDS-666
Fixes a focus issue with SearchInput and NVDA. When the clear button is clicked the focus should move to the input. This doesn't work properly and the user can not type.
Styleguidist. Mac VoiceOver + Firefox Chrome, Safari, Edge. Windows NVDA + Chrome, Firefox. 
* Fix focus issue with NVDA screenreader
=> [Fix] SearchInput: NVDA focus issue when hiding Clear button

src/core/Form/FilterInput/FilterInput.tsx, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
This PR connects the label and input in `<SingleSelect>` & `<MultiSelect>` (using the underlying `<FilterInput>` component). The label gets the input's ID as its `htmlFor` prop. 
NOTE: I tried to do the same thing for our `<Dropdown>`, but ReachUI's Listbox component does not allow an ID to be passed to the actual underlying `<input>` element. So no can do. 
We want SingleSelect & MultiSelect to gain focus when their label is clicked
Styleguidist
* Connect the component's label to its input via the `for` attribute to allow focus on label click
=> [Fix]: MultiSelect & SingleSelect: Associate label with input

src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.md
This PR changes `<WizardNavigation>` examples so that the elements which are currently disabled are still in the tab order, so screen reader users can know they exist.
This suggestion came up in the accessibility clinic
Styleguidist, VoiceOver
* Adjust examples so that he elements which are currently disabled are still in the tab order
=> [Fix]: WizardNav: Make disabled (coming) elements tabbable in the examples

src/core/Navigation/SideNavigation/SideNavigation/SideNavigation.md
This PR removes aria-current="location" attributes from `<SideNavigation>` examples. 
This came up in accessibility clinic. Having aria-current="location" in the parents of the currently active page was seen as more confusing than helpful. Having aria-current="page" in the item which is actually active is enough.
Styleguidist, VoiceOver
* Remove aria-current="location" attributes from examples
=> [Fix] SideNav: Remove aria-current=location from examples

src/core/Tooltip/Tooltip.test.tsx, src/core/Tooltip/TooltipContent/TooltipContent.baseStyles.tsx, src/core/Tooltip/__snapshots__/Tooltip.test.tsx.snap
This PR changes the color, size and position of the tooltip content close button so that it meets the accessibility guidelines and matches designs.
During testing I also noticed that the snapshot test didn't catch changes made to the opened tooltip content, so I changed the test to open the tooltip before taking the snapshot.
The close button in the tooltip content was unnecessarily small. The space could be utilized better so that the button size also better matches the accessibility guidelines. At the same time the color and size of the icon was adjusted so that it matches the design.
Tested by checking against designs and testing in styleguidist on Chrome and Firefox
Tooltip close button hover state:
* **Breaking Change**: Change close button size and appearance.
=> [Fix] Tooltip close button size and appearance

src/core/Form/Select/BaseSelect/SelectEmptyItem/SelectEmptyItem.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.tsx
Add support for "loading state" in MultiSelect and SingleSelect.
https://jira.dvv.fi/browse/SFIDS-510
Provide a clear indication MultiSelect / SingleSelect is loading more data.
MacOs Firefox, Chrome, Styleguidist, CRA
* Add support for loading state
* Add support for loading state
=> [Feature] Loading state for SingleSelect & MultiSelect

src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts, src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
This PR will make the InlineAlert content take up all available space.
At the moment the users need to adjust internal styling of the component if they want something to span the full width of the alert. There's no reason why this couldn't be the case out of the box.
By running in styleguidist on Chrome.
* **Breaking change:** Content will now take up all available space.
=> [Fix/Breaking change] Inline alert content area size to 100%

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx
This PR removes `null` as a possible parameter in MultiSelect's `onItemSelect()` prop. Null was there because the code had been copied over from SingleSelect where `onItemSelect()` gets called also when the input is cleared. In MultiSelect there is no such behavior.
This was reported as a bug by one of our users.
Styleguidist
* **Breaking change:** Remove redundant `null` from possible parameters in `onItemSelect()` prop
=> [Fix/BreakingChange] Multiselect onitemselect return type

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
It was noticed that the new loading state in SingleSelect and MultiSelect was not properly informed by screen readers. 
This PR adds  aria rules that will replace the "x options available" on screen reader with the "loading" text.
Also add more realistic demo in styleguidist.
https://jira.dvv.fi/browse/SFIDS-720
Closes #
Better screen reader support on select components.
Safari + Chrome + Voice Over + Styleguidist
These are probably covered by the original "loading state" feature in release notes?
* Add screen reader support for loading state
* Fix possible issue with NVDA and ariaOptionsAvailableText
* Add screen reader support for loading state
* Fix possible issue with NVDA and ariaSelectedAmountText
=> [Fix] Select components loading state screen reader improvement

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/LanguageMenu/LanguageMenu/LanguageMenu.test.tsx, src/core/LanguageMenu/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
This PR adjusts tests for SingleSelect, MultiSelect and LanguageMenu so that the snapshot tests test the opened state of the components instead of the initial state.
Some components with dynamic content such as single- and multiselect had snapshot tests that only tested the initial state of the component, which left a lot of content outside the snapshot. Thus something could have been broken or changed inside the component without it being caught by the test.
By running tests and manually checking the contents of the new snapshots.
- none needed
=> [Fix] Dynamic content snapshots

src/core/Form/DateInput/DateInput.baseStyles.tsx, src/core/Form/DateInput/DateInput.md, src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DateInput.tsx, src/core/Form/DateInput/DatePicker/DatePicker.baseStyles.tsx, src/core/Form/DateInput/DatePicker/DatePicker.tsx, src/core/Form/DateInput/DatePicker/MonthDay/MonthDay.tsx, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
PR adds variant for smallScreen for the new DateInput component.
Variant for smaller resolutions improves usability of datepicker, preventing it from appearing out of screen or being scrolled out of view.
With styleguidist
Windows, NVDA: Edge, Chrome, Firefox
Mac, VoiceOver (BrowserStack): Safari
iOS, VoiceOver: Safari, Chrome
Android, TalkBack (BrowserStack): Chrome
- Add `smallScreen` prop
=> [Feature] DateInput variant for smallScreen

src/core/Alert/Alert/Alert.baseStyles.ts, src/core/Alert/Alert/__snapshots__/Alert.test.tsx.snap, src/core/Alert/InlineAlert/InlineAlert.baseStyles.ts, src/core/Alert/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap
This PR adds a 1px visual border to `<Alert>` and `<InlineAlert>` in accordance with the recent changes in Figma styleguide.
Make the alert component pop out more from its background
* Add 1px border
=> [Feature] Add border to Alert

src/core/Dropdown/Dropdown/Dropdown.baseStyles.tsx, src/core/Dropdown/Dropdown/Dropdown.md, src/core/Dropdown/Dropdown/Dropdown.test.tsx, src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx, src/core/Dropdown/DropdownItem/DropdownItem.tsx, src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DatePicker/DatePicker.tsx, src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.baseStyles.tsx, src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.tsx, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/Popover/Popover.tsx, src/reset/HtmlButton/HtmlButton.tsx, src/reset/HtmlLi/HtmlLi.tsx, src/utils/common/common.ts
This PR introduces a complete rewrite of the `<Dropdown>` component, implementing the component without ReachUI dependencies. 
The API has stayed as similar as possible, but some changes were inevitable. See release notes for changes and additions.
`<DateInput>` uses Dropdown, so some API related as well as minor visual changes had to be made there.  
ReachUI has ceased development and it does not support React 18 anymore. We need to replace Reach stuff with our own code. 
Styleguidist on Mac Chrome, Safari, Firefox. VoiceOver on Mac. CRA with react 18
- **Breaking change**: Completely rewrite the component without using ReachUI dependency
- Remove props `dropdownButtonProps` and `dropdownPopoverProps` (these were provided by Reach)
- Change ref type from `HtmlDivElement` to …
=> [Breaking change] Dropdown without Reach

src/core/Form/DateInput/DateInput.tsx, src/core/Form/Label/Label.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/TextInput/TextInput.tsx
PR fixes typing of wrapperProps in DateInput and TextInput components. 
Fix allows users to add data-attributes in wrapperProps.
CRA with TypeScript
- **Breaking change:** `wrapperProps` prop typing is changed to include also data-attributes
=> [Breaking change] wrapperProps typing

src/core/Form/Checkbox/CheckboxGroup.baseStyles.tsx, src/core/Form/Checkbox/CheckboxGroup.tsx, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap, src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx, src/core/Form/RadioButton/RadioButtonGroup.tsx, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
Fix for margin issues on CheckboxGroup and RadiobuttonGroup.
Reason for this bug is probably that `<legend>` contains `<div>` (that has `<span>` children) element which is against [html specifications](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend)  "Permitted content | Phrasing content and headings (h1–h6 elements)." and Safari messes up the bottom margin of that inner `span`.
Issue is somewhat isolated in this example https://codepen.io/riippi/pen/xxJbYYP  (try with Safari and compare to other browsers).
Removing that div+span structure is currently not feasible so in this PR the margin is removed from span. Instead it's added to div element in question when hintText is present. 
Solution here is a bit complicated and pure CSS fix would be "ideal", but this was the …
=> [Fix] Safari margin issue with CheckboxGroup and RadiobuttonGroup

src/core/Expander/Expander/Expander.baseStyles.tsx, src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx, src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap, src/core/Expander/ExpanderGroup/ExpanderGroup.baseStyles.tsx, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap, src/core/Expander/ExpanderTitle/ExpanderTitle.baseStyles.tsx, src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap, src/core/Expander/ExpanderTitleButton/ExpanderTitleButton.baseStyles.tsx, src/core/Expander/ExpanderTitleButton/__snapshots__/ExpanderTitleButton.test.tsx.snap
This PR contains a visual update for the `<Expander>` component. Biggest changes concern the open/close button, which is now implemented using flexbox instead of absolute positioning. 
Also removed this CSS line from ExpanderContent: `transform: scaleY(0)`. The same rule is already applied in the `fi-expander_content-anim` animation, and removing it from ExpanderContent's default state seemed to fix a Safari print bug described here: https://jira.dvv.fi/browse/SFIDS-673
Expander's appearance was updated in Figma in order to better pop out from backgrounds and provide visual clues regarding click targets (hover styles)
Styleguidist, Chrome, Safari
* Update visual style: Remove shadows, add border, add hover styles
=> [Feature] Expander facelift

src/core/Expander/Expander/Expander.baseStyles.tsx, src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx, src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
With Firefox, expander's bottom border disapperas. Safari/iOS browsers on the other hand add an additional border.
Border disappearing seems to be a scaling issue with Firefox.
Border appearing seems to be a scaling issue with Safari and iOS browsers.
Styleguidist with Firefox, Chrome, Edge, and Safari, iOS with Safari and Chrome.
None (fixes issue in new UI #704)
=> [Fix] Expander border disappears when scaled

src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DateInput.tsx, src/core/Form/DateInput/DatePicker/DatePicker.baseStyles.tsx, src/core/Form/DateInput/DatePicker/DatePicker.tsx, src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.baseStyles.tsx, src/core/Form/DateInput/DatePicker/DateSelectors/DateSelectors.tsx, src/core/Form/DateInput/DatePicker/MonthDay/MonthDay.tsx, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
Based on accessibility review, removed confirm feature. Close button styles were also updated to be less dominant.
Datepicker has better usability, especially with screen readers, without separate confirm button.
Windows NVDA Edge, Chrome, Firefox
iOS VoiceOver Safari, Chrome
Mac VoiceOver (with BrowserStack) Safari, Chrome
Android (with BrowsersStack) Chrome
=> [Fix] Remove Confirm button from DateInput

src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap, src/core/Modal/ModalTitle/ModalTitle.baseStyles.tsx, src/core/Modal/ModalTitle/ModalTitle.tsx
PR unifies modal heading styles in scrollable and non-scrollable modal.
Margins under heading have been slightly different height. Margin is unified for more uniform design.
Styleguidist
- **Breaking change:** Removed class `.fi-modal_title--no-scroll` from non-scrollable dialog
=> Remove smaller margin from non-scrollable modal

src/core/Dropdown/Dropdown/Dropdown.md, src/core/Dropdown/Dropdown/Dropdown.test.tsx, src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Dropdown/DropdownItem/DropdownItem.basestyles.tsx, src/core/Dropdown/DropdownItem/DropdownItem.tsx
Adds disabled option to DropdownItem.
Dropdown had possibility to disable an option when it was implemented with Reach. Adding disabled prop makes functionality same as before.
Windows (NVDA) Chrome, Edge, Firefox
iOS (VoiceOver) Safari, Chrome
Android, Chrome (BrowserStack)
Mac, Safari (BrowserStack)
(none)
=> [Feature] DropdownItem disabled option

src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DatePicker/MonthDay/MonthDay.tsx, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap
PR changes date to aria-label and improves naming for dates disabled by shouldDisableDate prop.
Removes VisuallyHidden component dependency as unnecessary.
Windows NVDA Chrome, Edge, Firefox
iOS VoiceOver Safari, Chrome
Mac VoiceOver Safari, Chrome
Android TalkBack
=> [Fix] DateInput button text from VisuallyHidden to aria-label

src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Dropdown/DropdownItem/DropdownItem.tsx
PR fixes issues regarding Dropdown usage with screen readers
- Keyboard navigation is implemented by moving actual browser focus() to the list elements
- When selecting an item, a small 10ms timeout is used before focusing back to the dropdown button. This hack seemed to be the only way to make NVDA + Firefox work properly
Mac: Chrome and Safari with VoiceOver
iOS: Safari with VoiceOver
Windows: Chrome, Firefox, Edge with NVDA
* Fix screen reader problems
=> [Fix] Dropdown screen reader problems

src/core/Dropdown/Dropdown/Dropdown.tsx
PR introduces a fix to the below mentioned issue. Created a `componentIsMounted` variable which is checked before updating state inside a timeout
https://github.com/vrk-kpa/suomifi-ui-components/issues/720
Jest tests, where the error also occured
* Fix an issue where setState was sometimes called when the component was unmounted (https://github.com/vrk-kpa/suomifi-ui-components/issues/720)
=> [Fix] Dropdown unmounted

package.json, src/core/Dropdown/Dropdown/Dropdown.tsx, src/utils/common/common.ts
PR removes problematic code which tried to parse only the **children text content** of a selected `<DropdownItem>` into the Dropdown button element. 
This logic created problems with elements like `<FormattedMessage />` (from react-intl) and patterns like this
```
const Foo = () => 'This text will not show up in button when selected'
...
<DropdownItem>
<Foo />
</DropdownItem>
```
PR also raises version to 10.0.3 for a hotfix release
This bug was reported by a user and severely affects their application
Styleguidist, CRA with react-intl `<FormattedMessage />`
☝️ Initial bug report image
* Fix a bug where selected item text did not correctly appear in Dropdown button
=> [Fix]: Dropdown selected item parsing

package.json, src/core/Dropdown/Dropdown/Dropdown.test.tsx, src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.tsx
PR adds support to giving nested array children in Dropdown.
```
<Dropdown ...>
{['Item 1', 'Item 2', 'Item 3'].map((item) => (
<DropdownItem value={`dropdown-item-${item}`}>
{item}
</DropdownItem>
))}
<DropdownItem value="Static">Static</DropdownItem>
</Dropdown>
```
PR removes old NVDA fix that was needed for v10.0.0-beta.1 but not as of v10.0.0.
Giving a nested array as children was supported by previous Dropdown version and is a common pattern.
Old fix for NVDA with` <VisuallyHidden> `text causes confusion with mobile screen readers, that can navigate to the hidden text.
Windows: Firefox, Chrome, Edge (NVDA)
iOS: Chrome, Safari (VoiceOver)
Android: Chrome (TalkBack)
Mac: Chrome, Safari (VoiceOver)
=> [Fix] Support nested array children in Dropdown

src/core/Link/LinkList/LinkList.tsx, src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap
`ariaDescribedBy` prop accidentally went unhandled in the LinkList component. This PR fixes it so that it's implemented in the component properly.
Previously the prop simply passed to the DOM without any handling causing an error to show up in console.
Tested locally in styleguidist on Chrome. The prop is now handled correctly.
Before: 
After:
=> [Bugfix] LinkList ariaDescribedBy prop handling

src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap, src/core/Button/Button.baseStyles.tsx, src/core/Button/Button.md, src/core/Button/Button.test.tsx, src/core/Button/Button.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelectRemoveAllButton/MultiSelectRemoveAllButton.tsx, src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap, src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
PR changes Button component's variant options. Option "link" is renamed to "secondaryLight" to remove ambiguity about element's semantics. (Element is still a button with the "link" variant, and not a link.)
Closes #729
Variant naming is misleading, since variant only affects the appearance of the element. Link variant still renders a button.
With Styleguidist (Windows, Firefox)
- **Breaking change:** Rename variant `link` to `secondaryLight`
=> [Breaking change] Rename button's link variant to secondaryLight

.styleguidist/foundations.md, .styleguidist/icon.md, .styleguidist/introduction.md, .styleguidist/styleguidist.sections.js, .styleguidist/theme.md, README.md
This PR updates the styleguidist menu structure as well as adds and updates some information on the pages.
* Added introduction page with similar content to README.md
* Moved current introduction subpages under `Foundations`
Styleguidist was lacking some basic level technical information and was in need of a restructure in terms of the menu.
By running styleguidist locally on chrome.
* Update styleguidist menu structure and add general library usage documentation to styleguidist
=> [Fix] Styleguidist introduction revamp

src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/TextInput.md, src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/Textarea.baseStyles.tsx, src/core/Form/Textarea/Textarea.md, src/core/Form/Textarea/Textarea.test.tsx, src/core/Form/Textarea/Textarea.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
This PR adds character counter functionality to `Textarea` and `TextInput` components.
In some cases it is necessary to limit the input to text inputs and textarea components. In those cases it is important to let users know about the limit..
Tested on:
- Windows + NVDA +Chrome/Firefox/Edge
- macOS + VoiceOver + Safari/Chrome
- Android + TalkBack + Chrome
- iOS + VoiceOver + Safari
- Add character counter option and examples
=> [Feature] Character counter for TextInput and Textarea

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx
PR adds new props to SingleSelect and MultiSelect for passing custom data-attributes to elements that are rendered in portal.
SingleSelect and MultiSelect render displayed menu in portal that is appended to the bottom of body element. Option to add
custom data-attributes enables targeting menu and menu items in tests.
Component tests, Styleguidist testing, CRA application
- Add optional property `listProps` for passing data-attributes to unordered list element
- Add optional property `listItemProps` for passing data-attributes to list items
- Add optional property `listProps` for passing data-attributes to unordered list element
- Add optional property `listItemProps` for passing data-attributes to list items
=> [Feature] SingleSelect/MultiSelect: Additional props for data-attributes

src/core/Form/TextInput/TextInput.test.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/Textarea/Textarea.test.tsx, src/core/Form/Textarea/Textarea.tsx
This PR fixes issues regarding character counter tests in Textarea and TextInput. Character counter uses a timeout, and we wanted to use Jest fake timers to control the passage of time more accurately in the tests. Furthermore, this PR adds mounted checks to timeout to avoid the `Warning: Can't perform a React state update on an unmounted component` error. 
Error free tests
Running tests locally
None needed
=> [Fix] CharacterCounter component tests

package.json, src/docs/Icons/Icons.tsx, yarn.lock
PR updates suomifi-icons version to 7.0.1. This version contains a critical bugfix regarding icons Typescript build. 
https://github.com/vrk-kpa/suomifi-icons/issues/83
Styleguidist build, CRA
- Update `suomifi-icons` to 7.0.1
=> [Hotfix]: Update icons to 7.0.1

package.json, src/docs/Icons/Icons.tsx, yarn.lock
This PR cherry-picks a hotfix from master to develop. Original hotfix PR: https://github.com/vrk-kpa/suomifi-ui-components/pull/758
Also increased package version to 12.0.0-beta.2 to quickly make a new beta release containing the fix. 
* Update `suomifi-icons` to 7.0.1
=> [Hotfix from master] Icons update

src/core/Form/DateInput/DateInput.tsx
There was a bug in `<DateInput>` ref. User given ref was never actually set to the input, because there was an internal ref taking its place.
The implementation now uses our custom `forkRefs` utility to set both refs to the input.
Styleguidist, running Jest tests.
* Fix ref
=> [Fix]: DateInput ref

src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Breadcrumb/BreadcrumbLink/BreadcrumbLink.baseStyles.ts, src/core/Breadcrumb/BreadcrumbLink/BreadcrumbLink.tsx
PR makes the `<BreadcrumbLink>` component follow the `underline` prop, same as all other link components. 
The breadcrumb link did not have any underlining previously. 
`<BreadcrumbLink>` should work with the `underline` prop since it is part of the component's API (via BaseLinkProps)
Styleguidist
- Fix `underline` prop behavior
=> [Fix] Breadcrumb underline

package.json
PR increases version number to 12.0.0 in anticipation of a new stable release
- Improve support for Windows High Contrast Mode (#743)
- **Breaking change**: Library no longer exports main.css file. Import line for main.css should be removed
Main.css file contained styles for Reach-dependency that is now removed (#722)
- Remove ReachUI dependency from the project (#722)
- Update Styleguidist menu structure and add general library usage documentation to Styleguidist (#751)
- Enhance prop descriptions across all components of the library and adjust Styleguidist code block styles (#757)
- Update dependencies (#762)
- Update suomifi-icons to 7.1.0 (#768)
- Update Styleguidist component pages and code examples (#766)
- Introduce `<LinkList>` component
* **Breaking change:** Add `.fi-link` class …
=> Increase version to 12.0.0

src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx
Currently if the selected object in SingleSelect is updated elsewhere so that the label value is changed, the new value is updated to the popover list, but not in the input.
This PR fixes it so that the input value is also updated.
https://jira.dvv.fi/browse/SFIDS-852
This issue came from a project using SingleSelect in a form where some other input changes the item array.
Styleguidist. New unit test. 
There is a branch `fix/singleselect-modify-selected-test`  that has an styleguidist example demoing this fix. It's identical to this PR except the .md file.
- Fix input to show updated value when item array is changed
=> [Fix] SingleSelect to update when items array is changed

src/core/Expander/Expander/Expander.md, src/core/Expander/ExpanderTitle/ExpanderTitle.test.tsx, src/core/Expander/ExpanderTitle/ExpanderTitle.tsx, src/core/Expander/ExpanderTitle/__snapshots__/ExpanderTitle.test.tsx.snap
Combine ariaOpenText and ariaCloseText to toggleButtonAriaLabel. This makes the button behaviour less complicated for screen readers. The opened state is already indicated programmatically.
This makes Expander behaviour uniform between different variants.
https://jira.dvv.fi/browse/SFIDS-857
This makes the button behaviour less complicated for screen readers as the button text doesn't change on the fly.
Voiceover Chrome + Safari.
- **Breaking change:** Combine `ariaOpenText` and `ariaCloseText` props to `toggleButtonAriaLabel`
=> [Breaking change] Combine expander button aria labels

src/core/Expander/ExpanderGroup/ExpanderGroup.tsx
Make the props conditional so that `openAllText` and `closeAllText` become optional when `showToggleAllButton` is set to false.
https://jira.dvv.fi/browse/SFIDS-882
ExpanderGroup had `openAllText` and `closeAllText` as mandatory props even when `showToggleAllButton` is set to false. This PR makes it more user friendly for developers.
Styleguidist
- `openAllText` and `closeAllText` are optional when `showToggleAllButton` is set to false
=> [Fix] ExpanderGroup conditional props

src/core/ActionMenu/ActionMenuDivider/ActionMenuDivider.tsx, src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap
This was reported by Daniel. The divider in ActionMenu is not proper html as it has div inside the menu. It was also suggested not to use aria-hidden on divider so that also screen readers could "see" it.
Solutions that made it visible for screen readers didn't work as they expected some functionality from the divider that is not relevant to our use case. 
But this PR would fix the Html so that it's according to the rules. 
https://jira.dvv.fi/browse/SFIDS-859
Fixes the Html so it's according to the rules. Practical effect is minimal if any, but 
Mac chrome +  safari with voiceover.  Windows Chrome + NVDA. Android talkback.
Didn't notice any difference.
- Improved Html
=> [Fix] Html in ActionMenu divider

src/core/LanguageMenu/LanguageMenuPopover/LanguageMenuPopover.tsx, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap
This PR makes the LanguageMenu component's widths behave as thus
- The menu button will have a dynamic width based on the text in the button (`buttonText`) prop
- The popover will always have the width of the widest item in the list. Previously, the popover used to be the same width as the menu button
It was reported to us by users that the current behavior of the component is not optimal
Styleguidist
Before: 
After:
- Change the popover width to match the width of the widest element in the list
=> [Fix] LanguageMenu popover width

package.json, src/core/Link/LinkListItem/LinkListItem.tsx
PR includes a hotfix to `<LinkListItem>` component. Its `icon` prop was not rendered correctly and caused a fatal error when trying to use it. 
```
Error: Objects are not valid as a React child (found: object with keys {icon}). If you meant to render a collection of children, use an array instead.
```
Also raised version to 12.0.1 in anticipation of a hotfix release.
Styleguidist, where the error could also be replicated
* Fix `icon` prop rendering
=> [Hotfix] LinkListItem icon rendering

.github/CODEOWNERS, .styleguidist/spacingprops.md, .styleguidist/styleguidist.sections.js, src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DateInput.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/TimeInput/TimeInput.baseStyles.tsx, src/core/Form/TimeInput/TimeInput.md, src/core/Form/TimeInput/TimeInput.test.tsx, src/core/Form/TimeInput/TimeInput.tsx, src/core/Form/TimeInput/__snapshots__/TimeInput.test.tsx.snap, src/core/Form/index.ts, src/index.tsx, src/utils/common/common.ts, src/utils/common/index.ts
This PR introduces a new `<TimeInput>` component. It is very close to TextInput, but has a few autocomplete features on blur event. These instances are documented at the top of the component's Styleguidist page.
Also added a new small new feature to `<DateInput>` in this PR. This is logical because this new feature is needed when implementing the date + time pattern.  
Styleguidist. Chrome and Safari with VoiceOver
* Introduce the TimeInput component
* Add `onDatePickerButtonBlur()` prop
=> [Feature] TimeInput

package.json, src/core/Alert/Alert.tsx, src/core/InlineAlert/InlineAlert.tsx
Alert and InlineAlert `forwardedRef` props weren't correctly implemented and would in some cases show in the DOM and cause warnings. This PR fixes the issue. 
These were issues reported by developers using the library.
By checking ref functionality in styleguidist on Chrome.
* Fix ref/forwardedRef functionality
=> [Hotfix] Alert and InlineAlert refs

src/core/Expander/Expander/Expander.md, src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.md
- Change all "expanders" to "sections" in ariaOpenAllText and ariaCloseAllText in Expander example code. 
- Use the same text in `aria-label` as in `heading` in WizardNavigation. 
Improves accessibility when example code is used as-is. However, in the case of the WizardNavigation component, ideally there should be no need for an aria-label at all, unless it is desired to have a different text from the one visually shown.
=> [Fix] Expander and WizardNavigation example accessibility

src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalContent/ModalContent.baseStyles.tsx, src/core/Modal/ModalContent/__snapshots__/ModalContent.test.tsx.snap, src/core/Modal/ModalFooter/ModalFooter.baseStyles.tsx, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
This PR adjusts Modal component paddings in the `smallScreen` variant of the component according to [the updated design](https://www.figma.com/file/uBoVvfv64yvn1kDiaEJpdk/Suomi.fi---Components?node-id=1603%3A22957&mode=dev)
This saves some space on smaller screens where the margins were slightly too big previously.
Tested by running locally on styleguidist on chrome and comparing the implementation with the design.
- **Breaking change:**  Decrease padding of `smallScreen` variant
=> [Fix] Modal fullscreen padding

src/core/Form/TimeInput/TimeInput.test.tsx, src/core/Form/TimeInput/TimeInput.tsx
This PR removes `wrapperProps` from TimeInput and places the generic `style` prop to the outer div element
Other components in the library already follow this pattern
Unit test and Styleguidist
- Remove `wrapperProps` and place the generic `style` attribute to the outermost div element of the component
=> [Fix] TimeInput: Remove wrapperProps in favor of style

src/core/LanguageMenu/LanguageMenu.tsx
This PR changes the `buttonText` prop type of the LanguageMenu component from string to ReactNode
We got a request from a user that it would be nice to be able to have content in the button which allows displaying a different span based on CSS classes and media query
- **Breaking change**: Change `buttonText` prop type from string to ReactNode
=> [Feature] LanguageMenu buttonText type

package-lock.json, package.json, src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap, src/core/Alert/Alert.baseStyles.ts, src/core/Alert/Alert.tsx, src/core/Alert/__snapshots__/Alert.test.tsx.snap, src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap, src/core/Form/TimeInput/__snapshots__/TimeInput.test.tsx.snap, src/core/Heading/Heading.test.tsx, src/core/InlineAlert/InlineAlert.baseStyles.ts, src/core/InlineAlert/__snapshots__/InlineAlert.test.tsx.snap, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap, src/core/LoadingSpinner/__snapshots__/LoadingSpinner.test.tsx.snap, src/core/Navigation/WizardNavigation/WizardNavigation/__snapshots__/WizardNavigation.test.tsx.snap, src/core/Notification/Notification.baseStyles.ts, src/core/Notification/Notification.tsx, src/core/Notification/__snapshots__/Notification.test.tsx.snap, src/core/Pagination/__snapshots__/Pagination.test.tsx.snap, src/docs/Colors/Colors.tsx
This PR updates the style of `Alert`, `InlineAlert` and `Notification` components to match the updated design. In Notification, the internal structure was changed slightly to use an existing `Button` component variant instead of a custom button.
`Suomifi-design-tokens` dependency was updated to version 6.0.0 to gain access to the new and changed colors.
The designs were updated along with some recent color changes for better accessibility and usability. This simply applies the changes to the components.
Visually checked against the designs in styleguidist on Chrome.
- **Breaking change:** update styles to match new designs
- **Breaking change:** update styles to match new designs
- **Breaking change:** `closeButtonProps` are now of type `ButtonProps`
- Update `suomifi-design-tokens` to …
=> [Feature] Alert, InlineAlert and Notification style update

src/docs/Colors/Colors.tsx
This PR hardcodes the brandBase color hex value as #003479 in colors documentation. Due to HSL conversion, it has been previously shown as #00357a.
This same thing has already been implemented to DS-site. 
In the beginning of time, the brand blue color of DVV was determined to be hex #003479. This color as HSL is 214.21, 100%, 23.73% (according to MacOS Chrome)
Suomifi-tokens uses HSL values for colors and when the brand color was added there it was rounded to 214, 100%, 24%
Now when this HSL is turned back to hex it's not #003479 anymore but rather #00357a. This has caused some confusion and we figured it's just easiest to display the original hex value. 
None needed? Silent change
=> [Fix] brandBase color docs

src/core/Alert/Alert.baseStyles.ts, src/core/Alert/__snapshots__/Alert.test.tsx.snap
This PR changes the color of the default info variant of `Alert` component to match the designs. It is a supplement to previous PR #796
It was an oversight in previous PR and needed to be fixed.
By checking locally in styleguidist.
None, covered in #796
=> [Fix] Alert icon color in default variant

src/core/Form/TimeInput/TimeInput.baseStyles.tsx, src/core/Form/TimeInput/__snapshots__/TimeInput.test.tsx.snap
This PR removes `width: 290px` from TimeInput styles and adds `max-width: 290px`
It makes more sense not to have fixed width for TimeInput since it's usually laid out side by side with DateInput. Fixed widths cause problems when the screen gets narrower. With max-width, TimeInput can take less space but never more than 290 (so that e.g. hintText does not overflow unnecessarily)
Styleguidist & date + time pattern on the DS site
- Change `width: 290px` to `max-width: 290px`
=> [Fix] TimeInput width

package.json, src/core/LoadingSpinner/LoadingSpinner.tsx
PR contains a hotfix to LoadingSpinner. Ref/forwardedRef was not correctly used inside the component and was not working at all. Similar thing was hotfixed to Alert & InlineAlert https://github.com/vrk-kpa/suomifi-ui-components/pull/790 previously
Also inreased version to 12.0.3 in anticipation of a hotfix release
Checking ref behavior in Styleguidist
- Fix ref/forwardedRef functionality
=> [Hotfix] LoadingSpinner ref

src/core/Form/TextInput/TextInput.tsx, src/core/Form/Textarea/Textarea.tsx, src/core/Form/index.ts, src/core/Form/types.ts, src/index.tsx
Add export for `characterCounterProps` that is used with `TextInput` & `TextArea` components.
Is the user of the library needs to for e.g alter the `TextInputProps` like following, it would then require to implement the props from the `characterCounterProps`.
Reproducing the issue without the fix:
```tsx
import { TextInput, TextInputProps } from 'suomifi-ui-components';
interface EnhancedTextInputProps extends Omit<TextInputProps, 'value'> {
something: string;
}
const EnhancedTextInput = (props:EnhancedTextInputProps) => {
const {something, ...restOfTheProps } = props;
return (
<TextInput {...restOfTheProps} />
)
};
```
The error with this example is something like:
```
Types of property 'ariaCharactersRemainingText' are incompatible.
Type '((amount: number) => string) | undefined' is not …
```
=> [Feature] Add export for characterCounterProps

package-lock.json, package.json
This PR updates suomifi-icons package to 7.2.0
It also updates various dev-dependencies to get rid of npm/dependabot warnings
- Update `suomifi-icons` to 7.2.0
- Update `@babel/runtime` to 7.23.5
- Update various devDependencies
=> [Feature] Update suomifi-icons to 7.2.0

src/core/ActionMenu/ActionMenu.baseStyles.tsx, src/core/ActionMenu/ActionMenu.test.tsx, src/core/ActionMenu/ActionMenu.tsx, src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap, src/core/Button/Button.baseStyles.tsx, src/core/Button/Button.test.tsx, src/core/Button/Button.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap, src/core/Notification/__snapshots__/Notification.test.tsx.snap, src/core/Pagination/__snapshots__/Pagination.test.tsx.snap, src/index.tsx
This PR improves support for Buttons with only an icon and no text content out of the box. Some changes:
- Icon wrapper elements are no longer rendered if corresponding icon is not specified
- Buttons are square with equal proportions when no text content is given
- Buttons require either children or an `aria-label` attribute
- Button component's `icon` and `iconRight` prop types changed from `ReactNode` to `ReactElement`
- `ActionMenuProps` changed from an interface to a type to accommodate changes
This was requested by users and the redundant wrappers were noticed by the team.
Tested by running locally on styleguidist and by trying out the new typing inside the project. Needs to be tested in another project to check the typing just in case.
**Breaking change:** Adjusted paddings to …
=> [Fix] Button support for icon only implementation

src/core/Notification/Notification.md, src/core/Notification/Notification.test.tsx, src/core/Notification/Notification.tsx, src/index.tsx
This PR makes the presence of the close button in Notification optional. This is controlled via the `showCloseButton` prop. the `closeText` prop is now required depending on the value of the `showCloseButton` prop. The new union type is also exported to help mitigate any issues that may rise due to the typing.
This feature was requested by a service, discussed among the DS team and deemed worth implementing.
By testing the typing inside the project and checking that the outcome is desired in styleguidist on Chrome.
- Make close button optional via `showCloseButton` prop.
=> [Feature] Notification close button to optional

src/core/Dropdown/Dropdown/Dropdown.tsx, src/core/Dropdown/DropdownItem/DropdownItem.tsx
Add generics to Dropdown (+ DropdownItem).
But it should not allow just any value, but value that extends String. 
This should be valid:
```tsx
type CountryKey = 'finland' | 'sweden' | 'norway' | 'denmark' | 'iceland';
```
This should not be valid (e.g number):
```tsx
type CountryKey =  1 | 2 | 3 | 4 | 5;
```
Would ease the component usage as the given type safety.
Locally in the project and then in new next.js app started from scratch.
To get rid of that error, we would need to cast it which is not nice:
```tsx
onChange={(newValue) => dropdownOnChange(newValue as CountryKey)}
```
```tsx
import { Dropdown, DropdownItem } from 'suomifi-ui-components';
// ...
type CountryKey = 'finland' | 'sweden' | 'norway' | 'denmark' | 'iceland';
interface CountryItem {
name: string;
key: CountryKey;
}; …
```
=> [Feature] Add generics to Dropdown

src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap, src/core/Form/RadioButton/RadioButton.baseStyles.tsx, src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
This PR updates the styling of the `Checkbox` component checked state as well as the focus indicator of both `Checkbox` and `RadioButton`. The checked state style also affects the error variant.
This visual change improves accessibility and overall readability of the different Checkbox states, as well as makes the focus indicator clearer matching the style of most other components.
By running locally on styleguidist on Chrome and Firefox.
**Breaking change:** Change styling of the checked state and focus indicator
**Breaking change:** Change focus indicator styling
=> [Feature] Checkbox and RadioButton visual updates

src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap, src/core/Navigation/ServiceNavigation/ServiceNavigationItem/ServiceNavigationItem.baseStyles.tsx, src/core/Navigation/SideNavigation/SideNavigation/__snapshots__/SideNavigation.test.tsx.snap, src/core/Navigation/SideNavigation/SideNavigationItem/SideNavigationItem.baseStyles.tsx
PR removes forced uppercase text from `<ServiceNavigation>` and `<SideNavigation>` components. This corresponds with the latest design changes. 
Uppercase letters were thought difficult to read and depicted as "screaming"
SideNavigation before:
SideNavigation after:
----
ServiceNavigation before:
ServiceNavigation after:
- **Breaking change**: Remove forced uppercase text from level 1 `<SideNavigationItem>`
- **Breaking change**: Remove forced uppercase text from `<ServiceNavigationItem>`
=> [Feature] SideNav & ServiceNav: Remove forced uppercases

src/core/ActionMenu/ActionMenu.baseStyles.tsx, src/core/ActionMenu/ActionMenu.tsx, src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap, src/core/Button/Button.baseStyles.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap, src/core/Notification/__snapshots__/Notification.test.tsx.snap, src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
This PR fixes the height in buttons with borders. The padding was slightly too big, so the height of the button was 42px instead of the intended 40px by default when borders were present.
This was a clear bug and needed to be fixed
By checking the styles in styleguidist on chrome.
- **Breaking change:** Decrease button top and bottom padding by 1px to fix wrong total height. Increase horizontal padding by total of 2px in borderless buttons.
=> [Fix] Button height

src/core/Link/LinkList/LinkList.md, src/core/Link/LinkList/LinkList.test.tsx, src/core/Link/LinkList/LinkList.tsx, src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap
This PR changes the `LinkList` component to use `aria-labelledby` instead of `aria-describedby` to connect the list heading to the list itself.
This is the correct aria prop to use in this case and may improve the behavior on some devices and screen readers.
Tested on NVDA on Chrome and TalkBack on Android.
- **Breaking change:** Change `ariaDescribedBy` prop to `ariaLabelledBy`.
=> [Fix] LinkList aria label

src/core/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/FilterInput/__snapshots__/FilterInput.test.tsx.snap, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/Form/StatusText/StatusText.baseStyles.tsx, src/core/Form/StatusText/StatusText.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap, src/core/Form/TimeInput/__snapshots__/TimeInput.test.tsx.snap, src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
This PR adds icons to StatusText component so that conveying the status does not solely depend on the color.
This was an accessibility issue needing a fix.
Tested by running locally in styleguidist on Chrome and Firefox
- **Breaking change:** Add icons to status text to signify error or success status
=> [Feature] Add status icons to StatusText

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.tsx
This PR adds a new prop called `onChangeWithoutDebounce()` to `<SingleSelect>` & `<MultiSelect>`. The prop is basically the same as `onChange()` but does not use the debounce time even if it is specified. 
Its inteded use case is mainly enabling the `loading` state of the component. It makes sense to show the loading spinner immediately when the user starts filtering and only make a backend call after a certain debounce time. 
In addition, this PR also fixes an oversight in the SingleSelect component `getDerivedStateFromProps()` logic. Previously, when the value of the `items` prop or the `selectedItem` prop changed, the filter input's value was always set to an empty string `''`. Now it only does that if `selectedItem` is set to null. 
It was reported by users that having the `loading` …
=> [Feature] SingleSelect & MultiSelect: Add onChangeWithoutDebounce()

package-lock.json, package.json, src/core/Form/DateInput/DateInput.tsx, src/core/Form/RadioButton/RadioButton.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/Textarea/Textarea.tsx, src/core/Form/TimeInput/TimeInput.tsx, src/core/LanguageMenu/LanguageMenu.tsx, src/core/Pagination/Pagination.tsx
This PR fixes some overlap in typing related to callbacks such as `onChange`, `onClick` and `onBlur`. After the recent change of extending component props with relevant HTML props, the typings were accidentally changed in components where there were differing typings for the callbacks in the component APIs and the HTML props they extended.
The issue was fixed by omitting the overlapping props from the extended HTML props.
There was an unintended change in typings which caused issues for developers.
Tested in a React+Vite test project with latest Typescript to see if the issues were indeed fixed.
- Fix unintentionally changed typings in `onChange`, `onClick` and `onBlur` props in several components
=> [Hotfix] Typing in callback function props

package-lock.json, package.json, src/core/Form/DateInput/DateInput.tsx, src/core/Form/RadioButton/RadioButton.tsx, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/TextInput/TextInput.tsx, src/core/Form/Textarea/Textarea.tsx, src/core/Form/TimeInput/TimeInput.tsx, src/core/LanguageMenu/LanguageMenu.tsx, src/core/Pagination/Pagination.tsx
This PR fixes some overlap in typing related to callbacks such as `onChange`, `onClick` and `onBlur`. After the recent change of extending component props with relevant HTML props, the typings were accidentally changed in components where there were differing typings for the callbacks in the component APIs and the HTML props they extended.
The issue was fixed by omitting the overlapping props from the extended HTML props.
**This PR contains the cherry-picked changes made to master branch in PR #828**
There was an unintended change in typings which caused issues for developers.
Tested in a React+Vite test project with latest Typescript to see if the issues were indeed fixed.
- Fix unintentionally changed typings in `onChange`, `onClick` and `onBlur` props in several components
=> [Hotfix from master] Typing in callback function props

src/core/Block/Block.baseStyles.ts, src/core/Block/Block.test.tsx, src/core/Block/Block.tsx, src/core/Block/__snapshots__/Block.test.tsx.snap, src/core/theme/utils/spacing.ts
This PR changes the spacing prop implementation of block back to a CSS-based solution from the style prop based one introduced last fall. The previous change caused issues with strict content security policies which disallow inline styles.
The issue was reported by services using the library and upon discussion it seemed like multiple projects were affected
Tested by running styleguidist locally on chrome and checking that the props work
- **Breaking change:** Change spacing props to use CSS spaced implementation instead of style prop
=> [Bugfix] Block spacing props to CSS

src/core/Tooltip/Tooltip.tsx
This PR prevents an unwanted Tooltip prop from ending up in DOM. The `anchorElement` props is used in some hooks, but it was not destructured away upon rendering the component, causing it to end up in DOM.
This was noticed when making other changes and was clearly a minor bug with an easy fix.
Tested in styleguidist on chrome by checking that the prop no longer appears in DOM
- Prevent an unwanted prop from showing up in DOM
=> [Bugfix] Remove Tooltip anchorElement prop from DOM

src/core/Expander/ExpanderGroup/ExpanderGroup.tsx, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
This PR removes the `aria-expanded` property from the ExpanderGroup open/close all button.
It was deemed unnecessary an somewhat of an anti-pattern by multiple accessibility specialists and thus needed to be removed.
Tested by running locally on styleguidist on chrome, checking the DOM and testing with NVDA to see that the `aria-expanded` prop was gone.
-Remove `aria-expanded` from open/close all button
=> [Bugfix] Remove aria-expanded from ExpanderGroup open/close all button

src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap, src/core/Link/LinkListItem/LinkListItem.tsx
There was a redundant color prop in LinkListItem's default icon, which caused some weird issues in some cases. The quickest fix was to remove the prop, since the color was specified in the styles already.
This was reported by a developer and was clearly redundant code
Tested in React + Vite test project on Chrome
- Remove redundant color prop from default icon
=> [Bugfix] LinkListItem icon redundant color prop

src/core/ActionMenu/ActionMenu.tsx, src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap, src/core/Button/Button.baseStyles.tsx, src/core/Button/Button.md, src/core/Button/Button.test.tsx, src/core/Button/Button.tsx, src/core/Button/__snapshots__/Button.test.tsx.snap, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/LoadingSpinner/LoadingSpinner.baseStyles.tsx, src/core/LoadingSpinner/__snapshots__/LoadingSpinner.test.tsx.snap, src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap, src/core/Notification/Notification.tsx, src/core/Notification/__snapshots__/Notification.test.tsx.snap, src/core/Pagination/__snapshots__/Pagination.test.tsx.snap
PR adds the `loading` prop to `<Button>`. With the loading state, `ariaLoadingText` is also required. 
PR also adds a permanent `<VisuallyHidden>` aria-live region in the DOM next to the button. In normal use, the element is just an empty div node. When the loading state is applied, the node gets populated with the `ariaLoadingText` string and it gets announced by screen readers. 
In styleguidist on macOS Chrome + Voiceover. More testing needed with browsers and screen readers. 
https://github.com/vrk-kpa/suomifi-ui-components/assets/17459942/64474f02-5085-41a2-a31c-9146a4335e05
- Add `loading` and `ariaLoadingText` props. Applies a loading spinner to the button and disables it.
=> [Feature] Loading spinner in button

src/core/Form/TextInput/TextInput.tsx, src/core/Form/index.ts, src/core/theme/index.ts, src/index.tsx
This PR adds exports to some types requested by the developers, namely:
- `TextInputValue` from TextInput
- `PaddingProps`, `MarginProps`, `SpacingProps` and `SpacingWithoutInsetProp`
These types were requested by developers.
Tested by using the library in a React + Vite project and using the types both correctly and incorrectly in a component.
- Add exports for several types:
- `TextInputValue` from TextInput
- `PaddingProps`, `MarginProps`, `SpacingProps` and `SpacingWithoutInsetProp`
=> [Feature] Add type exports

src/core/Form/TextInput/TextInput.baseStyles.tsx, src/core/Form/TextInput/__snapshots__/TextInput.test.tsx.snap, src/core/Form/Textarea/Textarea.baseStyles.tsx, src/core/Form/Textarea/__snapshots__/Textarea.test.tsx.snap
There were a few issues with the spacings of TextInput and Textarea, which this PR fixes:
- TextInput had an implicit line-height set at the top level, which caused the component to take up unnecessary extra space
- There was a 1px difference between status text and character counter top margins
- Textarea label was lacking the correct bottom margin
The line height issue was reported by a developer, and the other issues were noticed during the fixing and testing of that change.
Tested by running locally on styleguidist on chrome and inspecting the rendered styles and visual representations.
- **Breaking change:** Remove redundant root level font styles and set line-height to 0 on top level.
- **Breaking change:** Increase character counter top margin by 1px
- **Breaking change:** Set the …
=> [Bugfix] TextInput and Textarea spacings

src/core/Form/Checkbox/Checkbox.tsx
This PR fixes an issue where the checkbox check mark color was not visible in disabled state.
This is a bug that was reported by a developer.
Tested by running locally on styleguidist and checking the rendered styles as well as the visual result.
- Fixed an issue where checkmark was not visible in disabled state
=> [Bugfix] Disabled checkbox icon visibility

src/core/Form/StatusText/StatusText.tsx
This PR sets the StatusText to only render the icon corresponding the status when the component has content. This is to avoid showing orphaned icons when the StatusText is present without content.
This was a clear but that was noticed while making other changes.
Tested in styleguidist locally on Chrome
- Set icon to render only when component has children
=> [Bugfix] Empty StatusText icon render

src/core/Dropdown/Dropdown/Dropdown.tsx
PR fixes an issue with `<Dropdown>` where its apparent selected value did not get updated when children change. 
Case: Switching application's language. The selected DropdownItem's `value` remains the same, but its displayed value changes. We need to handle this case and force the recalculation of `selectedValueNode` in the Dropdown's state. 
Styleguidist on Chrome
- Fix an issue where visible selected value did not get updated when changing application language (DropdownItem visible text changes but value remains the same)
=> [Fix] Dropdown selected value when children change (case language change)

src/core/Button/Button.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Tooltip/Tooltip.tsx, src/core/VisuallyHidden/VisuallyHidden.tsx
PR removes unwanted props from leaking to DOM in the `<Tooltip>` and `<VisuallyHidden>` components. 
Also remove redundant `never` typings from a few conditional prop types in `<Button>`, `<MultiSelect>` and `<SingleSelect>`
These were reported as bugs by a user
Styleguidist + CRA project + Typescript tests in this repo
- Prevent `onToggleButtonClick` and `onCloseButtonClick` props from leaking to DOM
- Fix `forwardedRef` behavior
- Remove redundant `never` typing from `LoadingProps`
- Remove redundant `never` typing from `LoadingProps`
- Remove redundant `never` typing from `AllowItemAdditionProps`
- Remove redundant `never` typing from `LoadingProps`
- Remove redundant `never` typing from `AllowItemAdditionProps`
=> [Fix] Remove unwanted props from DOM + remove redundant never types from some conditional props

src/core/Form/Checkbox/Checkbox.baseStyles.tsx, src/core/Form/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/core/Form/Checkbox/__snapshots__/CheckboxGroup.test.tsx.snap
This PR changes the Checkbox hint text color to match the designs.
This was a minor visual bug and needed to be fixed.
Tested by checking the corrected visual outcome in styleguidist.
- **Breaking change:** change disabled variant hint text color to match the label color
=> [Fix] Disabled checkbox hint text color

src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DateInput.tsx, src/core/Form/DateInput/DatePicker/DatePicker.tsx
This PR adds the possibility to add a collection of props in DateInput props that get passed to the datepicker element. This allows, for exampke, giving the picker a custom className and targeting the picker in certain situation where it wouldn't otherwise be possible due to the use of portal in the implementation.
This was reported by a developer and the solution should make it easier for them to use the component in certain situations, like inside modals.
Tested in a Vite + React project with Suomi.fi modal and some modified styles. Also tested in a CRA project
- Add `datePickerProps` prop
=> [Feature] datePickerProps

package-lock.json
This PR updates a few styleguidist related dependencies in order to patch vulnerabilities in them.
There were a few styleguidist related dependencies that contained security issues. While the risk is minimal, these should be kept up to date nonetheless.
By checking that styleguidist still runs like before after updating the deps and the library builds as normal as well.
- Minor dependency updates
=> [Fix] Patch vulnerable dependencies

src/core/Chip/BaseChip/BaseChip.baseStyles.tsx, src/core/Chip/Chip/__snapshots__/Chip.test.tsx.snap, src/core/Chip/StaticChip/__snapshots__/StaticChip.test.tsx.snap, src/core/Form/DateInput/DatePicker/MonthDay/MonthDay.baseStyles.tsx, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/SearchInput/SearchInput.baseStyles.tsx, src/core/Form/SearchInput/__snapshots__/SearchInput.test.tsx.snap, src/core/Form/Select/BaseSelect/SelectItem/SelectItem.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap
This PR fixes addresses issues where components were not fully accessible or didn't behave optimally when using Windows high contrast mode. Issues fixed:
- DatePicker disabled dates are now better distinguishable from enabled ones
- Multiselect highlighted text in list is now visible
- Disabled Chip is now distinguishable from an enabled one
Closes #744 
These are accessibility issues that needed to be tackled in order to meet our accessibility goals.
Tested by running on styleguidist on Chrome with Windows high contrast mode on.
Before:
After:
Before: 
After:
Before:
After:
- Fix accessibility issues related to Windows high contrast mode
=> [Fix] Windows high contrast mode issues

src/core/Form/DateInput/DateInput.md, src/core/Form/DateInput/DateInput.tsx, src/core/Form/DateInput/DatePicker/DatePicker.tsx
This PR adds the option to change the alignment of the date picker in relation to the date picker button in the date input.
This feature was a request from services using the component and was fairly simple to implement.
By running locally in styleguidist on Chrome and in a react + vite test project on Chrome and Firefox
- Allow custom date picker positioning via new `datePickerPosition` prop
=> [Feature] Date picker position prop

src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.md, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.test.tsx, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/SingleSelect.baseStyles.tsx, src/core/Form/Select/SingleSelect/SingleSelect.md, src/core/Form/Select/SingleSelect/SingleSelect.test.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
This PR adds the `fullWidth` prop to SingleSelect and MultiSelect. It should provide the same functionality as in other form components, namely, to set the component's width to 100%.
This addition was requested by developers and made sense since the option is available in other form components.
Tested by running locally on styleguidist on Chrome and Firefox.
- Add `fullWidth` prop
- Add `fullWidth` prop
=> [Feature] SingleSelect and MultiSelect fullWidth prop

.styleguidist/styleguidist.sections.js, src/core/Details/Details.baseStyles.ts, src/core/Details/Details.md, src/core/Details/Details.test.tsx, src/core/Details/Details.tsx, src/core/Details/__snapshots__/Details.test.tsx.snap, src/index.tsx, src/reset/HtmlDetails/HtmlDetails.tsx
This PR introduces a new component, Details, that can be used for hiding and presenting information that is not essential to most users.
This component is already in use via separate implementation, so a centralized, uniform, implementation made sense.
Tested locally in styleguidist on chrome and Windows, and in a React + Vite project on Chrome. Still needs more testing and accessibility testing especially.
- Introduce `<Details>` component
=> [Feature] Details component

src/core/Form/TextInput/TextInput.md
Some testing content from spacing provider branch got accidentally applied to development branch. This PR removes it and returns TextInput examples to their earlier state.
A clear oversight and unwanted content that needs to be corrected.
Locally on styleguidist on chrome
=> [Fix] TextInput examples

src/core/Form/Select/SingleSelect/SingleSelect.tsx
SingleSelect input value didn't behave correctly when both `onInputValueChange` and `onChange` were given and onchange altered the parent component state. The input value could not be modified in this case.
This PR provides a suggested solution to the issue.
Closes #857
This was a bug reported by users and  a service developer
Tested by running locally on styleguidist with modified examples.
- Fix an issue where input value could not be updated in a certain controlled state situation
=> [Bugfix] SingleSelect input value in controlled state

.styleguidist/styleguidist.sections.js
PR fixes Dropdown documentation page import in Styleguidist sections. Dropdown moved under the Form-directory in PR #862
=> [Fix] Dropdown styleguidist section

src/core/Form/DateInput/DateInput.md, src/core/Form/FileInput/FileInput.baseStyles.tsx, src/core/Form/FileInput/FileInput.md, src/core/Form/FileInput/FileInput.tsx, src/core/Form/FileInput/__snapshots__/FileInput.test.tsx.snap
PR fixes an issue in FileInput's `onChange` function. The issue manifested when using the component with controlled value.
Also fixes a minor font related problem in file item.
Also fixes some Tooltip related prop naming in Styleguidist .md files.
Styleguidist and a separate CRA project
- Fix `onChange` behavior in controlled state
- Fix file item text styles
=> [Fix] FileInput onChange

package-lock.json, package.json, src/core/Form/SearchInput/SearchInput.tsx, src/core/Form/Select/BaseSelect/SelectEmptyItem/SelectEmptyItem.tsx, src/core/Pagination/PageInput/PageInput.tsx, src/core/utils/Debounce/Debounce.tsx
This PR updates the version of react types in order to avoid typing issues in projects using the library.
Some components needed minor adjustments due to the update, which are included in this PR.
Multiple projects reported having to do some typing hacks in order to use the library with newer react types. Updating the types to the library was the easiest solution option, and didn't seem to cause any issues.
Tested by building and using in a react+vite project where the older version caused a typing issue. This seemed to fix it.
- Update `@types/react` to 18.3.3
=> [Feature] React types update

src/core/Form/FileInput/FileInput.baseStyles.tsx
PR fixes a cosmetic issue in FileInput multifile list. The horizontal line separating the items was not correct. 
Styleguidist (where the issue did not manifest in the first place for some reason...) and a separate CRA project
Before
After
- Fix multifile list styles
=> FileInput: Fix multifile list separator CSS

src/core/Form/FileInput/FileInput.baseStyles.tsx, src/core/Form/FileInput/FileInput.tsx, src/core/Form/FileInput/FileItem.tsx, src/core/Form/FileInput/__snapshots__/FileInput.test.tsx.snap
PR fixes various a11y related issues in the `<FileInput>` component as discussed in ticket https://jira.dvv.fi/browse/SFIDS-974 
- The component's structure now has a HTML fieldset + legend at the top level to limit the number of `<label>` elements
- In single file mode, the actual input is not focusable after a file has been selected. Focus moves to the "Remove" button instead
- File names are not focusable anymore when `filePreview` is not used
- Fixed redundant role=listitem when using single file mode
Styleguidist on macOS Chrome + Safari
- Fix various accessibility related issues
=> [Fix] Adjust FileInput accessibility

src/core/Navigation/WizardNavigation/WizardNavigation/WizardNavigation.md
PR updates `<WizardNavigation>` styleguidist docs to include more information about the required aria-attributes. Also removes unnecessary tabIndex props from inner RouterLinks
- Update documentation regarding aria-attributes and the usage of tabIndex
=> [Fix] Update WizardNav docs

src/core/Details/Details.md
Thre was a small accessibility issue in the varied content example of `Details` component documentation. Details content shouldn't contain headings. This PR changes simplifies the varied content example and fixes the accessibility issue in the process.
This came up in the accessibility validation and needed to be fixed.
Locally on styleguidist
=> [Fix] Details varied content example accessibility

package-lock.json, src/core/Form/TimeInput/TimeInput.baseStyles.tsx, src/core/Form/TimeInput/TimeInput.tsx, src/core/Form/TimeInput/__snapshots__/TimeInput.test.tsx.snap
This PR removes the non-functioning `fullWidth` prop from `TimeInput` altogether. It is not useful since the input entry length is limited anyway, and there are no use cases where the input value needs to be longer.
This was a redundant entry in the components API with no real implementation behind it.
**Breaking change:** Remove redundant `fullWidth` prop
=> [Fix] TimeInput redundant fullWidth prop

package-lock.json, package.json, src/core/Expander/Expander/__snapshots__/Expander.test.tsx.snap, src/core/Expander/ExpanderContent/ExpanderContent.baseStyles.tsx, src/core/Expander/ExpanderContent/__snapshots__/ExpanderContent.test.tsx.snap, src/core/Expander/ExpanderGroup/__snapshots__/ExpanderGroup.test.tsx.snap
This PR addresses a bug that appeared in Chrome version 129, where Expander content didn't become fully visible due to the bug in the animation. The decided solution was to remove the open animation altogether. This PR also patches some vulnerable dependencies.
This was an acute bug that affects end-users and needed to be fixed ASAP
Tested by running locally on styleguidist on Chrome version 129. The changes made seem to have fixed the bug.
- Patch vulnerable dependencies
- Remove open animation and transition styles
=> [Hotfix] Remove ExpanderContent animation

src/core/Form/RadioButton/RadioButton.baseStyles.tsx, src/core/Form/RadioButton/RadioButton.md, src/core/Form/RadioButton/RadioButton.tsx, src/core/Form/RadioButton/RadioButtonGroup.baseStyles.tsx, src/core/Form/RadioButton/RadioButtonGroup.test.tsx, src/core/Form/RadioButton/RadioButtonGroup.tsx, src/core/Form/RadioButton/__snapshots__/RadioButton.test.tsx.snap, src/core/Form/RadioButton/__snapshots__/RadioButtonGroup.test.tsx.snap
PR adds `groupStatus` and `groupStatusText` props to `<RadioButtonGroup>`. They work similarly compared to the ones found in `<CheckboxGroup>` and the code is mostly copy-paste from there. 
As a "side effect", an individual `<RadioButton>` component can also now take in a `status` prop, but its usage is not illustrated on the documentation page. Radios are typically used in a group. 
This feature is a no-brainer but has not been implemented before for one reason or another.
macOS Chrome/Safari + VoiceOver
- Add `groupStatus` and `groupStatusText` props
=> [Feature] RadioButtonGroup: Add groupStatus & groupStatusText

src/core/Form/Select/BaseSelect/SelectItem/SelectItem.tsx, src/reset/HtmlMark/HtmlMark.tsx
This PR adds style reset version of the html `<mark>` component to the library and replaces existing instances of `<mark>` with the new component, `<HtmlMark>`.
Previously `SelectItem` used the native html `<mark>` component, and apparently some default bootstrap styles broke the styles of the component. Thus a reset version was needed. 
Tested by running locally on styleguidist on Win + Chrome. Still needs to be tested in a test project where the existing issue can be reproduced and thus test the fix properly.
* Reset styles for `<mark>` components inside the library
=> [Feature] Add HtmlMark component

src/core/Form/FileInput/FileInput.tsx, src/core/Form/FileInput/FileItem.tsx
Upon building there was a warning about a circular dependency between `FileInput` and `FileItem`. It seemed to have originated from the shared class name object. Separating FileItem classes to reside in the correct file seems to have fixed the issue.
Tested by building locally and checking that the warning message no longer appears upon building. 
- Fix circular dependency between FileInput and FileItem
=> [Fix] FileInput & FileItem circular dependency

src/core/Form/DateInput/DatePicker/DatePicker.tsx
This PR fixes an issue where an escape key press in `DatePicker` would propagate outside the component, causing unwanted side effects. One example of a side effect is when a `DateInput` with `DatePicker` is used inside a modal. Before this fix, pressing escape to close the date picker would also close the containing modal.
This was a bug reported by a service using the library.
Tested by placing a DateInput inside of a modal and checking the behavior before and after the fix.
* Stop event propagation of escape keypress
=> [Fix] DatePicker escape key event propagation

rollup.config.mjs, src/core/Breadcrumb/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, src/core/Form/ErrorSummary/__snapshots__/ErrorSummary.test.tsx.snap, src/core/Link/BaseLink/BaseLink.baseStyles.ts, src/core/Link/ExternalLink/ExternalLink.tsx, src/core/Link/ExternalLink/__snapshots__/ExternalLink.test.tsx.snap, src/core/Link/Link/Link.tsx, src/core/Link/Link/__snapshots__/Link.test.tsx.snap, src/core/Link/LinkList/__snapshots__/LinkList.test.tsx.snap, src/core/Link/RouterLink/__snapshots__/RouterLink.test.tsx.snap, src/core/Link/SkipLink/__snapshots__/SkipLink.test.tsx.snap, src/core/Navigation/ServiceNavigation/ServiceNavigation/__snapshots__/ServiceNavigation.test.tsx.snap, src/core/Navigation/SideNavigation/SideNavigation/__snapshots__/SideNavigation.test.tsx.snap, src/core/Navigation/WizardNavigation/WizardNavigation/__snapshots__/WizardNavigation.test.tsx.snap, src/reset/HtmlMark/HtmlMark.tsx
After updating dependencies, an issue appeared, where project builds would fail with an error referring to a missing theme object. It seems that somehow updating styled-components broke passing theme object down from the `styled` level of the components to the underlying JSX code. Link components used the theme to provide a color for the accent icon when used which caused the error.
This PR changes the styling of the icons to use CSS instead, which seems to fix the issue.
In addition, this PR fixes the styled import syntax on recently added HtmlMark component  and adds an `interop: 'auto'` setting to the rollup config to improve CJS compatibility.
This was a major bug which needed to be fixed.
Tested locally on styleguidist on chrome, on DS-site where this error manifested without the …
=> [Bugfix] Missing Link theme object

.circleci/config.yml, src/core/Form/FileInput/FileInput.md, src/core/Form/FileInput/FileInput.tsx, src/core/Form/FileInput/FileItem.tsx, src/core/Form/index.ts, src/index.tsx
This PR brings a new feature to FileInput, which allows it to be used in controlled state without having to store the actual file data in the component state. This can be accomplished by providing the component with an object with the necessary metadata, and storing the actual file elsewhere.
This was a request from several projects, where there were forms with possibly tens of files added. Storing the actual file data in the component state got really unoptimal in those cases.
Tested locally on styleguidist on chrome as well as in a React+Vite test project. Also tested in one of the projects that requested this feature.
- File is no longer required in `ControlledFileItem`
- Providing the necessary metadata for the component is now enough, which provides more flexibility in terms of where …
=> [Feature] FileInput controlled state without file data

src/core/Notification/Notification.baseStyles.ts, src/core/Notification/__snapshots__/Notification.test.tsx.snap, src/core/Toast/Toast.baseStyles.tsx, src/core/Toast/Toast.md, src/core/Toast/Toast.test.tsx, src/core/Toast/Toast.tsx, src/core/Toast/__snapshots__/Toast.test.tsx.snap
This PR adds the option to add a close button to the `Toast` component. The implementation is similar to that in notification and alert.
This PR also fixes the close button size in `Notification` small screen variant.
This was a request from a project, where they had situations with multiple Toasts open at the same time, which blocked a fair chunk of the UI in smaller screens.
Tested by running locally on styleguidist as well as a React+Vite test project.
- Add option for close button
=> [Feature] Toast close button

package-lock.json, package.json
This PR updates the `suomifi-icons` library to its latest version, 7.4.0. This brings one additional icon into the mix.
Dependencies should be kept up to date
By running styleguidist and checkin that the new icon is found and works as intended
- Update `suomifi-icons` to 7.4.0
=> [Dependencies] Update suomifi-icons to 7.4.0

src/core/Pagination/Pagination.md, src/core/Pagination/Pagination.test.tsx, src/core/Pagination/Pagination.tsx, src/index.tsx
This PR adds the possibility to replace the page change buttons with a custom component in Pagination. It also updates all the examples to show the preferred accessibility behavior upon page change, which is to focus the heading of the content area or a relevant focusable list element.
This was a request from a service using the library. Using buttons for browsing the pages prevents search engines from indexing the paginated content. Thus they wanted the possibility to use links instead.
Tested by running locally on styleguidist
- Allow replacing browse buttons with custom components
=> [Feature] Pagination accessibility and custom button variant

src/core/Table/Table.baseStyles.tsx, src/core/Table/Table.md, src/core/Table/Table.test.tsx, src/core/Table/Table.tsx, src/core/Table/__snapshots__/Table.test.tsx.snap
This PR makes a few prop additions to the Table component as well as a some CSS adjustments
It was noticed in pattern testing that these features were missing
Styleguidist on macOS Chrome + Safari
- Add `tableSortCallback` prop
- Add `loading` and `loadingRowAmount` props
- Fix sorting of numerical data
- Adjust checkbox and radiobutton selection CSS
=> [Feature] Table additions

src/core/Form/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
PR fixes a visual issue which appears in version 15.0.1 in the `<Dropdown>` component. Changing box-sizing to border-box in`<SelectItemList>` seems to fix it.
An annoying visual glitch which needs addressing
macOS Chrome + Safari
Before:
After:
- Fix dropdown width glitch
=> [Fix] Dropdown width glitch

src/core/Form/FileInput/FileInput.tsx
This PR fixes the drag and drop logic in `FileInput` to correctly handle cases where files get dropped into a single file FileInput. Previously dropping a file into a single file FileInput with already a file in it resulted in "bricking" the component for the user. The case was the same for dropping multiple file into a single file FileInput.
This PR should fix these issues without any adverse effects.
This was a bug that was noticed while making other changes to the component. Bugs need to be fixed.
Tested locally on styleguidist on chrome. 
* Fix drag and drop file handling in single file variant
=> [Bugfix] Drag and drop file handling in single file variant

src/core/Table/Table.baseStyles.tsx, src/core/Table/Table.md, src/core/Table/Table.tsx, src/core/Table/__snapshots__/Table.test.tsx.snap
PR makes the `<Table>` component's wrapping div focusable when it has horizontal scroll. This is due to Safari not being able to handle scrolling with a keyboard otherwise.
This issue was reported by an accessibility expert
macOS Chrome + Safari in styleguidist
- Make the component's wrapping div focusable when it has horizontal scroll to allow keyboard scrolling on Safari
=> [Fix] Table horizontal scroll a11y

src/core/Form/FileInput/FileInput.baseStyles.tsx, src/core/Form/FileInput/__snapshots__/FileInput.test.tsx.snap
FileInput had some issues with long filenames breaking the styles of the file list and/or the input in some cases. This should be remedied by giving it the possibility to break words.
This PR applies this fix. It also changes the FileInput button content word break rule so that it doesn't break words.
This was a reported bug that needed fixing.
Tested by running locally on styleguidist on Chrome and testing with different component combinations.
* **Breaking change**: change word break rules for file list items and input button
=> [Fix] FileInput long names

README.md, package-lock.json, package.json, src/core/ActionMenu/ActionMenuPopover/ActionMenuPopover.baseStyles.tsx, src/core/ActionMenu/ActionMenuPopover/ActionMenuPopover.tsx, src/core/ActionMenu/__snapshots__/ActionMenu.test.tsx.snap, src/core/Form/DateInput/DateInput.test.tsx, src/core/Form/DateInput/DatePicker/DatePicker.baseStyles.tsx, src/core/Form/DateInput/DatePicker/DatePicker.tsx, src/core/Form/DateInput/__snapshots__/DateInput.test.tsx.snap, src/core/Form/Dropdown/Dropdown/Dropdown.tsx, src/core/Form/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Select/MultiSelect/MultiSelect/MultiSelect.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/SingleSelect.tsx, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, src/core/LanguageMenu/LanguageMenuPopover/LanguageMenuPopover.baseStyles.tsx, src/core/LanguageMenu/LanguageMenuPopover/LanguageMenuPopover.tsx, src/core/LanguageMenu/__snapshots__/LanguageMenu.test.tsx.snap, src/core/Popover/Popover.tsx
PR updates two dependencies to officially support React 19: 
`react-modal` 3.16.1 --> 3.16.3
`popperjs` --> `floating-ui`
Migrating to floating-ui required quite a few code changes (since the APIs are quite different) but the end-user result and our component APIs remain unchanged
Also added `popoverClassName` prop to Dropdown, SingleSelect and MultiSelect
We want to officially support React 19. While the old deps seemed to work with with R19, their peer deps only officially supported R18.
By running the components in Styleguidist macOS Chrome + Safari and checking that no React version warnings come up when installing the library into a React 19 project.
- `react-modal` 3.16.1 --> 3.16.3
- Migrate from `popperjs` to `floating-ui`
- Affects the under-the-hood implementations of the …
=> [Chore] React 19 dependency updates + popoverClassName props

src/core/Form/FileInput/FileInput.tsx, src/core/Form/FileInput/FileItem.tsx
This PR addresses several issues in the FileInput component:
* File preview link is now only shown for items that don't have a status of `error` or 'loading'
* Removed a redundant key from the metadata interface
* To avoid empty file size in UI, show file size of `0 B` when the size is either zero or undefined/null
These were minor issues that were reported by developers using the component and needed to be addressed.
Tested by running locally in styleguidist on chrome, since the changes were straightforward
* **Breaking change:** Prevent showing preview link for files that have a status of `error` or  `loading`
* **Breaking change:** Show file size of `0 B` for empty files and when file size is undefined
* Removed a redundant key from file metadata interface
=> [Fix] FileInput file preview improvements

src/core/Form/Dropdown/Dropdown/Dropdown.tsx, src/core/Form/Select/SingleSelect/SingleSelect.tsx
PR fixes an issue in the `<Dropdown>` and `<SingleSelect>` components where setting the controlled value from a defined value to undefined did not clear the input as intuitively expected.
This was reported by a user
Styleguidist
- Fix issue of input not clearing when setting `value` from a defined value to undefined
- Fix issue of input not clearing when setting `selectedItem` from a defined value to undefined
=> [Fix]: Dropdown and SingleSelect undefined value

src/core/ActionMenu/ActionMenu.tsx
This PR changes the button content type for ActionMenu from string to ReactNode to allow for more versatile content when needed. This is the type in other similar components already.
This was requested by a developer using the component.
Tested by automated unit tests and by running locally on styleguidist.
* **Breaking change:** Change `buttonText` prop type from `string` to `ReactNode`
=> [Feature] Change ActionMenu button content type

src/core/Form/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/core/Form/Select/BaseSelect/SelectItemList/SelectItemList.baseStyles.tsx, src/core/Form/Select/MultiSelect/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, src/core/Form/Select/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
This PR will fix the flicker of components that use popover, when the popover is near the bottom of the page. The issue was due to mismatch in popover size depending on its position, and fix is simple.
This is a clear and rather visible bug and needs to be fixed.
Tested by running locally on styleguidist on chrome
=> [Fix] Popover flicker near bottom of the page

src/core/Modal/Modal/__snapshots__/Modal.test.tsx.snap, src/core/Modal/ModalFooter/ModalFooter.baseStyles.tsx, src/core/Modal/ModalFooter/__snapshots__/ModalFooter.test.tsx.snap
PR adds `display: flex` to Modal footer content. This ensures elements inside it are displayed side by side. In full screen mode, also add `flex-direction: column` to make the content stack vertically
There was an issue where buttons did not appear inline inside the footer when one button had the `loading` state. Loading state applies `display: flex` to the button which breaks the layout. Making this change to the Modal footer styles mitigates the issue.
macOS Chrome, Styleguidist
- **Breaking change**: Add `display: flex` to Modal footer
=> [Fix] Modal footer display
